# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `alchemrest` gem.
# Please instead update this file by running `bin/tapioca gem alchemrest`.


# typed: true

# source://alchemrest-sentry/1.1.1/lib/alchemrest/sentry.rb#5
module Alchemrest
  class << self
    # source://alchemrest//lib/alchemrest.rb#103
    def deprecator; end

    # source://alchemrest//lib/alchemrest.rb#107
    def filter_parameters; end

    # source://alchemrest//lib/alchemrest.rb#111
    def filter_parameters=(params); end

    # source://alchemrest//lib/alchemrest.rb#136
    def handle_rescued_result(error); end

    # source://alchemrest//lib/alchemrest.rb#152
    def kill_switch_adapter; end

    # source://alchemrest//lib/alchemrest.rb#156
    def kill_switch_adapter=(adapter); end

    # source://alchemrest//lib/alchemrest.rb#94
    sig { returns(Logger) }
    def logger; end

    # source://alchemrest//lib/alchemrest.rb#98
    def logger=(logger); end

    # source://alchemrest//lib/alchemrest.rb#123
    def on_response_captured(&block); end

    # source://alchemrest//lib/alchemrest.rb#119
    def on_result_rescued(&block); end

    # source://alchemrest//lib/alchemrest.rb#115
    def parameter_filter; end

    # source://alchemrest//lib/alchemrest.rb#144
    def rescuable_exceptions; end

    # source://alchemrest//lib/alchemrest.rb#148
    def rescuable_exceptions=(exceptions); end

    # source://alchemrest//lib/alchemrest.rb#132
    def restore_default_response_capture_behavior; end

    # source://alchemrest//lib/alchemrest.rb#128
    def restore_default_result_rescue_behavior; end
  end
end

# source://alchemrest//lib/alchemrest/error.rb#74
class Alchemrest::AuthError < ::Alchemrest::ClientError; end

# source://alchemrest//lib/alchemrest/circuit_breaker.rb#4
class Alchemrest::CircuitBreaker
  include ::Memosa::Initializer
  include ::Alchemrest::CircuitBreaker::MemosaMethods
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods
  extend ::Memosa

  # source://alchemrest//lib/alchemrest/circuit_breaker.rb#30
  def initialize(args); end

  # source://anima/0.3.2/lib/anima.rb#142
  def disabled_when; end

  # source://alchemrest//lib/alchemrest/circuit_breaker.rb#34
  def enabled?; end

  # source://anima/0.3.2/lib/anima.rb#142
  def error_threshold; end

  # source://alchemrest//lib/alchemrest/circuit_breaker.rb#42
  def monitor!(result:); end

  # source://alchemrest//lib/alchemrest/circuit_breaker.rb#38
  def open?; end

  # source://anima/0.3.2/lib/anima.rb#142
  def service_name; end

  # source://anima/0.3.2/lib/anima.rb#142
  def sleep_window; end

  # source://anima/0.3.2/lib/anima.rb#142
  def time_window; end

  # source://anima/0.3.2/lib/anima.rb#142
  def volume_threshold; end

  private

  # source://memosa/0.8.3/lib/memosa.rb#44
  def circuit_box; end

  # source://alchemrest//lib/alchemrest/circuit_breaker.rb#69
  def circuit_box_options; end

  # source://alchemrest//lib/alchemrest/circuit_breaker.rb#56
  def request_failed?(result:); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/circuit_breaker.rb#17
Alchemrest::CircuitBreaker::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/circuit_breaker.rb#0
module Alchemrest::CircuitBreaker::MemosaMethods
  private

  # source://memosa/0.8.3/lib/memosa.rb#44
  def circuit_box; end
end

# source://alchemrest//lib/alchemrest/circuit_breaker.rb#15
class Alchemrest::CircuitBreaker::RequestFailed < ::StandardError; end

# source://alchemrest//lib/alchemrest/error.rb#88
class Alchemrest::CircuitOpenError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/client/configuration/connection.rb#6
class Alchemrest::Client
  # source://alchemrest//lib/alchemrest/client.rb#40
  def build_http_request(request); end

  # source://alchemrest//lib/alchemrest/client.rb#44
  def build_response(raw_response); end

  # source://alchemrest//lib/alchemrest/client.rb#36
  def configuration; end

  class << self
    # source://alchemrest//lib/alchemrest/client.rb#17
    def configuration; end

    # source://alchemrest//lib/alchemrest/client.rb#23
    def configure(&configuration_block); end

    # source://alchemrest//lib/alchemrest/client.rb#5
    def inherited(subclass); end

    # source://alchemrest//lib/alchemrest/client.rb#32
    def kill_switch; end
  end
end

# source://alchemrest//lib/alchemrest/client/configuration/connection.rb#7
class Alchemrest::Client::Configuration
  # source://alchemrest//lib/alchemrest/client/configuration.rb#14
  def initialize; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#9
  def circuit_breaker; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#18
  sig { returns(Alchemrest::Client::Configuration::Connection) }
  def connection; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#22
  def freeze; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#9
  def kill_switch_enabled; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#12
  def kill_switch_enabled?; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#37
  def ready?; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#6
  def service_name; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#6
  def service_name=(_arg0); end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#6
  def underscore_response_body_keys; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#6
  def underscore_response_body_keys=(_arg0); end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#41
  def use_circuit_breaker(circuit_breaker_option = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#57
  def use_kill_switch(value = T.unsafe(nil)); end

  private

  # source://alchemrest//lib/alchemrest/client/configuration.rb#81
  def build_default_circuit_breaker(options = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#77
  def default_service_name; end

  # source://alchemrest//lib/alchemrest/client/configuration.rb#66
  def ensure_service_name!; end
end

# source://alchemrest//lib/alchemrest/client/configuration/connection.rb#8
class Alchemrest::Client::Configuration::Connection
  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#12
  def initialize(client_configuration); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#10
  def client_configuration; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#22
  def create_new_connection; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#17
  def customize(use_default_middleware: T.unsafe(nil), &block); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#9
  def customize_block; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#9
  def customize_block=(_arg0); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#34
  def freeze; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#9
  def headers; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#9
  def headers=(_arg0); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#9
  def url; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#9
  def url=(_arg0); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#10
  def use_default_middleware; end

  private

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#61
  def apply_configuration(connection); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#66
  def apply_middleware(connection); end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#53
  def kill_switch_adapter_ready?; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#49
  def underscore_response_body_keys?; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#41
  def use_default_middleware?; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#45
  def use_kill_switch?; end

  # source://alchemrest//lib/alchemrest/client/configuration/connection.rb#57
  def validate!; end
end

# source://alchemrest//lib/alchemrest/error.rb#72
class Alchemrest::ClientError < ::Alchemrest::ResponseError; end

# source://alchemrest//lib/alchemrest/error.rb#107
class Alchemrest::ConfigurationNotReadyError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest.rb#90
Alchemrest::DEFAULT_FILTER_PARAMETERS = T.let(T.unsafe(nil), Array)

# source://alchemrest//lib/alchemrest.rb#88
Alchemrest::DEFAULT_RESCUABLE_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# source://alchemrest//lib/alchemrest/data/field.rb#4
class Alchemrest::Data
  sig { params(attributes: T.untyped).void }
  def initialize(**attributes); end

  sig { returns(T::Hash[T.untyped, T.untyped]) }
  def to_h; end

  class << self
    sig { returns(T.class_of(Alchemrest::Data)) }
    def []; end

    sig { params(blk: T.proc.bind(Alchemrest::Data::CaptureConfiguration).void).void }
    def configure_response_capture(&blk); end

    sig { params(hash: T::Hash[T.any(Symbol, String), T.untyped]).returns(T.attached_class) }
    def from_hash(hash); end

    sig { returns(Alchemrest::Data::Graph) }
    def graph; end

    # source://alchemrest//lib/alchemrest/data.rb#5
    sig { void }
    def schema; end
  end
end

# source://alchemrest//lib/alchemrest/data/capture_configuration.rb#18
class Alchemrest::Data::CaptureConfiguration
  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#21
  def initialize(host_class:, path_to_payload: T.unsafe(nil), omitted_keys: T.unsafe(nil), safe_keys: T.unsafe(nil), &block); end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#58
  sig { params(keys: Symbol).void }
  def omitted(*keys); end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#19
  def omitted_keys; end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#47
  def omitted_paths; end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#19
  def path_to_payload; end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#54
  sig { params(keys: Symbol).void }
  def safe(*keys); end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#19
  def safe_keys; end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#40
  def safe_paths; end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#31
  def with_path_to_payload(path_to_payload); end

  private

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#64
  def get_child_paths(type); end

  # source://alchemrest//lib/alchemrest/data/capture_configuration.rb#72
  def prefix_with_path_to_payload_nodes(path); end
end

# source://alchemrest//lib/alchemrest/data/field.rb#5
class Alchemrest::Data::Field
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/data/field.rb#8
  def initialize(transform:, name:, required: T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/data/field.rb#31
  sig { returns(T::Array[Alchemrest::Transforms::Constraint]) }
  def constraints; end

  # source://anima/0.3.2/lib/anima.rb#142
  def name; end

  # source://alchemrest//lib/alchemrest/data/field.rb#20
  sig { returns(T.nilable(Alchemrest::Transforms::OutputType)) }
  def output_type; end

  # source://anima/0.3.2/lib/anima.rb#142
  def required; end

  # source://anima/0.3.2/lib/anima.rb#142
  def transform; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/data/graph.rb#6
class Alchemrest::Data::Graph
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/data/graph.rb#9
  def initialize(type:, sub_graphs: T.unsafe(nil), fields: T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/data/graph.rb#25
  def children; end

  # source://anima/0.3.2/lib/anima.rb#142
  sig { returns(T::Hash[Symbol, Alchemrest::Data::Field]) }
  def fields; end

  # source://anima/0.3.2/lib/anima.rb#142
  sig { returns(T::Hash[Symbol, Alchemrest::Data::Graph]) }
  def sub_graphs; end

  # source://anima/0.3.2/lib/anima.rb#142
  sig { returns(T.class_of(Alchemrest::Data)) }
  def type; end

  private

  # source://alchemrest//lib/alchemrest/data/graph.rb#35
  def fields_hash_has_correct_types?(fields:); end

  # source://alchemrest//lib/alchemrest/data/graph.rb#31
  def sub_graph_hash_has_correct_types?(sub_graphs:); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/data/record.rb#5
class Alchemrest::Data::Record < ::Module
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://anima/0.3.2/lib/anima.rb#142
  def allow_additional_properties; end

  # source://alchemrest//lib/alchemrest/data/record.rb#19
  def included(host); end

  # source://anima/0.3.2/lib/anima.rb#142
  def optional; end

  # source://anima/0.3.2/lib/anima.rb#142
  def required; end

  private

  # source://alchemrest//lib/alchemrest/data/record.rb#53
  def transform(attributes); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end

    # source://alchemrest//lib/alchemrest/data/record.rb#14
    def new(**attributes); end
  end
end

# source://alchemrest//lib/alchemrest/data/record.rb#6
Alchemrest::Data::Record::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/data/schema.rb#5
class Alchemrest::Data::Schema < ::Alchemrest::Data::Record
  # source://alchemrest//lib/alchemrest/data/schema.rb#6
  def included(host); end

  private

  # source://alchemrest//lib/alchemrest/data/schema.rb#42
  def extract_fields; end

  # source://alchemrest//lib/alchemrest/data/schema.rb#28
  def extract_graph(host); end

  # source://alchemrest//lib/alchemrest/data/schema.rb#36
  def extract_sub_graphs; end
end

# source://alchemrest//lib/alchemrest/data/schema.rb#48
module Alchemrest::Data::Schema::ClassMethods
  # source://alchemrest//lib/alchemrest/data/schema.rb#66
  def []; end

  # source://alchemrest//lib/alchemrest/data/schema.rb#49
  def capture_configuration; end

  # source://alchemrest//lib/alchemrest/data/schema.rb#74
  def configure_response_capture(&_arg0); end

  # source://alchemrest//lib/alchemrest/data/schema.rb#57
  def from_hash(hash); end

  # source://alchemrest//lib/alchemrest/data/schema.rb#70
  def graph; end

  # source://alchemrest//lib/alchemrest/data/schema.rb#53
  def response_transformer; end
end

# source://alchemrest//lib/alchemrest/endpoint_definition.rb#4
class Alchemrest::EndpointDefinition
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/endpoint_definition.rb#10
  def initialize(template:, http_method:, builder_block:); end

  # source://anima/0.3.2/lib/anima.rb#142
  def builder_block; end

  # source://anima/0.3.2/lib/anima.rb#142
  def http_method; end

  # source://alchemrest//lib/alchemrest/endpoint_definition.rb#24
  def params_for(context); end

  # source://anima/0.3.2/lib/anima.rb#142
  def template; end

  # source://alchemrest//lib/alchemrest/endpoint_definition.rb#20
  def url_for(context); end

  private

  # source://alchemrest//lib/alchemrest/endpoint_definition.rb#35
  def build_for(context); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/endpoint_definition.rb#5
Alchemrest::EndpointDefinition::VALID_HTTP_METHODS = T.let(T.unsafe(nil), Set)

# source://alchemrest//lib/alchemrest/error.rb#4
class Alchemrest::Error < ::StandardError
  # source://alchemrest//lib/alchemrest/error.rb#5
  def deconstruct; end

  # source://alchemrest//lib/alchemrest/error.rb#9
  def deconstruct_keys(_keys); end
end

# source://alchemrest//lib/alchemrest/factory_bot.rb#4
module Alchemrest::FactoryBot
  class << self
    # source://alchemrest//lib/alchemrest/factory_bot.rb#5
    def enable!; end
  end
end

# source://alchemrest//lib/alchemrest/factory_bot.rb#36
class Alchemrest::FactoryBot::AlchemrestStrategy
  # source://alchemrest//lib/alchemrest/factory_bot.rb#37
  def association(runner); end

  # source://alchemrest//lib/alchemrest/factory_bot.rb#41
  def result(evaluation); end

  # source://alchemrest//lib/alchemrest/factory_bot.rb#45
  def to_sym; end
end

# source://alchemrest//lib/alchemrest/factory_bot.rb#50
class Alchemrest::FactoryBot::HashStrategy
  # source://alchemrest//lib/alchemrest/factory_bot.rb#51
  def association(runner); end

  # source://alchemrest//lib/alchemrest/factory_bot.rb#55
  def result(evaluation); end

  # source://alchemrest//lib/alchemrest/factory_bot.rb#59
  def to_sym; end
end

# source://alchemrest//lib/alchemrest/factory_bot.rb#18
module Alchemrest::FactoryBot::Mixins
  # source://alchemrest//lib/alchemrest/factory_bot.rb#19
  def alchemrest_factory(name, options = T.unsafe(nil), &block); end
end

# source://alchemrest//lib/alchemrest/factory_bot.rb#14
class Alchemrest::FactoryBot::OmitKey
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  class << self
    private

    def allocate; end
    def new(*_arg0); end
  end
end

# source://alchemrest//lib/alchemrest/faraday_middleware/json_parser.rb#4
module Alchemrest::FaradayMiddleware; end

# source://alchemrest//lib/alchemrest/faraday_middleware/external_api_instrumentation.rb#5
class Alchemrest::FaradayMiddleware::ExternalApiInstrumentation < ::Faraday::Middleware
  # source://alchemrest//lib/alchemrest/faraday_middleware/external_api_instrumentation.rb#8
  def initialize(app, options = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/faraday_middleware/external_api_instrumentation.rb#13
  def call(env); end

  # source://alchemrest//lib/alchemrest/faraday_middleware/external_api_instrumentation.rb#6
  def external_service; end

  # source://alchemrest//lib/alchemrest/faraday_middleware/external_api_instrumentation.rb#19
  def name; end
end

# source://alchemrest//lib/alchemrest/faraday_middleware/json_parser.rb#5
class Alchemrest::FaradayMiddleware::JsonParser < ::Faraday::Middleware
  # source://alchemrest//lib/alchemrest/faraday_middleware/json_parser.rb#8
  def on_complete(env); end

  # source://alchemrest//lib/alchemrest/faraday_middleware/json_parser.rb#21
  def parse_body(raw_body); end

  # source://alchemrest//lib/alchemrest/faraday_middleware/json_parser.rb#25
  def parseable_body(raw_body); end
end

# source://alchemrest//lib/alchemrest/faraday_middleware/json_parser.rb#6
Alchemrest::FaradayMiddleware::JsonParser::DEFAULT_RESPONSE = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/faraday_middleware/kill_switch.rb#5
class Alchemrest::FaradayMiddleware::KillSwitch < ::Faraday::Middleware
  # source://alchemrest//lib/alchemrest/faraday_middleware/kill_switch.rb#8
  def initialize(app, options = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/faraday_middleware/kill_switch.rb#13
  def call(env); end

  # source://alchemrest//lib/alchemrest/faraday_middleware/kill_switch.rb#6
  def service_name; end
end

# source://alchemrest//lib/alchemrest/faraday_middleware/underscore_response.rb#5
class Alchemrest::FaradayMiddleware::UnderScoreResponse < ::Faraday::Middleware
  # source://alchemrest//lib/alchemrest/faraday_middleware/underscore_response.rb#6
  def on_complete(env); end

  private

  # source://alchemrest//lib/alchemrest/faraday_middleware/underscore_response.rb#12
  def deep_transform_keys!(object); end
end

# source://alchemrest//lib/alchemrest/hash_path.rb#18
class Alchemrest::HashPath
  include ::Equalizer::Methods

  # source://concord/0.1.6/lib/concord.rb#67
  def segments; end

  # source://alchemrest//lib/alchemrest/hash_path.rb#41
  def walk(input, &block); end

  private

  # source://alchemrest//lib/alchemrest/hash_path.rb#64
  def traverse(node, remaining_segments, path, &block); end

  class << self
    # source://alchemrest//lib/alchemrest/hash_path.rb#28
    def build_collection(definition); end

    private

    # source://alchemrest//lib/alchemrest/hash_path.rb#48
    def visit_leaves(input, path = T.unsafe(nil), &block); end
  end
end

# source://alchemrest//lib/alchemrest/http_request.rb#6
class Alchemrest::HttpRequest < ::SimpleDelegator
  include ::Memosa::Initializer
  include ::Alchemrest::HttpRequest::MemosaMethods
  extend ::Memosa

  # source://alchemrest//lib/alchemrest/http_request.rb#9
  def initialize(request, client); end

  # source://alchemrest//lib/alchemrest/http_request.rb#26
  def execute!; end

  # source://alchemrest//lib/alchemrest/http_request.rb#22
  def headers; end

  # source://alchemrest//lib/alchemrest/http_request.rb#18
  def url; end

  private

  # source://alchemrest//lib/alchemrest/http_request.rb#38
  def build_response(raw_response); end

  # source://memosa/0.8.3/lib/memosa.rb#44
  def circuit_breaker; end

  # source://alchemrest//lib/alchemrest/http_request.rb#65
  def handle_faraday_error(error); end

  # source://alchemrest//lib/alchemrest/http_request.rb#46
  def make_request!; end

  # source://alchemrest//lib/alchemrest/http_request.rb#61
  def modify_faraday_request(req); end
end

# source://alchemrest//lib/alchemrest/http_request.rb#0
module Alchemrest::HttpRequest::MemosaMethods
  private

  # source://memosa/0.8.3/lib/memosa.rb#44
  def circuit_breaker; end
end

# source://alchemrest//lib/alchemrest/error.rb#105
class Alchemrest::InvalidConfigurationError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/kill_switch.rb#4
class Alchemrest::KillSwitch
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/kill_switch.rb#7
  def initialize(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch.rb#17
  def activate!; end

  # source://alchemrest//lib/alchemrest/kill_switch.rb#13
  def active?; end

  # source://alchemrest//lib/alchemrest/kill_switch.rb#21
  def deactivate!; end

  # source://anima/0.3.2/lib/anima.rb#142
  def service_name; end

  private

  # source://alchemrest//lib/alchemrest/kill_switch.rb#27
  def adapter; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#7
module Alchemrest::KillSwitch::Adapters; end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#51
class Alchemrest::KillSwitch::Adapters::ActiveRecord
  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#66
  def activate(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#62
  def active?(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#70
  def deactivate(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#58
  def ready?; end

  private

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#80
  def load_record(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#76
  def set(service_name:, enabled:); end
end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#52
class Alchemrest::KillSwitch::Adapters::ActiveRecord::Record < ::ActiveRecord::Base
  include ::Alchemrest::KillSwitch::Adapters::ActiveRecord::Record::GeneratedAttributeMethods
  include ::Alchemrest::KillSwitch::Adapters::ActiveRecord::Record::GeneratedAssociationMethods

  class << self
    private

    # source://activesupport/8.0.4.1/lib/active_support/class_attribute.rb#15
    def __class_attr__validators; end

    # source://activesupport/8.0.4.1/lib/active_support/class_attribute.rb#17
    def __class_attr__validators=(new_value); end

    # source://activesupport/8.0.4.1/lib/active_support/class_attribute.rb#15
    def __class_attr_defined_enums; end

    # source://activesupport/8.0.4.1/lib/active_support/class_attribute.rb#17
    def __class_attr_defined_enums=(new_value); end
  end
end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#0
module Alchemrest::KillSwitch::Adapters::ActiveRecord::Record::GeneratedAssociationMethods; end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#0
module Alchemrest::KillSwitch::Adapters::ActiveRecord::Record::GeneratedAttributeMethods; end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#8
class Alchemrest::KillSwitch::Adapters::Test
  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#17
  def initialize; end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#29
  def activate(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#25
  def active?(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#33
  def deactivate(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#21
  def ready?; end

  private

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#44
  def load_record(service_name:); end

  # source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#39
  def set(service_name:, enabled:); end
end

# source://alchemrest//lib/alchemrest/kill_switch/adapters.rb#9
class Alchemrest::KillSwitch::Adapters::Test::Record
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://anima/0.3.2/lib/anima.rb#142
  def enabled; end

  # source://anima/0.3.2/lib/anima.rb#142
  def enabled?; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/error.rb#109
class Alchemrest::KillSwitchEnabledError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/error.rb#90
class Alchemrest::MorpherTransformError < ::Alchemrest::Error
  # source://alchemrest//lib/alchemrest/error.rb#93
  def initialize(error); end

  # source://alchemrest//lib/alchemrest/error.rb#91
  def error; end

  # source://alchemrest//lib/alchemrest/error.rb#98
  def to_s; end
end

# source://alchemrest//lib/alchemrest/error.rb#111
class Alchemrest::NoRegisteredTransformError < ::Alchemrest::Error
  # source://alchemrest//lib/alchemrest/error.rb#112
  def initialize(from:, to:); end
end

# source://alchemrest//lib/alchemrest/error.rb#117
class Alchemrest::NoTransformOptionForNameError < ::Alchemrest::Error
  # source://alchemrest//lib/alchemrest/error.rb#118
  def initialize(from:, to:, name:, options:); end
end

# source://alchemrest//lib/alchemrest/error.rb#76
class Alchemrest::NotFoundError < ::Alchemrest::ClientError; end

# source://alchemrest//lib/alchemrest/railtie.rb#6
class Alchemrest::Railtie < ::Rails::Railtie; end

# source://alchemrest//lib/alchemrest/request/endpoint.rb#4
class Alchemrest::Request
  # source://alchemrest//lib/alchemrest/request.rb#44
  def body; end

  # source://alchemrest//lib/alchemrest/request.rb#54
  def capture_transformer; end

  # source://alchemrest//lib/alchemrest/request.rb#36
  def default_headers; end

  # source://alchemrest//lib/alchemrest/request.rb#40
  def headers; end

  # source://alchemrest//lib/alchemrest/request.rb#32
  def http_method; end

  # source://alchemrest//lib/alchemrest/request.rb#70
  def identifier; end

  # source://alchemrest//lib/alchemrest/request.rb#28
  def path; end

  # source://alchemrest//lib/alchemrest/request.rb#61
  def response_capture_enabled; end

  # source://alchemrest//lib/alchemrest/request.rb#48
  def response_transformer; end

  # source://alchemrest//lib/alchemrest/request.rb#65
  def transform_response(response); end

  private

  # source://alchemrest//lib/alchemrest/request.rb#76
  def capture!(response:); end

  class << self
    # source://alchemrest//lib/alchemrest/request.rb#24
    def disable_response_capture; end

    # source://alchemrest//lib/alchemrest/request.rb#20
    sig { void }
    def enable_response_capture; end

    # source://alchemrest//lib/alchemrest/request.rb#14
    sig do
      params(
        http_method: Symbol,
        template: String,
        block: T.nilable(T.proc.bind(T.attached_class).params(url: Alchemrest::UrlBuilder::Options).void)
      ).void
    end
    def endpoint(http_method, template, &block); end

    # source://alchemrest//lib/alchemrest/request.rb#10
    sig do
      params(
        domain_type: T.class_of(Alchemrest::Data),
        path_to_payload: T::Array[T.any(Symbol, String)],
        allow_empty_response: T::Boolean
      ).void
    end
    def returns(domain_type, path_to_payload: T.unsafe(nil), allow_empty_response: T.unsafe(nil)); end
  end
end

# source://alchemrest//lib/alchemrest/request.rb#7
Alchemrest::Request::DEFAULT_HEADERS = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/request/endpoint.rb#5
class Alchemrest::Request::Endpoint < ::Module
  include ::Equalizer::Methods

  # source://concord/0.1.6/lib/concord.rb#67
  def endpoint_definition; end

  # source://alchemrest//lib/alchemrest/request/endpoint.rb#8
  def included(_); end
end

# source://alchemrest//lib/alchemrest/request/endpoint.rb#18
module Alchemrest::Request::Endpoint::InstanceMethods
  # source://alchemrest//lib/alchemrest/request/endpoint.rb#23
  def http_method; end

  # source://alchemrest//lib/alchemrest/request/endpoint.rb#19
  def path; end
end

# source://alchemrest//lib/alchemrest/request/returns.rb#5
class Alchemrest::Request::Returns < ::Module
  include ::Equalizer::Methods

  # source://concord/0.1.6/lib/concord.rb#67
  def allow_empty_response; end

  # source://concord/0.1.6/lib/concord.rb#67
  def domain_type; end

  # source://alchemrest//lib/alchemrest/request/returns.rb#8
  def included(request_class); end

  # source://alchemrest//lib/alchemrest/request/returns.rb#33
  def omit_step; end

  # source://concord/0.1.6/lib/concord.rb#67
  def path_to_payload; end

  # source://alchemrest//lib/alchemrest/request/returns.rb#27
  def sanitize_step; end

  private

  # source://alchemrest//lib/alchemrest/request/returns.rb#41
  def capture_configuration; end
end

# source://alchemrest//lib/alchemrest/request_definition.rb#7
class Alchemrest::RequestDefinition
  # source://alchemrest//lib/alchemrest/request_definition.rb#10
  def initialize(name, request_class, &block); end

  # source://alchemrest//lib/alchemrest/request_definition.rb#16
  def build_request(context, params = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/request_definition.rb#8
  def name; end
end

# source://alchemrest//lib/alchemrest/request_definition/builder.rb#5
class Alchemrest::RequestDefinition::Builder
  # source://alchemrest//lib/alchemrest/request_definition/builder.rb#6
  def initialize; end

  # source://alchemrest//lib/alchemrest/request_definition/builder.rb#10
  def defaults; end

  # source://alchemrest//lib/alchemrest/request_definition/builder.rb#10
  def defaults=(_arg0); end
end

# source://alchemrest//lib/alchemrest/error.rb#80
class Alchemrest::RequestFailedError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/response.rb#7
class Alchemrest::Response < ::SimpleDelegator
  include ::Memosa::Initializer
  include ::Alchemrest::Response::MemosaMethods
  extend ::Memosa

  # source://alchemrest//lib/alchemrest/response.rb#35
  def auth_error?; end

  sig { returns(T.untyped) }
  def body; end

  # source://alchemrest//lib/alchemrest/response.rb#55
  def circuit_open?; end

  # source://alchemrest//lib/alchemrest/response.rb#31
  def client_error?; end

  # source://alchemrest//lib/alchemrest/response.rb#10
  def data; end

  # source://memosa/0.8.3/lib/memosa.rb#44
  def error; end

  # source://alchemrest//lib/alchemrest/response.rb#23
  def error_details; end

  sig { returns(T::Hash[T.untyped, T.untyped]) }
  def headers; end

  # source://alchemrest//lib/alchemrest/response.rb#43
  def no_content_response?; end

  # source://alchemrest//lib/alchemrest/response.rb#39
  def not_found_error?; end

  sig { returns(String) }
  def reason_phrase; end

  # source://alchemrest//lib/alchemrest/response.rb#47
  def request_failed?; end

  # source://alchemrest//lib/alchemrest/response.rb#27
  def server_error?; end

  sig { returns(Integer) }
  def status; end

  sig { returns(T::Boolean) }
  def success?; end

  # source://alchemrest//lib/alchemrest/response.rb#51
  def timeout?; end

  # source://alchemrest//lib/alchemrest/response.rb#14
  def to_result; end
end

# source://alchemrest//lib/alchemrest/response.rb#0
module Alchemrest::Response::MemosaMethods
  # source://memosa/0.8.3/lib/memosa.rb#44
  def error; end
end

# source://alchemrest//lib/alchemrest/response/pipeline.rb#15
class Alchemrest::Response::Pipeline
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/response/pipeline.rb#18
  def initialize(*steps); end

  # source://alchemrest//lib/alchemrest/response/pipeline.rb#41
  def append(step); end

  # source://alchemrest//lib/alchemrest/response/pipeline.rb#22
  def call(response); end

  # source://alchemrest//lib/alchemrest/response/pipeline.rb#34
  def insert_after(step_class, step); end

  # source://alchemrest//lib/alchemrest/response/pipeline.rb#45
  def replace_with(step_class, step); end

  # source://concord/0.1.6/lib/concord.rb#67
  def steps; end

  private

  # source://alchemrest//lib/alchemrest/response/pipeline.rb#57
  def build_error_result(error); end
end

# source://alchemrest//lib/alchemrest/response/pipeline/extract_payload.rb#10
class Alchemrest::Response::Pipeline::ExtractPayload < ::Alchemrest::Response::Pipeline::Transform
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/response/pipeline/extract_payload.rb#17
  def initialize(_path_to_payload = T.unsafe(nil), _allow_empty_response = T.unsafe(nil)); end

  # source://concord/0.1.6/lib/concord.rb#67
  def allow_empty_response; end

  # source://alchemrest//lib/alchemrest/response/pipeline/extract_payload.rb#21
  def call(response); end

  # source://alchemrest//lib/alchemrest/response/pipeline/extract_payload.rb#37
  def extract_payload(response); end

  # source://concord/0.1.6/lib/concord.rb#67
  def path_to_payload; end

  private

  # source://alchemrest//lib/alchemrest/response/pipeline/extract_payload.rb#58
  def allow_empty_response?; end
end

# source://alchemrest//lib/alchemrest/response/pipeline/final.rb#6
class Alchemrest::Response::Pipeline::Final
  include ::Equalizer::Methods

  # source://concord/0.1.6/lib/concord.rb#67
  def value; end
end

# source://alchemrest//lib/alchemrest/response/pipeline/omit.rb#6
class Alchemrest::Response::Pipeline::Omit < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/response/pipeline/omit.rb#11
  def initialize(omit = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/response/pipeline/omit.rb#16
  def call(input); end

  # source://alchemrest//lib/alchemrest/response/pipeline/omit.rb#34
  def delete_from(input); end

  # source://concord/0.1.6/lib/concord.rb#67
  def omit; end

  # source://alchemrest//lib/alchemrest/response/pipeline/omit.rb#26
  def omit_nodes(input); end
end

# source://alchemrest//lib/alchemrest/response/pipeline/omit.rb#9
Alchemrest::Response::Pipeline::Omit::PRIMITIVE = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#6
class Alchemrest::Response::Pipeline::Sanitize < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#10
  def initialize(args = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#15
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def safe; end

  private

  # source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#35
  def copy(original, filtered); end

  # source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#48
  def hash_has_key?(hash, path, key); end

  # source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#27
  def sanitize(input); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/response/pipeline/sanitize.rb#8
Alchemrest::Response::Pipeline::Sanitize::PRIMITIVE = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://alchemrest//lib/alchemrest/response/pipeline/transform.rb#12
class Alchemrest::Response::Pipeline::Transform < ::Morpher::Transform
  # source://alchemrest//lib/alchemrest/response/pipeline/transform.rb#13
  def failure(error); end

  # source://alchemrest//lib/alchemrest/response/pipeline/transform.rb#20
  def final(value); end
end

# source://alchemrest//lib/alchemrest/response/pipeline/was_successful.rb#10
class Alchemrest::Response::Pipeline::WasSuccessful < ::Alchemrest::Response::Pipeline::Transform
  # source://alchemrest//lib/alchemrest/response/pipeline/was_successful.rb#15
  def ==(other); end

  # source://alchemrest//lib/alchemrest/response/pipeline/was_successful.rb#19
  def call(response); end

  # source://alchemrest//lib/alchemrest/response/pipeline/was_successful.rb#11
  def eql?(other); end
end

# source://alchemrest//lib/alchemrest/response_captured_handler.rb#4
class Alchemrest::ResponseCapturedHandler
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/response_captured_handler.rb#21
  def call; end

  # source://anima/0.3.2/lib/anima.rb#142
  def request; end

  # source://anima/0.3.2/lib/anima.rb#142
  def response; end

  private

  # source://alchemrest//lib/alchemrest/response_captured_handler.rb#39
  def capture_pipeline_result; end

  # source://alchemrest//lib/alchemrest/response_captured_handler.rb#59
  def default_capture_method; end

  # source://alchemrest//lib/alchemrest/response_captured_handler.rb#43
  def identifier; end

  # source://alchemrest//lib/alchemrest/response_captured_handler.rb#47
  def legacy_capture_handler; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/response_captured_handler.rb#5
Alchemrest::ResponseCapturedHandler::LEGACY_ON_RESPONSE_CAPTURED_METHOD_DEFINITION_MESSAGE = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/error.rb#14
class Alchemrest::ResponseError < ::Alchemrest::Error
  # source://alchemrest//lib/alchemrest/error.rb#17
  def initialize(response); end

  # source://alchemrest//lib/alchemrest/error.rb#31
  def deconstruct; end

  # source://alchemrest//lib/alchemrest/error.rb#35
  def deconstruct_keys(_keys); end

  # source://alchemrest//lib/alchemrest/error.rb#15
  def response; end

  # source://alchemrest//lib/alchemrest/error.rb#22
  def to_s; end
end

# source://alchemrest//lib/alchemrest/error.rb#103
class Alchemrest::ResponsePipelineError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/result.rb#4
class Alchemrest::Result
  extend T::Generic

  abstract!
  sealed!

  ValueType = type_member(:out)

  # source://alchemrest//lib/alchemrest/result.rb#82
  def initialize(*_arg0); end

  sig { params(other: T.untyped).returns(T::Boolean) }
  def ==(other); end

  sig { returns(T::Boolean) }
  def ok?; end

  # source://alchemrest//lib/alchemrest/result.rb#86
  def transform; end

  # source://alchemrest//lib/alchemrest/result.rb#114
  sig { returns(ValueType) }
  def unwrap_or_raise!; end

  # source://alchemrest//lib/alchemrest/result.rb#101
  def unwrap_or_rescue; end

  protected

  # source://alchemrest//lib/alchemrest/result.rb#122
  def error; end

  # source://alchemrest//lib/alchemrest/result.rb#122
  def value; end

  private

  # source://alchemrest//lib/alchemrest/result.rb#126
  def error=(_arg0); end

  # source://alchemrest//lib/alchemrest/result.rb#126
  def value=(_arg0); end

  class << self
    # source://alchemrest//lib/alchemrest/result.rb#65
    sig { params(error: T.any(Exception, String)).returns(Alchemrest::Result::Error) }
    def Error(error); end

    # source://alchemrest//lib/alchemrest/result.rb#61
    sig do
      type_parameters(:Value)
        .params(
          value: T.type_parameter(:Value)
        ).returns(Alchemrest::Result::Ok[T.type_parameter(:Value)])
    end
    def Ok(value); end

    # source://alchemrest//lib/alchemrest/result.rb#6
    def [](*_types); end

    # source://alchemrest//lib/alchemrest/result.rb#69
    def for; end
  end
end

# source://alchemrest//lib/alchemrest/result.rb#32
class Alchemrest::Result::Error < ::Alchemrest::Result
  ValueType = type_member { { fixed: T.noreturn } }

  # source://alchemrest//lib/alchemrest/result.rb#33
  sig { params(error: T.any(String, Exception)).void }
  def initialize(error); end

  # source://alchemrest//lib/alchemrest/result.rb#44
  def ==(other); end

  # source://alchemrest//lib/alchemrest/result.rb#52
  sig { returns([Exception]) }
  def deconstruct; end

  # source://alchemrest//lib/alchemrest/result.rb#56
  sig { params(_keys: T.untyped).returns({ error: Exception }) }
  def deconstruct_keys(_keys); end

  # source://alchemrest//lib/alchemrest/result.rb#48
  def ok?; end
end

# source://alchemrest//lib/alchemrest/result/halt.rb#5
class Alchemrest::Result::Halt < ::StandardError
  # source://alchemrest//lib/alchemrest/result/halt.rb#8
  def initialize(original_error); end

  # source://alchemrest//lib/alchemrest/result/halt.rb#6
  def error; end
end

# source://alchemrest//lib/alchemrest/result.rb#10
class Alchemrest::Result::Ok < ::Alchemrest::Result
  ValueType = type_member

  # source://alchemrest//lib/alchemrest/result.rb#11
  sig { params(value: ValueType).void }
  def initialize(value); end

  # source://alchemrest//lib/alchemrest/result.rb#15
  def ==(other); end

  # source://alchemrest//lib/alchemrest/result.rb#23
  sig { returns([ValueType]) }
  def deconstruct; end

  # source://alchemrest//lib/alchemrest/result.rb#27
  sig { params(_keys: T.untyped).returns({ value: ValueType }) }
  def deconstruct_keys(_keys); end

  # source://alchemrest//lib/alchemrest/result.rb#19
  def ok?; end
end

# source://alchemrest//lib/alchemrest/result/try_helpers.rb#5
module Alchemrest::Result::TryHelpers
  class << self
    # source://alchemrest//lib/alchemrest/result/try_helpers.rb#6
    sig do
      type_parameters(:Value)
        .params(
          result: Alchemrest::Result[T.type_parameter(:Value)]
        ).returns(T.type_parameter(:Value))
    end
    def unwrap(result); end
  end
end

# source://alchemrest//lib/alchemrest/error.rb#86
class Alchemrest::ResultRescued < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/root.rb#4
class Alchemrest::Root
  # source://alchemrest//lib/alchemrest/root.rb#49
  sig { params(name: Symbol, params: T::Hash[Symbol, T.untyped]).returns(Alchemrest::Request) }
  def build_request(name, params = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/root.rb#59
  sig { returns(Alchemrest::Client) }
  def client; end

  class << self
    # source://alchemrest//lib/alchemrest/root.rb#16
    sig do
      params(
        name: Symbol,
        request_class: T.class_of(Alchemrest::Request),
        block: T.nilable(
        T.proc
         .params(request: Alchemrest::RequestDefinition::Builder)
         .bind(T.attached_class)
         .void,
      )
      ).void
    end
    def define_request(name, request_class, &block); end

    # source://alchemrest//lib/alchemrest/root.rb#35
    def error_handler; end

    # source://alchemrest//lib/alchemrest/root.rb#45
    sig { params(block: T.proc.bind(T.attached_class).params(error: Exception).void).void }
    def on_alchemrest_error(&block); end

    # source://alchemrest//lib/alchemrest/root.rb#12
    sig { returns(T::Hash[Symbol, Alchemrest::RequestDefinition]) }
    def request_definitions; end

    # source://alchemrest//lib/alchemrest/root.rb#41
    def reset_error_handler!; end

    # source://alchemrest//lib/alchemrest/root.rb#7
    sig { params(client_class: T.class_of(Alchemrest::Client)).void }
    def use_client(client_class); end
  end

  WithParams = T.type_alias { T.proc.returns(T::Hash[Symbol, T.untyped]) }
end

# source://alchemrest//lib/alchemrest/error.rb#40
class Alchemrest::ServerError < ::Alchemrest::ResponseError
  # source://alchemrest//lib/alchemrest/error.rb#43
  def initialize(response, cause = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/error.rb#41
  def cause; end

  # source://alchemrest//lib/alchemrest/error.rb#41
  def response; end

  # source://alchemrest//lib/alchemrest/error.rb#49
  def to_s; end

  private

  # source://alchemrest//lib/alchemrest/error.rb#61
  def error_message; end
end

# source://alchemrest//lib/alchemrest/error.rb#82
class Alchemrest::TimeoutError < ::Alchemrest::RequestFailedError; end

# source://alchemrest//lib/alchemrest/error.rb#84
class Alchemrest::TransformError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/transforms.rb#13
module Alchemrest::Transforms
  class << self
    # source://alchemrest//lib/alchemrest/transforms.rb#44
    def boolean; end

    # source://alchemrest//lib/alchemrest/transforms.rb#50
    def date; end

    # source://alchemrest//lib/alchemrest/transforms.rb#69
    def enum(enum); end

    # source://alchemrest//lib/alchemrest/transforms.rb#29
    def float; end

    # source://alchemrest//lib/alchemrest/transforms.rb#33
    def from; end

    # source://alchemrest//lib/alchemrest/transforms.rb#16
    def integer; end

    # source://alchemrest//lib/alchemrest/transforms.rb#89
    def many_of(klass); end

    # source://alchemrest//lib/alchemrest/transforms.rb#60
    def money(unit); end

    # source://alchemrest//lib/alchemrest/transforms.rb#39
    def number; end

    # source://alchemrest//lib/alchemrest/transforms.rb#80
    def one_of(klass_or_hash); end

    # source://alchemrest//lib/alchemrest/transforms.rb#22
    def string; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/base_to_type_transform_registry.rb#5
class Alchemrest::Transforms::BaseToTypeTransformRegistry
  include ::AbstractType
  include ::Equalizer::Methods
  extend ::AbstractType::AbstractMethodDeclarations

  # source://alchemrest//lib/alchemrest/transforms/base_to_type_transform_registry.rb#11
  def initialize(*args); end

  # source://abstract_type/0.0.7/lib/abstract_type.rb#111
  def build_transforms(*_arg0); end

  # source://alchemrest//lib/alchemrest/transforms/base_to_type_transform_registry.rb#16
  def resolve(type); end

  private

  # source://alchemrest//lib/alchemrest/transforms/base_to_type_transform_registry.rb#26
  def build_internal_registry_hash(transforms); end

  class << self
    # source://abstract_type/0.0.7/lib/abstract_type.rb#33
    def new(*args, &block); end
  end
end

# source://alchemrest//lib/alchemrest/transforms/constrainable.rb#8
class Alchemrest::Transforms::Constrainable < ::Anima
  # source://alchemrest//lib/alchemrest/transforms/constrainable.rb#9
  def initialize(args = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/transforms/constrainable.rb#14
  def included(base); end
end

# source://alchemrest//lib/alchemrest/transforms/constrainable.rb#19
module Alchemrest::Transforms::Constrainable::InstanceMethods
  # source://alchemrest//lib/alchemrest/transforms/constrainable.rb#20
  def where(constraint_or_description, &block); end

  private

  # source://alchemrest//lib/alchemrest/transforms/constrainable.rb#34
  def validate_constraints; end
end

# source://alchemrest//lib/alchemrest/transforms/constraint.rb#10
class Alchemrest::Transforms::Constraint
  include ::AbstractType
  extend ::AbstractType::AbstractMethodDeclarations

  # source://abstract_type/0.0.7/lib/abstract_type.rb#111
  def description(*_arg0); end

  # source://abstract_type/0.0.7/lib/abstract_type.rb#111
  def meets_conditions?(*_arg0); end

  class << self
    # source://abstract_type/0.0.7/lib/abstract_type.rb#33
    def new(*args, &block); end
  end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/block.rb#6
class Alchemrest::Transforms::Constraint::Block < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/block.rb#10
  def initialize(description, &block); end

  # source://concord/0.1.6/lib/concord.rb#67
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/block.rb#16
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/greater_than.rb#6
class Alchemrest::Transforms::Constraint::GreaterThan < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/greater_than.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/greater_than.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/greater_than_or_eq.rb#6
class Alchemrest::Transforms::Constraint::GreaterThanOrEq < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/greater_than_or_eq.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/greater_than_or_eq.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/in_list.rb#6
class Alchemrest::Transforms::Constraint::InList < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/in_list.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/in_list.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/is_instance_of.rb#6
class Alchemrest::Transforms::Constraint::IsInstanceOf < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/is_instance_of.rb#13
  def description; end

  # source://concord/0.1.6/lib/concord.rb#67
  def klass; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/is_instance_of.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/is_uuid.rb#6
class Alchemrest::Transforms::Constraint::IsUuid < ::Alchemrest::Transforms::Constraint::MatchesRegex
  # source://alchemrest//lib/alchemrest/transforms/constraint/is_uuid.rb#9
  def initialize; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/is_uuid.rb#13
  def description; end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/is_uuid.rb#7
Alchemrest::Transforms::Constraint::IsUuid::REGEX = T.let(T.unsafe(nil), Regexp)

# source://alchemrest//lib/alchemrest/transforms/constraint/less_than.rb#6
class Alchemrest::Transforms::Constraint::LessThan < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/less_than.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/less_than.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/less_than_or_eq.rb#6
class Alchemrest::Transforms::Constraint::LessThanOrEq < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/less_than_or_eq.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/less_than_or_eq.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/matches_regex.rb#6
class Alchemrest::Transforms::Constraint::MatchesRegex < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/matches_regex.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/matches_regex.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/max_length.rb#6
class Alchemrest::Transforms::Constraint::MaxLength < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/max_length.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/max_length.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint/min_length.rb#6
class Alchemrest::Transforms::Constraint::MinLength < ::Alchemrest::Transforms::Constraint
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/constraint/min_length.rb#13
  def description; end

  # source://alchemrest//lib/alchemrest/transforms/constraint/min_length.rb#9
  def meets_conditions?(input); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint_builder.rb#5
class Alchemrest::Transforms::ConstraintBuilder
  include ::Equalizer::Methods

  private

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder.rb#10
  def apply_constraint(constraint); end
end

# source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#6
class Alchemrest::Transforms::ConstraintBuilder::ForNumber < ::Alchemrest::Transforms::ConstraintBuilder
  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#9
  def greater_than(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#13
  def greater_than_or_eq(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#21
  def integer; end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#11
  def less_than(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#15
  def less_than_or_eq(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#19
  def non_negative; end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#17
  def positive; end
end

# source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_number.rb#7
Alchemrest::Transforms::ConstraintBuilder::ForNumber::CONSTRAINT_METHODS = T.let(T.unsafe(nil), Array)

# source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#6
class Alchemrest::Transforms::ConstraintBuilder::ForString < ::Alchemrest::Transforms::ConstraintBuilder
  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#15
  def in(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#13
  def matches(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#9
  def max_length(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#11
  def min_length(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#17
  def must_be_uuid; end
end

# source://alchemrest//lib/alchemrest/transforms/constraint_builder/for_string.rb#7
Alchemrest::Transforms::ConstraintBuilder::ForString::CONSTRAINT_METHODS = T.let(T.unsafe(nil), Array)

# source://alchemrest//lib/alchemrest/transforms/date_transform.rb#7
class Alchemrest::Transforms::DateTransform < ::Morpher::Transform
  # source://alchemrest//lib/alchemrest/transforms/date_transform.rb#8
  def call(input); end

  # source://alchemrest//lib/alchemrest/transforms/date_transform.rb#20
  def not_a_valid_iso_date_string(input); end
end

# source://alchemrest//lib/alchemrest/transforms/enum.rb#5
class Alchemrest::Transforms::Enum < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/enum.rb#10
  def call(input); end

  private

  # source://alchemrest//lib/alchemrest/transforms/enum.rb#23
  def evaluate_array(input); end

  # source://alchemrest//lib/alchemrest/transforms/enum.rb#33
  def evaluate_hash(input); end

  # source://alchemrest//lib/alchemrest/transforms/enum.rb#42
  def failure_error(input); end
end

# source://alchemrest//lib/alchemrest/transforms/epoch_time.rb#7
class Alchemrest::Transforms::EpochTime < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/epoch_time.rb#10
  def call(input); end
end

# source://alchemrest//lib/alchemrest/transforms/from_chain.rb#5
module Alchemrest::Transforms::FromChain
  class << self
    # source://alchemrest//lib/alchemrest/transforms/from_chain.rb#6
    def number; end

    # source://alchemrest//lib/alchemrest/transforms/from_chain.rb#10
    def string; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/from_number.rb#5
class Alchemrest::Transforms::FromNumber < ::Alchemrest::Transforms::FromType
  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#9
  def initialize(args = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def greater_than(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def greater_than_or_eq(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def integer(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def less_than(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def less_than_or_eq(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def non_negative(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#23
  def output_type_name; end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#27
  def positive(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#13
  def where(constraint_or_description = T.unsafe(nil), &block); end

  private

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#31
  def constraint_builder; end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def to_type_transform_registry(&block); end

  # source://alchemrest//lib/alchemrest/transforms/from_number.rb#35
  def transform; end
end

# source://alchemrest//lib/alchemrest/transforms/from_number.rb#7
Alchemrest::Transforms::FromNumber::CONSTRAINT_BUILDER_CLASS = Alchemrest::Transforms::ConstraintBuilder::ForNumber

# source://alchemrest//lib/alchemrest/transforms/from_number.rb#6
Alchemrest::Transforms::FromNumber::OVERRIDES = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/transforms/from_number/to_type_transform_registry.rb#6
class Alchemrest::Transforms::FromNumber::ToTypeTransformRegistry < ::Alchemrest::Transforms::BaseToTypeTransformRegistry
  # source://alchemrest//lib/alchemrest/transforms/from_number/to_type_transform_registry.rb#7
  def build_transforms; end
end

# source://alchemrest//lib/alchemrest/transforms/from_string.rb#5
class Alchemrest::Transforms::FromString < ::Alchemrest::Transforms::FromType
  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#9
  def initialize(args = T.unsafe(nil)); end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#23
  def in(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#23
  def matches(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#23
  def max_length(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#23
  def min_length(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#23
  def must_be_uuid(*_arg0, **_arg1, &_arg2); end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#13
  def where(constraint_or_description = T.unsafe(nil), &block); end

  private

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#27
  def constraint_builder; end

  # source://alchemrest//lib/alchemrest/transforms/from_string.rb#31
  def to_type_transform_registry; end
end

# source://alchemrest//lib/alchemrest/transforms/from_string.rb#7
Alchemrest::Transforms::FromString::CONSTRAINT_BUILDER_CLASS = Alchemrest::Transforms::ConstraintBuilder::ForString

# source://alchemrest//lib/alchemrest/transforms/from_string.rb#6
Alchemrest::Transforms::FromString::OVERRIDES = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/transforms/from_string/to_type_transform_registry.rb#6
class Alchemrest::Transforms::FromString::ToTypeTransformRegistry < ::Alchemrest::Transforms::BaseToTypeTransformRegistry
  # source://alchemrest//lib/alchemrest/transforms/from_string/to_type_transform_registry.rb#7
  def build_transforms; end
end

# source://alchemrest//lib/alchemrest/transforms/from_type.rb#10
class Alchemrest::Transforms::FromType < ::Morpher::Transform
  include ::Alchemrest::Transforms::Constrainable::InstanceMethods
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods
  include ::Adamantium::Mutable

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#15
  def initialize(args); end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#42
  def array; end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#27
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def constraints; end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#46
  def maybe; end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#19
  def output_type; end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#23
  def output_type_name; end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#31
  def to(type, &block); end

  # source://anima/0.3.2/lib/anima.rb#142
  def type; end

  private

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def to_type_transform_registry(&block); end

  # source://alchemrest//lib/alchemrest/transforms/from_type.rb#56
  def transform; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/from_type.rb#13
Alchemrest::Transforms::FromType::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/transforms/from_type/empty_to_type_transform_registry.rb#6
class Alchemrest::Transforms::FromType::EmptyToTypeTransformRegistry < ::Alchemrest::Transforms::BaseToTypeTransformRegistry
  # source://alchemrest//lib/alchemrest/transforms/from_type/empty_to_type_transform_registry.rb#8
  def build_transforms; end
end

# source://alchemrest//lib/alchemrest/transforms/iso_time.rb#7
class Alchemrest::Transforms::IsoTime < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/iso_time.rb#10
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def require_offset; end

  # source://anima/0.3.2/lib/anima.rb#142
  def to_timezone; end

  private

  # source://alchemrest//lib/alchemrest/transforms/iso_time.rb#31
  def has_offset?(input); end

  # source://alchemrest//lib/alchemrest/transforms/iso_time.rb#39
  def missing_required_offset(input); end

  # source://alchemrest//lib/alchemrest/transforms/iso_time.rb#48
  def not_a_valid_iso_string(input); end

  # source://alchemrest//lib/alchemrest/transforms/iso_time.rb#23
  def parse(input); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/json_number.rb#5
class Alchemrest::Transforms::JsonNumber < ::Morpher::Transform
  # source://alchemrest//lib/alchemrest/transforms/json_number.rb#6
  def call(input); end

  private

  # source://alchemrest//lib/alchemrest/transforms/json_number.rb#16
  def failure_error(input); end
end

# source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#5
class Alchemrest::Transforms::LooseHash < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://anima/0.3.2/lib/anima.rb#142
  def allow_additional_properties; end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#18
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def optional; end

  # source://anima/0.3.2/lib/anima.rb#142
  def required; end

  private

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def allowed_keys(&block); end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#63
  def coerce_key(key, input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def defaults(&block); end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#69
  def reject_keys(input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def required_keys(&block); end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#28
  def transform(input); end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#49
  def transform_keys(keys, input); end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#42
  def transform_optional(input); end

  # source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#34
  def transform_required(input); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#8
Alchemrest::Transforms::LooseHash::KEY_MESSAGE = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/transforms/loose_hash.rb#9
Alchemrest::Transforms::LooseHash::PRIMITIVE = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://alchemrest//lib/alchemrest/transforms/money_transform.rb#5
class Alchemrest::Transforms::MoneyTransform < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/money_transform.rb#10
  def call(input); end

  private

  # source://alchemrest//lib/alchemrest/transforms/money_transform.rb#32
  def failure_error(input); end

  # source://alchemrest//lib/alchemrest/transforms/money_transform.rb#21
  def into_money(amount); end
end

# source://alchemrest//lib/alchemrest/transforms/number.rb#5
class Alchemrest::Transforms::Number < ::Morpher::Transform
  # source://alchemrest//lib/alchemrest/transforms/number.rb#6
  def call(input); end

  private

  # source://alchemrest//lib/alchemrest/transforms/number.rb#17
  def failure_error(input); end
end

# source://alchemrest//lib/alchemrest/transforms/output_type.rb#9
class Alchemrest::Transforms::OutputType < ::T::Struct
  const :sorbet_type, T.any(::Class, ::T::Types::Base)
  const :constraints, T::Array[::Alchemrest::Transforms::Constraint]

  # source://alchemrest//lib/alchemrest/transforms/output_type.rb#29
  def ==(other); end

  # source://alchemrest//lib/alchemrest/transforms/output_type.rb#17
  sig { returns(T.nilable(Alchemrest::Data::Graph)) }
  def graph; end

  # source://alchemrest//lib/alchemrest/transforms/output_type.rb#25
  def with(args); end

  private

  # source://alchemrest//lib/alchemrest/transforms/output_type.rb#39
  def graph_types; end

  # source://alchemrest//lib/alchemrest/transforms/output_type.rb#35
  def has_graph?(type); end

  # source://alchemrest//lib/alchemrest/transforms/output_type.rb#43
  def recursively_unwrap_raw_type(type); end

  class << self
    # source://sorbet-runtime/0.5.12135/lib/types/struct.rb#13
    def inherited(s); end

    # source://alchemrest//lib/alchemrest/transforms/output_type.rb#13
    def simple(sorbet_type); end
  end
end

# source://alchemrest//lib/alchemrest/transforms/to_decimal.rb#5
class Alchemrest::Transforms::ToDecimal < ::Morpher::Transform
  # source://alchemrest//lib/alchemrest/transforms/to_decimal.rb#6
  def call(input); end

  # source://alchemrest//lib/alchemrest/transforms/to_decimal.rb#12
  def cannot_make_decimal(input); end
end

# source://alchemrest//lib/alchemrest/transforms/to_type.rb#9
class Alchemrest::Transforms::ToType < ::Morpher::Transform
  include ::Alchemrest::Transforms::Constrainable::InstanceMethods
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#17
  def initialize(args); end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#40
  def all_constraints; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#56
  def array; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#36
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def constraints; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#44
  def constraints_for(type); end

  # source://anima/0.3.2/lib/anima.rb#142
  def from; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#60
  def maybe; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#28
  def output_type; end

  # source://anima/0.3.2/lib/anima.rb#142
  def to; end

  # source://anima/0.3.2/lib/anima.rb#142
  def use; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#32
  def using(transforms); end

  private

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#66
  def transform; end

  # source://alchemrest//lib/alchemrest/transforms/to_type.rb#75
  def validate_output; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end

    # source://alchemrest//lib/alchemrest/transforms/to_type.rb#13
    def using(args, &block); end
  end
end

# source://alchemrest//lib/alchemrest/transforms/to_type.rb#11
Alchemrest::Transforms::ToType::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://alchemrest//lib/alchemrest/transforms/to_type/from_string_to_time_selector.rb#6
class Alchemrest::Transforms::ToType::FromStringToTimeSelector < ::Alchemrest::Transforms::ToType::TransformsSelector
  # source://alchemrest//lib/alchemrest/transforms/to_type/from_string_to_time_selector.rb#7
  def initialize(from); end

  # source://alchemrest//lib/alchemrest/transforms/to_type/from_string_to_time_selector.rb#11
  def using(timezone_identifier, require_offset: T.unsafe(nil)); end
end

# source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#6
class Alchemrest::Transforms::ToType::TransformsSelector
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#12
  def initialize(*_arg0); end

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#31
  def options; end

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#19
  def using(key_or_transform); end

  private

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#43
  def a_symbol_or_transform?(value); end

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#51
  def resolve_transforms_array(value); end

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#47
  def transform_array?(value); end

  # source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#37
  def transform_options_valid?; end
end

# source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#7
Alchemrest::Transforms::ToType::TransformsSelector::INVALID_KEY_OR_TRANSFORM_ERROR_MESSAGE = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/transforms/to_type/transforms_selector.rb#8
Alchemrest::Transforms::ToType::TransformsSelector::INVALID_TRANSFORMS_HASH_ERROR_MESSAGE = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/transforms/typed.rb#9
class Alchemrest::Transforms::Typed < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods
  include ::Adamantium::Mutable

  # source://alchemrest//lib/alchemrest/transforms/typed.rb#17
  def array; end

  # source://alchemrest//lib/alchemrest/transforms/typed.rb#13
  def call(input); end

  # source://alchemrest//lib/alchemrest/transforms/typed.rb#24
  def maybe; end

  # source://anima/0.3.2/lib/anima.rb#142
  def output_type; end

  # source://anima/0.3.2/lib/anima.rb#142
  def transform; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/union.rb#5
class Alchemrest::Transforms::Union < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/union.rb#10
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def discriminator; end

  # source://alchemrest//lib/alchemrest/transforms/union.rb#19
  def output_type; end

  # source://anima/0.3.2/lib/anima.rb#142
  def types; end

  private

  # source://alchemrest//lib/alchemrest/transforms/union.rb#34
  def klass_not_found_failure_error(input); end

  # source://alchemrest//lib/alchemrest/transforms/union.rb#25
  def perform_transformation(input, type_key); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/transforms/with_constraint.rb#5
class Alchemrest::Transforms::WithConstraint < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/transforms/with_constraint.rb#9
  def initialize(constraint); end

  # source://alchemrest//lib/alchemrest/transforms/with_constraint.rb#15
  def call(input); end
end

# source://alchemrest//lib/alchemrest/transforms/with_constraint.rb#6
Alchemrest::Transforms::WithConstraint::MESSAGE = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/error.rb#78
class Alchemrest::UndefinedClientError < ::Alchemrest::Error; end

# source://alchemrest//lib/alchemrest/url_builder.rb#5
class Alchemrest::UrlBuilder
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://alchemrest//lib/alchemrest/url_builder.rb#8
  def initialize(args); end

  # source://anima/0.3.2/lib/anima.rb#142
  def query; end

  # source://anima/0.3.2/lib/anima.rb#142
  def query_param_encoder; end

  # source://anima/0.3.2/lib/anima.rb#142
  def template; end

  # source://alchemrest//lib/alchemrest/url_builder.rb#12
  def url; end

  # source://anima/0.3.2/lib/anima.rb#142
  def values; end

  private

  # source://alchemrest//lib/alchemrest/url_builder.rb#24
  def query_string; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://alchemrest//lib/alchemrest/url_builder/encoders.rb#6
module Alchemrest::UrlBuilder::Encoders
  class << self
    # source://alchemrest//lib/alchemrest/url_builder/encoders.rb#7
    def find(name); end
  end
end

# source://alchemrest//lib/alchemrest/url_builder/encoders.rb#28
class Alchemrest::UrlBuilder::Encoders::Custom
  # source://alchemrest//lib/alchemrest/url_builder/encoders.rb#29
  def initialize(&block); end

  # source://alchemrest//lib/alchemrest/url_builder/encoders.rb#33
  def call(query); end
end

# source://alchemrest//lib/alchemrest/url_builder/encoders.rb#22
class Alchemrest::UrlBuilder::Encoders::FormUrlEncoded
  # source://alchemrest//lib/alchemrest/url_builder/encoders.rb#23
  def call(query); end
end

# source://alchemrest//lib/alchemrest/url_builder/encoders.rb#16
class Alchemrest::UrlBuilder::Encoders::RackEncoded
  # source://alchemrest//lib/alchemrest/url_builder/encoders.rb#17
  def call(query); end
end

# source://alchemrest//lib/alchemrest/url_builder/options.rb#6
class Alchemrest::UrlBuilder::Options
  # source://alchemrest//lib/alchemrest/url_builder/options.rb#23
  def create_builder(template:); end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#19
  def encode_query_with(&_arg0); end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#13
  sig { params(name: Symbol).void }
  def encode_query_with=(name); end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#7
  def query; end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#7
  def query=(_arg0); end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#9
  def query_param_encoder; end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#7
  def values; end

  # source://alchemrest//lib/alchemrest/url_builder/options.rb#7
  def values=(_arg0); end
end

# source://alchemrest//lib/alchemrest/url_builder/options.rb#11
class Alchemrest::UrlBuilder::Options::InvalidEncoderError < ::StandardError; end

# source://alchemrest//lib/alchemrest/version.rb#4
Alchemrest::VERSION = T.let(T.unsafe(nil), String)

# source://alchemrest//lib/alchemrest/webmock_helpers.rb#4
module Alchemrest::WebmockHelpers
  private

  # source://alchemrest//lib/alchemrest/webmock_helpers.rb#5
  def stub_alchemrest_request(alchemrest_request, with_request_body: T.unsafe(nil), with_headers: T.unsafe(nil)); end

  class << self
    # source://alchemrest//lib/alchemrest/webmock_helpers.rb#5
    def stub_alchemrest_request(alchemrest_request, with_request_body: T.unsafe(nil), with_headers: T.unsafe(nil)); end
  end
end
