# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `circuitbox` gem.
# Please instead update this file by running `bin/tapioca gem circuitbox`.


# source://circuitbox//lib/circuitbox/version.rb#3
class Circuitbox
  extend ::Circuitbox::Configuration

  class << self
    # source://circuitbox//lib/circuitbox.rb#36
    def circuit(service_name, options, &block); end
  end
end

# source://circuitbox//lib/circuitbox/circuit_breaker.rb#7
class Circuitbox::CircuitBreaker
  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#31
  def initialize(service, options = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#8
  def circuit_options; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#8
  def circuit_store; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#109
  def error_rate(failures = T.unsafe(nil), success = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#8
  def exceptions; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#119
  def failure_count; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#8
  def notifier; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#102
  def open?; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#58
  def option_value(name); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#78
  def run(exception: T.unsafe(nil), &block); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#8
  def service; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#126
  def success_count; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#8
  def time_class; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#135
  def try_close_next_time; end

  private

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#252
  def align_time_to_window(window = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#257
  def check_sleep_window; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#197
  def close!; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#268
  def default_time_klass; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#220
  def failure!; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#210
  def half_open?; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#164
  def half_open_failure; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#240
  def increment_and_notify_event(event); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#235
  def notify_event(event); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#188
  def notify_opened; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#176
  def open!; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#160
  def passed_rate_threshold?(failures, successes); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#156
  def passed_volume_threshold?(failures, successes); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#141
  def should_open?; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#230
  def skipped!; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#247
  def stat_storage_key(event, aligned_time = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#214
  def success!; end

  # source://circuitbox//lib/circuitbox/circuit_breaker.rb#192
  def trip; end
end

# source://circuitbox//lib/circuitbox/circuit_breaker.rb#11
Circuitbox::CircuitBreaker::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://circuitbox//lib/circuitbox/configuration.rb#8
module Circuitbox::Configuration
  # source://circuitbox//lib/circuitbox/configuration.rb#27
  def configure; end

  # source://circuitbox//lib/circuitbox/configuration.rb#37
  def default_circuit_store; end

  # source://circuitbox//lib/circuitbox/configuration.rb#9
  def default_circuit_store=(_arg0); end

  # source://circuitbox//lib/circuitbox/configuration.rb#46
  def default_notifier; end

  # source://circuitbox//lib/circuitbox/configuration.rb#9
  def default_notifier=(_arg0); end

  private

  # source://circuitbox//lib/circuitbox/configuration.rb#62
  def clear_cached_circuits!; end

  # source://circuitbox//lib/circuitbox/configuration.rb#56
  def find_or_create_circuit_breaker(service_name, options); end

  class << self
    # source://circuitbox//lib/circuitbox/configuration.rb#12
    def extended(base); end
  end
end

# source://circuitbox//lib/circuitbox/errors/error.rb#4
class Circuitbox::Error < ::StandardError; end

# source://circuitbox//lib/circuitbox/memory_store/container.rb#6
class Circuitbox::MemoryStore
  include ::Circuitbox::TimeHelper::Monotonic

  # source://circuitbox//lib/circuitbox/memory_store.rb#10
  def initialize(compaction_frequency: T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#57
  def delete(key); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#24
  def increment(key, amount = T.unsafe(nil), opts = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#53
  def key?(key); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#42
  def load(key, _opts = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#17
  def store(key, value, opts = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#46
  def values_at(*keys, **_opts); end

  private

  # source://circuitbox//lib/circuitbox/memory_store.rb#78
  def compact(current_time); end

  # source://circuitbox//lib/circuitbox/memory_store.rb#63
  def fetch_container(key, current_time = T.unsafe(nil)); end
end

# source://circuitbox//lib/circuitbox/memory_store/container.rb#7
class Circuitbox::MemoryStore::Container
  include ::Circuitbox::TimeHelper::Monotonic

  # source://circuitbox//lib/circuitbox/memory_store/container.rb#12
  def initialize(value:, expiry: T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/memory_store/container.rb#17
  def expired?; end

  # source://circuitbox//lib/circuitbox/memory_store/container.rb#21
  def expired_at?(clock_second); end

  # source://circuitbox//lib/circuitbox/memory_store/container.rb#25
  def expires_after(seconds = T.unsafe(nil)); end

  # source://circuitbox//lib/circuitbox/memory_store/container.rb#10
  def value; end

  # source://circuitbox//lib/circuitbox/memory_store/container.rb#10
  def value=(_arg0); end
end

# source://circuitbox//lib/circuitbox/notifier/active_support.rb#4
module Circuitbox::Notifier; end

# source://circuitbox//lib/circuitbox/notifier/active_support.rb#5
class Circuitbox::Notifier::ActiveSupport
  # source://circuitbox//lib/circuitbox/notifier/active_support.rb#6
  def notify(circuit_name, event); end

  # source://circuitbox//lib/circuitbox/notifier/active_support.rb#14
  def notify_run(circuit_name, &block); end

  # source://circuitbox//lib/circuitbox/notifier/active_support.rb#10
  def notify_warning(circuit_name, message); end
end

# source://circuitbox//lib/circuitbox/notifier/null.rb#5
class Circuitbox::Notifier::Null
  # source://circuitbox//lib/circuitbox/notifier/null.rb#6
  def notify(_circuit_name, _event); end

  # source://circuitbox//lib/circuitbox/notifier/null.rb#10
  def notify_run(_circuit_name); end

  # source://circuitbox//lib/circuitbox/notifier/null.rb#8
  def notify_warning(_circuit_name, _message); end
end

# source://circuitbox//lib/circuitbox/errors/open_circuit_error.rb#4
class Circuitbox::OpenCircuitError < ::Circuitbox::Error
  # source://circuitbox//lib/circuitbox/errors/open_circuit_error.rb#7
  def initialize(service); end

  # source://circuitbox//lib/circuitbox/errors/open_circuit_error.rb#5
  def service; end

  # source://circuitbox//lib/circuitbox/errors/open_circuit_error.rb#12
  def to_s; end
end

# source://circuitbox//lib/circuitbox/errors/service_failure_error.rb#4
class Circuitbox::ServiceFailureError < ::Circuitbox::Error
  # source://circuitbox//lib/circuitbox/errors/service_failure_error.rb#7
  def initialize(service, exception); end

  # source://circuitbox//lib/circuitbox/errors/service_failure_error.rb#5
  def original; end

  # source://circuitbox//lib/circuitbox/errors/service_failure_error.rb#5
  def service; end

  # source://circuitbox//lib/circuitbox/errors/service_failure_error.rb#16
  def to_s; end
end

# source://circuitbox//lib/circuitbox/time_helper/monotonic.rb#4
module Circuitbox::TimeHelper; end

# source://circuitbox//lib/circuitbox/time_helper/monotonic.rb#5
module Circuitbox::TimeHelper::Monotonic
  private

  # source://circuitbox//lib/circuitbox/time_helper/monotonic.rb#8
  def current_second; end

  class << self
    # source://circuitbox//lib/circuitbox/time_helper/monotonic.rb#8
    def current_second; end
  end
end

# source://circuitbox//lib/circuitbox/time_helper/real.rb#5
module Circuitbox::TimeHelper::Real
  private

  # source://circuitbox//lib/circuitbox/time_helper/real.rb#8
  def current_second; end

  class << self
    # source://circuitbox//lib/circuitbox/time_helper/real.rb#8
    def current_second; end
  end
end

# source://circuitbox//lib/circuitbox/version.rb#4
Circuitbox::VERSION = T.let(T.unsafe(nil), String)
