# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `concord` gem.
# Please instead update this file by running `bin/tapioca gem concord`.


# source://concord//lib/concord.rb#5
class Concord < ::Module
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat

  # source://concord//lib/concord.rb#27
  def initialize(*names); end

  # source://concord//lib/concord.rb#17
  def names; end

  private

  # source://concord//lib/concord.rb#54
  def define_equalizer; end

  # source://concord//lib/concord.rb#80
  def define_initialize; end

  # source://concord//lib/concord.rb#64
  def define_readers; end

  # source://concord//lib/concord.rb#44
  def included(descendant); end

  # source://concord//lib/concord.rb#100
  def instance_variable_names; end
end

# source://concord//lib/concord.rb#9
Concord::MAX_NR_OF_OBJECTS = T.let(T.unsafe(nil), Integer)

# source://concord//lib/concord.rb#105
class Concord::Public < ::Concord
  # source://concord//lib/concord.rb#115
  def included(descendant); end
end
