# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `hansi` gem.
# Please instead update this file by running `bin/tapioca gem hansi`.


# source://hansi//lib/hansi.rb#1
module Hansi
  class << self
    # source://hansi//lib/hansi.rb#4
    def [](*args); end

    # source://hansi//lib/hansi.rb#37
    def color_names; end

    # source://hansi//lib/hansi.rb#8
    def mode; end

    # source://hansi//lib/hansi.rb#12
    def mode=(value); end

    # source://hansi//lib/hansi.rb#16
    def mode_for(env, **options); end

    # source://hansi//lib/hansi.rb#20
    def render(*input, **options); end

    # source://hansi//lib/hansi.rb#24
    def renderer_for(input); end

    # source://hansi//lib/hansi.rb#33
    def reset; end
  end
end

# source://hansi//lib/hansi/ansi_code.rb#2
class Hansi::AnsiCode
  # source://hansi//lib/hansi/ansi_code.rb#3
  def to_ansi_code(**options); end

  # source://hansi//lib/hansi/ansi_code.rb#10
  def to_css(*names, &block); end

  # source://hansi//lib/hansi/ansi_code.rb#6
  def to_css_rule; end
end

# source://hansi//lib/hansi/color.rb#2
class Hansi::Color < ::Hansi::AnsiCode
  # source://hansi//lib/hansi/color.rb#6
  def initialize(red, green, blue); end

  # source://hansi//lib/hansi/color.rb#15
  def ==(other); end

  # source://hansi//lib/hansi/color.rb#3
  def blue; end

  # source://hansi//lib/hansi/color.rb#32
  def closest(set); end

  # source://hansi//lib/hansi/color.rb#23
  def distance(other); end

  # source://hansi//lib/hansi/color.rb#19
  def eql?(other); end

  # source://hansi//lib/hansi/color.rb#3
  def green; end

  # source://hansi//lib/hansi/color.rb#11
  def hash; end

  # source://hansi//lib/hansi/color.rb#56
  def inspect; end

  # source://hansi//lib/hansi/color.rb#3
  def red; end

  # source://hansi//lib/hansi/color.rb#68
  def to_ansi(mode: T.unsafe(nil), **options); end

  # source://hansi//lib/hansi/color.rb#92
  def to_ansi_16colors(**options); end

  # source://hansi//lib/hansi/color.rb#80
  def to_ansi_24bit(**options); end

  # source://hansi//lib/hansi/color.rb#84
  def to_ansi_256colors(**options); end

  # source://hansi//lib/hansi/color.rb#88
  def to_ansi_88colors(**options); end

  # source://hansi//lib/hansi/color.rb#96
  def to_ansi_8colors(**options); end

  # source://hansi//lib/hansi/color.rb#64
  def to_css_rule; end

  # source://hansi//lib/hansi/color.rb#52
  def to_i; end

  # source://hansi//lib/hansi/color.rb#60
  def to_s; end

  # source://hansi//lib/hansi/color.rb#100
  def to_web_name(**options); end

  # source://hansi//lib/hansi/color.rb#43
  def to_yuv; end

  protected

  # source://hansi//lib/hansi/color.rb#3
  def distance_cache; end

  private

  # source://hansi//lib/hansi/color.rb#104
  def from_palette(main, *fallback, exact: T.unsafe(nil)); end
end

# source://hansi//lib/hansi/color_parser.rb#2
class Hansi::ColorParser
  # source://hansi//lib/hansi/color_parser.rb#11
  def initialize; end

  # source://hansi//lib/hansi/color_parser.rb#89
  def illegal(value); end

  # source://hansi//lib/hansi/color_parser.rb#15
  def parse(values, potentially_illegal: T.unsafe(nil)); end

  # source://hansi//lib/hansi/color_parser.rb#75
  def parse_ansi(string, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#47
  def parse_color(color, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#51
  def parse_float(value, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#43
  def parse_hash(potentially_illegal, red: T.unsafe(nil), green: T.unsafe(nil), blue: T.unsafe(nil)); end

  # source://hansi//lib/hansi/color_parser.rb#56
  def parse_integer(value, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#61
  def parse_string(string, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#83
  def parse_symbol(symbol, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#31
  def parse_value(value, potentially_illegal); end

  # source://hansi//lib/hansi/color_parser.rb#19
  def parse_values(values, potentially_illegal); end

  class << self
    # source://hansi//lib/hansi/color_parser.rb#6
    def parse(*values); end

    private

    def new(*_arg0); end
  end
end

# source://hansi//lib/hansi/color_parser.rb#3
class Hansi::ColorParser::IllegalValue < ::ArgumentError; end

# source://hansi//lib/hansi/color_renderer.rb#4
class Hansi::ColorRenderer
  # source://hansi//lib/hansi/color_renderer.rb#9
  def initialize(mode: T.unsafe(nil), join: T.unsafe(nil)); end

  # source://hansi//lib/hansi/color_renderer.rb#14
  def render(color, *input); end

  class << self
    # source://hansi//lib/hansi/color_renderer.rb#5
    def render(*input, **options); end
  end
end

# source://hansi//lib/hansi/mode_detector.rb#4
class Hansi::ModeDetector
  # source://hansi//lib/hansi/mode_detector.rb#31
  def initialize(env, shell_out: T.unsafe(nil), io: T.unsafe(nil), supported: T.unsafe(nil)); end

  # source://hansi//lib/hansi/mode_detector.rb#89
  def actual_xterm?; end

  # source://hansi//lib/hansi/mode_detector.rb#143
  def commands; end

  # source://hansi//lib/hansi/mode_detector.rb#30
  def env; end

  # source://hansi//lib/hansi/mode_detector.rb#59
  def from_term; end

  # source://hansi//lib/hansi/mode_detector.rb#54
  def from_term_program; end

  # source://hansi//lib/hansi/mode_detector.rb#47
  def from_tput; end

  # source://hansi//lib/hansi/mode_detector.rb#69
  def from_xterm; end

  # source://hansi//lib/hansi/mode_detector.rb#136
  def full_terminal_command; end

  # source://hansi//lib/hansi/mode_detector.rb#85
  def gnome_terminal?; end

  # source://hansi//lib/hansi/mode_detector.rb#103
  def gnome_true_color?; end

  # source://hansi//lib/hansi/mode_detector.rb#30
  def io; end

  # source://hansi//lib/hansi/mode_detector.rb#93
  def iterm?; end

  # source://hansi//lib/hansi/mode_detector.rb#110
  def iterm_true_color?; end

  # source://hansi//lib/hansi/mode_detector.rb#120
  def iterm_version; end

  # source://hansi//lib/hansi/mode_detector.rb#183
  def maximum; end

  # source://hansi//lib/hansi/mode_detector.rb#192
  def minimum; end

  # source://hansi//lib/hansi/mode_detector.rb#37
  def mode; end

  # source://hansi//lib/hansi/mode_detector.rb#156
  def processes; end

  # source://hansi//lib/hansi/mode_detector.rb#166
  def shell_out?; end

  # source://hansi//lib/hansi/mode_detector.rb#30
  def supported; end

  # source://hansi//lib/hansi/mode_detector.rb#174
  def supported?(value); end

  # source://hansi//lib/hansi/mode_detector.rb#73
  def term; end

  # source://hansi//lib/hansi/mode_detector.rb#130
  def terminal_command(command = T.unsafe(nil)); end

  # source://hansi//lib/hansi/mode_detector.rb#77
  def true_color?; end

  # source://hansi//lib/hansi/mode_detector.rb#170
  def windows?; end

  # source://hansi//lib/hansi/mode_detector.rb#97
  def xterm_true_color?; end
end

# source://hansi//lib/hansi/mode_detector.rb#25
Hansi::ModeDetector::COMMANDS = T.let(T.unsafe(nil), Array)

# source://hansi//lib/hansi/mode_detector.rb#5
Hansi::ModeDetector::TERMS = T.let(T.unsafe(nil), Hash)

# source://hansi//lib/hansi/mode_detector.rb#24
Hansi::ModeDetector::TRUE_COLOR_COMMANDS = T.let(T.unsafe(nil), Array)

# source://hansi//lib/hansi/palettes.rb#2
Hansi::PALETTES = T.let(T.unsafe(nil), Hash)

# source://hansi//lib/hansi/sexp_renderer.rb#4
class Hansi::SexpRenderer
  # source://hansi//lib/hansi/sexp_renderer.rb#9
  def initialize(theme: T.unsafe(nil), mode: T.unsafe(nil), join: T.unsafe(nil)); end

  # source://hansi//lib/hansi/sexp_renderer.rb#15
  def render(input, codes: T.unsafe(nil)); end

  class << self
    # source://hansi//lib/hansi/sexp_renderer.rb#5
    def render(*args, **options); end
  end
end

# source://hansi//lib/hansi/special.rb#2
class Hansi::Special < ::Hansi::AnsiCode
  # source://hansi//lib/hansi/special.rb#3
  def initialize(ansi, css = T.unsafe(nil)); end

  # source://hansi//lib/hansi/special.rb#21
  def inspect; end

  # source://hansi//lib/hansi/special.rb#16
  def to_ansi(mode: T.unsafe(nil), **options); end

  # source://hansi//lib/hansi/special.rb#12
  def to_css_rule; end
end

# source://hansi//lib/hansi/string_renderer.rb#4
class Hansi::StringRenderer
  # source://hansi//lib/hansi/string_renderer.rb#21
  def initialize(markup = T.unsafe(nil), theme: T.unsafe(nil), escape: T.unsafe(nil), tags: T.unsafe(nil), mode: T.unsafe(nil)); end

  # source://hansi//lib/hansi/string_renderer.rb#88
  def ansi_for(input); end

  # source://hansi//lib/hansi/string_renderer.rb#68
  def color_codes(stack); end

  # source://hansi//lib/hansi/string_renderer.rb#73
  def describe(element); end

  # source://hansi//lib/hansi/string_renderer.rb#98
  def escape(string); end

  # source://hansi//lib/hansi/string_renderer.rb#34
  def render(input, *values); end

  # source://hansi//lib/hansi/string_renderer.rb#81
  def unexpected(element, expected); end

  class << self
    # source://hansi//lib/hansi/string_renderer.rb#7
    def render(*args, **options); end
  end
end

# source://hansi//lib/hansi.rb#2
Hansi::TRUE_COLOR = T.let(T.unsafe(nil), Integer)

# source://hansi//lib/hansi/theme.rb#2
class Hansi::Theme
  # source://hansi//lib/hansi/theme.rb#18
  def initialize(*inherit, **rules); end

  # source://hansi//lib/hansi/theme.rb#23
  def ==(other); end

  # source://hansi//lib/hansi/theme.rb#35
  def [](key); end

  # source://hansi//lib/hansi/theme.rb#27
  def eql?(other); end

  # source://hansi//lib/hansi/theme.rb#31
  def hash; end

  # source://hansi//lib/hansi/theme.rb#62
  def inspect; end

  # source://hansi//lib/hansi/theme.rb#42
  def merge(other); end

  # source://hansi//lib/hansi/theme.rb#17
  def rules; end

  # source://hansi//lib/hansi/theme.rb#58
  def theme_name; end

  # source://hansi//lib/hansi/theme.rb#52
  def to_css(&block); end

  # source://hansi//lib/hansi/theme.rb#47
  def to_h; end

  class << self
    # source://hansi//lib/hansi/theme.rb#3
    def [](key); end

    # source://hansi//lib/hansi/theme.rb#13
    def []=(key, value); end
  end
end

# source://hansi//lib/hansi/themes.rb#2
Hansi::Themes = T.let(T.unsafe(nil), Hash)
