# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `money` gem.
# Please instead update this file by running `bin/tapioca gem money`.


# source://money//lib/money/currency/loader.rb#1
class Money
  include ::Comparable
  include ::Money::Arithmetic
  extend ::Money::Constructors

  # source://money//lib/money/money.rb#341
  def initialize(obj, currency = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://money//lib/money/money.rb#595
  def allocate(parts); end

  # source://money//lib/money/money.rb#386
  def amount; end

  # source://money//lib/money/money.rb#561
  def as_ca_dollar; end

  # source://money//lib/money/money.rb#573
  def as_euro; end

  # source://money//lib/money/money.rb#549
  def as_us_dollar; end

  # source://money//lib/money/money.rb#88
  def bank; end

  # source://money//lib/money/money.rb#33
  def cents; end

  # source://money//lib/money/money.rb#88
  def currency; end

  # source://money//lib/money/money.rb#396
  def currency_as_string; end

  # source://money//lib/money/money.rb#409
  def currency_as_string=(val); end

  # source://money//lib/money/money.rb#644
  def decimal_mark; end

  # source://money//lib/money/money.rb#372
  def dollars; end

  # source://money//lib/money/money.rb#649
  def dup_with(options = T.unsafe(nil)); end

  # source://money//lib/money/money.rb#532
  def exchange_to(other_currency, &rounding_method); end

  # source://money//lib/money/money.rb#627
  def format(*rules); end

  # source://money//lib/money/money.rb#53
  def fractional; end

  # source://money//lib/money/money.rb#422
  def hash; end

  # source://money//lib/money/money.rb#439
  def inspect; end

  # source://money//lib/money/money.rb#616
  def round(rounding_mode = T.unsafe(nil), rounding_precision = T.unsafe(nil)); end

  # source://money//lib/money/money.rb#70
  def round_to_nearest_cash_value; end

  # source://money//lib/money/money.rb#595
  def split(parts); end

  # source://money//lib/money/money.rb#432
  def symbol; end

  # source://money//lib/money/money.rb#635
  def thousands_separator; end

  # source://money//lib/money/money.rb#462
  def to_d; end

  # source://money//lib/money/money.rb#485
  def to_f; end

  # source://money//lib/money/money.rb#472
  def to_i; end

  # source://money//lib/money/money.rb#507
  def to_money(given_currency = T.unsafe(nil)); end

  # source://money//lib/money/money.rb#449
  def to_s; end

  # source://money//lib/money/money.rb#495
  def with_currency(new_currency); end

  private

  # source://money//lib/money/money.rb#659
  def as_d(num); end

  # source://money//lib/money/money.rb#675
  def locale_backend; end

  # source://money//lib/money/money.rb#667
  def return_value(value); end

  class << self
    # source://money//lib/money/money.rb#282
    def add_rate(from_currency, to_currency, rate); end

    # source://money//lib/money/money.rb#132
    def conversion_precision; end

    # source://money//lib/money/money.rb#132
    def conversion_precision=(_arg0); end

    # source://money//lib/money/money.rb#171
    def default_bank; end

    # source://money//lib/money/money.rb#134
    def default_bank=(_arg0); end

    # source://money//lib/money/money.rb#152
    def default_currency; end

    # source://money//lib/money/money.rb#166
    def default_currency=(currency); end

    # source://money//lib/money/money.rb#132
    def default_formatting_rules; end

    # source://money//lib/money/money.rb#132
    def default_formatting_rules=(_arg0); end

    # source://money//lib/money/money.rb#132
    def default_infinite_precision; end

    # source://money//lib/money/money.rb#132
    def default_infinite_precision=(_arg0); end

    # source://money//lib/money/money.rb#288
    def disallow_currency_conversion!; end

    # source://money//lib/money/money.rb#307
    def from_amount(amount, currency = T.unsafe(nil), options = T.unsafe(nil)); end

    def from_cents(*_arg0); end

    # source://money//lib/money/money.rb#307
    def from_dollars(amount, currency = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://money//lib/money/money.rb#136
    def infinite_precision; end

    # source://money//lib/money/money.rb#141
    def infinite_precision=(value); end

    # source://money//lib/money/money.rb#224
    def inherited(base); end

    # source://money//lib/money/money.rb#133
    def locale_backend; end

    # source://money//lib/money/money.rb#179
    def locale_backend=(value); end

    # source://money//lib/money/money.rb#235
    def rounding_mode(mode = T.unsafe(nil)); end

    # source://money//lib/money/money.rb#184
    def rounding_mode=(new_rounding_mode); end

    # source://money//lib/money/money.rb#199
    def setup_defaults; end

    # source://money//lib/money/money.rb#133
    def use_i18n; end

    # source://money//lib/money/money.rb#189
    def use_i18n=(value); end

    # source://money//lib/money/money.rb#265
    def with_rounding_mode(mode); end
  end
end

# source://money//lib/money/money/allocation.rb#4
class Money::Allocation
  class << self
    # source://money//lib/money/money/allocation.rb#58
    def convert_to_big_decimal(number); end

    # source://money//lib/money/money/allocation.rb#16
    def generate(amount, parts, whole_amounts = T.unsafe(nil)); end
  end
end

# source://money//lib/money/money/arithmetic.rb#2
module Money::Arithmetic
  # source://money//lib/money/money/arithmetic.rb#264
  def %(val); end

  # source://money//lib/money/money/arithmetic.rb#167
  def *(value); end

  # source://money//lib/money/money/arithmetic.rb#135
  def +(other); end

  # source://money//lib/money/money/arithmetic.rb#135
  def -(other); end

  # source://money//lib/money/money/arithmetic.rb#18
  def -@; end

  # source://money//lib/money/money/arithmetic.rb#191
  def /(value); end

  # source://money//lib/money/money/arithmetic.rb#55
  def <=>(other); end

  # source://money//lib/money/money/arithmetic.rb#73
  def ==(other); end

  # source://money//lib/money/money/arithmetic.rb#294
  def abs; end

  # source://money//lib/money/money/arithmetic.rb#326
  def coerce(other); end

  # source://money//lib/money/money/arithmetic.rb#209
  def div(value); end

  # source://money//lib/money/money/arithmetic.rb#223
  def divmod(val); end

  # source://money//lib/money/money/arithmetic.rb#37
  def eql?(other_money); end

  # source://money//lib/money/money/arithmetic.rb#253
  def modulo(val); end

  # source://money//lib/money/money/arithmetic.rb#102
  def negative?; end

  # source://money//lib/money/money/arithmetic.rb#317
  def nonzero?; end

  # source://money//lib/money/money/arithmetic.rb#89
  def positive?; end

  # source://money//lib/money/money/arithmetic.rb#276
  def remainder(val); end

  # source://money//lib/money/money/arithmetic.rb#305
  def zero?; end

  private

  # source://money//lib/money/money/arithmetic.rb#231
  def divmod_money(val); end

  # source://money//lib/money/money/arithmetic.rb#238
  def divmod_other(val); end
end

# source://money//lib/money/money/arithmetic.rb#5
class Money::Arithmetic::CoercedNumeric < ::Struct
  def value; end
  def value=(_); end

  # source://money//lib/money/money/arithmetic.rb#7
  def zero?; end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://money//lib/money/bank/base.rb#4
module Money::Bank; end

# source://money//lib/money/bank/base.rb#40
class Money::Bank::Base
  # source://money//lib/money/bank/base.rb#70
  def initialize(&block); end

  # source://money//lib/money/bank/base.rb#103
  def exchange_with(from, to_currency, &block); end

  # source://money//lib/money/bank/base.rb#52
  def rounding_method; end

  # source://money//lib/money/bank/base.rb#123
  def same_currency?(currency1, currency2); end

  # source://money//lib/money/bank/base.rb#82
  def setup; end

  class << self
    # source://money//lib/money/bank/base.rb#45
    def instance; end
  end
end

# source://money//lib/money/bank/single_currency.rb#6
class Money::Bank::DifferentCurrencyError < ::Money::Bank::Error; end

# source://money//lib/money/bank/base.rb#8
class Money::Bank::Error < ::StandardError; end

# source://money//lib/money/bank/single_currency.rb#15
class Money::Bank::SingleCurrency < ::Money::Bank::Base
  # source://money//lib/money/bank/single_currency.rb#19
  def exchange_with(from, to_currency, &block); end
end

# source://money//lib/money/bank/base.rb#13
class Money::Bank::UnknownRate < ::Money::Bank::Error; end

# source://money//lib/money/bank/variable_exchange.rb#9
class Money::Bank::UnknownRateFormat < ::StandardError; end

# source://money//lib/money/bank/variable_exchange.rb#43
class Money::Bank::VariableExchange < ::Money::Bank::Base
  # source://money//lib/money/bank/variable_exchange.rb#59
  def initialize(st = T.unsafe(nil), &block); end

  # source://money//lib/money/bank/variable_exchange.rb#158
  def add_rate(from, to, rate); end

  # source://money//lib/money/bank/variable_exchange.rb#127
  def calculate_fractional(from, to_currency); end

  # source://money//lib/money/bank/variable_exchange.rb#134
  def exchange(fractional, rate, &block); end

  # source://money//lib/money/bank/variable_exchange.rb#109
  def exchange_with(from, to_currency, &block); end

  # source://money//lib/money/bank/variable_exchange.rb#221
  def export_rates(format, file = T.unsafe(nil), opts = T.unsafe(nil)); end

  # source://money//lib/money/bank/variable_exchange.rb#198
  def get_rate(from, to, opts = T.unsafe(nil)); end

  # source://money//lib/money/bank/variable_exchange.rb#261
  def import_rates(format, s, opts = T.unsafe(nil)); end

  # source://money//lib/money/bank/variable_exchange.rb#68
  def marshal_dump; end

  # source://money//lib/money/bank/variable_exchange.rb#72
  def marshal_load(arr); end

  # source://money//lib/money/bank/variable_exchange.rb#45
  def mutex; end

  # source://money//lib/money/bank/variable_exchange.rb#236
  def rates; end

  # source://money//lib/money/bank/variable_exchange.rb#177
  def set_rate(from, to, rate, opts = T.unsafe(nil)); end

  # source://money//lib/money/bank/variable_exchange.rb#64
  def store; end
end

# source://money//lib/money/bank/variable_exchange.rb#50
Money::Bank::VariableExchange::FORMAT_SERIALIZERS = T.let(T.unsafe(nil), Hash)

# source://money//lib/money/bank/variable_exchange.rb#48
Money::Bank::VariableExchange::RATE_FORMATS = T.let(T.unsafe(nil), Array)

# source://money//lib/money/bank/variable_exchange.rb#49
Money::Bank::VariableExchange::SERIALIZER_SEPARATOR = T.let(T.unsafe(nil), String)

# source://money//lib/money/money/constructors.rb#2
module Money::Constructors
  # source://money//lib/money/money/constructors.rb#29
  def ca_dollar(cents); end

  # source://money//lib/money/money/constructors.rb#29
  def cad(cents); end

  # source://money//lib/money/money/constructors.rb#12
  def empty(currency = T.unsafe(nil)); end

  # source://money//lib/money/money/constructors.rb#62
  def eur(cents); end

  # source://money//lib/money/money/constructors.rb#62
  def euro(cents); end

  # source://money//lib/money/money/constructors.rb#78
  def gbp(pence); end

  # source://money//lib/money/money/constructors.rb#78
  def pound_sterling(pence); end

  # source://money//lib/money/money/constructors.rb#46
  def us_dollar(cents); end

  # source://money//lib/money/money/constructors.rb#46
  def usd(cents); end

  # source://money//lib/money/money/constructors.rb#12
  def zero(currency = T.unsafe(nil)); end
end

# source://money//lib/money/currency/loader.rb#2
class Money::Currency
  include ::Comparable
  extend ::Enumerable
  extend ::Money::Currency::Heuristics

  # source://money//lib/money/currency.rb#275
  def initialize(id); end

  # source://money//lib/money/currency.rb#293
  def <=>(other_currency); end

  # source://money//lib/money/currency.rb#316
  def ==(other_currency); end

  # source://money//lib/money/currency.rb#400
  def code; end

  # source://money//lib/money/currency.rb#258
  def decimal_mark; end

  # source://money//lib/money/currency.rb#425
  def decimal_places; end

  # source://money//lib/money/currency.rb#258
  def delimiter; end

  # source://money//lib/money/currency.rb#258
  def disambiguate_symbol; end

  def eql?(_arg0); end

  # source://money//lib/money/currency.rb#425
  def exponent; end

  # source://money//lib/money/currency.rb#258
  def format; end

  # source://money//lib/money/currency.rb#337
  def hash; end

  # source://money//lib/money/currency.rb#258
  def html_entity; end

  # source://money//lib/money/currency.rb#258
  def id; end

  # source://money//lib/money/currency.rb#347
  def inspect; end

  # source://money//lib/money/currency.rb#415
  def iso?; end

  # source://money//lib/money/currency.rb#258
  def iso_code; end

  # source://money//lib/money/currency.rb#258
  def iso_numeric; end

  # source://money//lib/money/currency.rb#258
  def name; end

  # source://money//lib/money/currency.rb#258
  def priority; end

  # source://money//lib/money/currency.rb#258
  def separator; end

  # source://money//lib/money/currency.rb#258
  def smallest_denomination; end

  # source://money//lib/money/currency.rb#258
  def subunit; end

  # source://money//lib/money/currency.rb#258
  def subunit_to_unit; end

  # source://money//lib/money/currency.rb#258
  def symbol; end

  # source://money//lib/money/currency.rb#258
  def symbol_first; end

  # source://money//lib/money/currency.rb#404
  def symbol_first?; end

  # source://money//lib/money/currency.rb#258
  def thousands_separator; end

  # source://money//lib/money/currency.rb#393
  def to_currency; end

  # source://money//lib/money/currency.rb#362
  def to_s; end

  # source://money//lib/money/currency.rb#374
  def to_str; end

  # source://money//lib/money/currency.rb#386
  def to_sym; end

  private

  # source://money//lib/money/currency.rb#320
  def compare_ids(other_currency); end

  # source://money//lib/money/currency.rb#432
  def initialize_data!; end

  class << self
    # source://money//lib/money/currency.rb#46
    def _instances; end

    # source://money//lib/money/currency.rb#133
    def all; end

    # source://money//lib/money/currency.rb#205
    def each; end

    # source://money//lib/money/currency.rb#61
    def find(id); end

    # source://money//lib/money/currency.rb#80
    def find_by_iso_numeric(num); end

    # source://money//lib/money/currency.rb#181
    def inherit(parent_iso_code, curr); end

    # source://money//lib/money/currency.rb#37
    def new(id); end

    # source://money//lib/money/currency.rb#170
    def register(curr); end

    # source://money//lib/money/currency.rb#209
    def reset!; end

    # source://money//lib/money/currency.rb#149
    def stringified_keys; end

    # source://money//lib/money/currency.rb#123
    def table; end

    # source://money//lib/money/currency.rb#194
    def unregister(curr); end

    # source://money//lib/money/currency.rb#102
    def wrap(object); end

    private

    # source://money//lib/money/currency.rb#216
    def stringify_keys; end
  end
end

# source://money//lib/money/currency/heuristics.rb#5
module Money::Currency::Heuristics
  # source://money//lib/money/currency/heuristics.rb#6
  def analyze(str); end
end

# source://money//lib/money/currency/loader.rb#3
module Money::Currency::Loader
  class << self
    # source://money//lib/money/currency/loader.rb#10
    def load_currencies; end

    private

    # source://money//lib/money/currency/loader.rb#18
    def parse_currency_file(filename); end
  end
end

# source://money//lib/money/currency/loader.rb#4
Money::Currency::Loader::DATA_PATH = T.let(T.unsafe(nil), String)

# source://money//lib/money/currency.rb#24
class Money::Currency::MissingAttributeError < ::StandardError
  # source://money//lib/money/currency.rb#25
  def initialize(method, currency, attribute); end
end

# source://money//lib/money/currency.rb#34
class Money::Currency::UnknownCurrency < ::ArgumentError; end

# source://money//lib/money/money/formatter.rb#5
class Money::Formatter
  # source://money//lib/money/money/formatter.rb#233
  def initialize(money, *rules); end

  # source://money//lib/money/money/formatter.rb#254
  def decimal_mark; end

  # source://money//lib/money/money/formatter.rb#246
  def delimiter; end

  # source://money//lib/money/money/formatter.rb#254
  def separator; end

  # source://money//lib/money/money/formatter.rb#246
  def thousands_separator; end

  # source://money//lib/money/money/formatter.rb#239
  def to_s; end

  private

  # source://money//lib/money/money/formatter.rb#317
  def append_currency_symbol(formatted_number); end

  # source://money//lib/money/money/formatter.rb#288
  def append_sign(formatted_number); end

  # source://money//lib/money/money/formatter.rb#263
  def currency; end

  # source://money//lib/money/money/formatter.rb#351
  def extract_whole_and_decimal_parts; end

  # source://money//lib/money/money/formatter.rb#364
  def format_decimal_part(value); end

  # source://money//lib/money/money/formatter.rb#265
  def format_number; end

  # source://money//lib/money/money/formatter.rb#344
  def format_whole_part(value); end

  # source://money//lib/money/money/formatter.rb#340
  def free_text; end

  # source://money//lib/money/money/formatter.rb#336
  def html_wrap(string, class_name); end

  # source://money//lib/money/money/formatter.rb#378
  def lookup(key); end

  # source://money//lib/money/money/formatter.rb#384
  def lookup_default(key); end

  # source://money//lib/money/money/formatter.rb#263
  def money; end

  # source://money//lib/money/money/formatter.rb#263
  def rules; end

  # source://money//lib/money/money/formatter.rb#332
  def show_free_text?; end

  # source://money//lib/money/money/formatter.rb#388
  def symbol_value_from(rules); end
end

# source://money//lib/money/money/formatter.rb#6
Money::Formatter::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://money//lib/money/money/formatting_rules.rb#4
class Money::FormattingRules
  # source://money//lib/money/money/formatting_rules.rb#5
  def initialize(currency, *raw_rules); end

  # source://money//lib/money/money/formatting_rules.rb#20
  def [](key); end

  # source://money//lib/money/money/formatting_rules.rb#24
  def has_key?(key); end

  private

  # source://money//lib/money/money/formatting_rules.rb#30
  def currency; end

  # source://money//lib/money/money/formatting_rules.rb#61
  def default_formatting_rules; end

  # source://money//lib/money/money/formatting_rules.rb#94
  def delimiter_pattern_rule(rules); end

  # source://money//lib/money/money/formatting_rules.rb#82
  def determine_format_from_formatting_rules(rules); end

  # source://money//lib/money/money/formatting_rules.rb#74
  def localize_formatting_rules(rules); end

  # source://money//lib/money/money/formatting_rules.rb#37
  def normalize_formatting_rules(rules); end

  # source://money//lib/money/money/formatting_rules.rb#103
  def symbol_position_from(rules); end

  # source://money//lib/money/money/formatting_rules.rb#65
  def translate_formatting_rules(rules); end

  # source://money//lib/money/money/formatting_rules.rb#117
  def warn_about_deprecated_rules(rules); end
end

# source://money//lib/money/locale_backend/errors.rb#2
module Money::LocaleBackend
  class << self
    # source://money//lib/money/money/locale_backend.rb#16
    def find(name); end
  end
end

# source://money//lib/money/money/locale_backend.rb#10
Money::LocaleBackend::BACKENDS = T.let(T.unsafe(nil), Hash)

# source://money//lib/money/locale_backend/base.rb#5
class Money::LocaleBackend::Base; end

# source://money//lib/money/locale_backend/currency.rb#5
class Money::LocaleBackend::Currency < ::Money::LocaleBackend::Base
  # source://money//lib/money/locale_backend/currency.rb#6
  def lookup(key, currency); end
end

# source://money//lib/money/locale_backend/i18n.rb#5
class Money::LocaleBackend::I18n < ::Money::LocaleBackend::Base
  # source://money//lib/money/locale_backend/i18n.rb#12
  def initialize; end

  # source://money//lib/money/locale_backend/i18n.rb#16
  def lookup(key, _); end
end

# source://money//lib/money/locale_backend/i18n.rb#6
Money::LocaleBackend::I18n::KEY_MAP = T.let(T.unsafe(nil), Hash)

# source://money//lib/money/locale_backend/legacy.rb#6
class Money::LocaleBackend::Legacy < ::Money::LocaleBackend::Base
  # source://money//lib/money/locale_backend/legacy.rb#7
  def initialize; end

  # source://money//lib/money/locale_backend/legacy.rb#11
  def lookup(key, currency); end

  private

  # source://money//lib/money/locale_backend/legacy.rb#23
  def i18n_backend; end
end

# source://money//lib/money/locale_backend/errors.rb#3
class Money::LocaleBackend::NotSupported < ::StandardError; end

# source://money//lib/money/locale_backend/errors.rb#4
class Money::LocaleBackend::Unknown < ::ArgumentError; end

# source://money//lib/money/rates_store/memory.rb#4
module Money::RatesStore; end

# source://money//lib/money/rates_store/memory.rb#15
class Money::RatesStore::Memory
  # source://money//lib/money/rates_store/memory.rb#23
  def initialize(opts = T.unsafe(nil), rates = T.unsafe(nil)); end

  # source://money//lib/money/rates_store/memory.rb#41
  def add_rate(currency_iso_from, currency_iso_to, rate); end

  # source://money//lib/money/rates_store/memory.rb#91
  def each_rate(&block); end

  # source://money//lib/money/rates_store/memory.rb#60
  def get_rate(currency_iso_from, currency_iso_to); end

  # source://money//lib/money/rates_store/memory.rb#66
  def marshal_dump; end

  # source://money//lib/money/rates_store/memory.rb#73
  def transaction(&block); end

  private

  # source://money//lib/money/rates_store/memory.rb#104
  def guard; end

  # source://money//lib/money/rates_store/memory.rb#104
  def options; end

  # source://money//lib/money/rates_store/memory.rb#115
  def rate_key_for(currency_iso_from, currency_iso_to); end

  # source://money//lib/money/rates_store/memory.rb#104
  def rates; end
end

# source://money//lib/money/rates_store/memory.rb#16
Money::RatesStore::Memory::INDEX_KEY_SEPARATOR = T.let(T.unsafe(nil), String)

# source://money//lib/money/money.rb#25
class Money::UndefinedSmallestDenomination < ::StandardError; end
