# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mustermann-contrib` gem.
# Please instead update this file by running `bin/tapioca gem mustermann-contrib`.


# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#4
module Mustermann
  class << self
    # source://mustermann/3.0.3/lib/mustermann.rb#89
    def [](name); end

    # source://mustermann/3.0.3/lib/mustermann.rb#120
    def extend_object(object); end

    # source://mustermann/3.0.3/lib/mustermann.rb#62
    def new(*input, type: T.unsafe(nil), operator: T.unsafe(nil), **options); end

    # source://mustermann/3.0.3/lib/mustermann.rb#115
    def normalized_type(type); end

    # source://mustermann/3.0.3/lib/mustermann.rb#110
    def register(name, type); end

    # source://mustermann/3.0.3/lib/mustermann.rb#101
    def try_require(path); end
  end
end

class Mustermann::Composite < ::Mustermann::Pattern
  # source://mustermann/3.0.3/lib/mustermann/composite.rb#27
  def initialize(patterns, operator: T.unsafe(nil), **options); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#33
  def ==(pattern); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#48
  def ===(string); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#38
  def eql?(pattern); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#69
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#43
  def hash; end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#48
  def inspect; end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#58
  def match(string); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#8
  def operator; end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#53
  def params(string); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#8
  def patterns; end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#63
  def respond_to_special?(method); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#92
  def simple_inspect; end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#43
  def to_s; end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#76
  def to_templates; end

  private

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#105
  def patterns_from(pattern, **options); end

  # source://mustermann/3.0.3/lib/mustermann/composite.rb#98
  def with_matching(string, method); end

  class << self
    # source://mustermann/3.0.3/lib/mustermann/composite.rb#18
    def new(*patterns, **options); end

    # source://mustermann/3.0.3/lib/mustermann/composite.rb#12
    def supported?(option, type: T.unsafe(nil), **options); end
  end
end

class Mustermann::Pattern
  include ::Mustermann::Visualizer::PatternExtension

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#75
  def initialize(string, uri_decode: T.unsafe(nil), **options); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#315
  def &(other); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#336
  def +(other); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#119
  def ==(other); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#106
  def ===(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#98
  def =~(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#315
  def ^(other); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#391
  def always_array?(key); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#126
  def eql?(other); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#240
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#112
  def hash; end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#48
  def inspect; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#91
  def match(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#192
  def named_captures; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#198
  def names; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#67
  def options; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#204
  def params(string = T.unsafe(nil), captures: T.unsafe(nil), offset: T.unsafe(nil)); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#153
  def peek(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#168
  def peek_match(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#185
  def peek_params(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#139
  def peek_size(string); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#353
  def respond_to?(method, *args); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#371
  def simple_inspect; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#346
  def to_proc; end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#43
  def to_s; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#279
  def to_templates; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#63
  def uri_decode; end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#315
  def |(other); end

  private

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#377
  def map_param(key, value); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#361
  def respond_to_special?(method); end

  # source://mustermann/3.0.3/lib/mustermann/pattern.rb#382
  def unescape(string, decode = T.unsafe(nil)); end

  class << self
    # source://mustermann/3.0.3/lib/mustermann/pattern.rb#50
    def new(string, ignore_unknown_options: T.unsafe(nil), **options); end

    # source://mustermann/3.0.3/lib/mustermann/pattern.rb#34
    def register(*names); end

    # source://mustermann/3.0.3/lib/mustermann/pattern.rb#40
    def supported?(option, **options); end

    # source://mustermann/3.0.3/lib/mustermann/pattern.rb#24
    def supported_options(*list); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#5
module Mustermann::Visualizer
  extend ::Mustermann::Visualizer

  # source://mustermann-contrib//lib/mustermann/visualizer.rb#21
  def highlight(pattern, **options); end

  # source://mustermann-contrib//lib/mustermann/visualizer.rb#34
  def tree(pattern, **options); end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#13
class Mustermann::Visualizer::Highlight
  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#51
  def initialize(pattern, type: T.unsafe(nil), inspect: T.unsafe(nil), **theme); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#15
  def pattern; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#132
  def render(renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#126
  def render_with(renderer, **options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#121
  def stylesheet(**options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#15
  def theme; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#80
  def to_ansi(**options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#67
  def to_hansi_template(**options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#93
  def to_html(**options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#111
  def to_pattern; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#116
  def to_s; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#106
  def to_sexp(**options); end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#30
Mustermann::Visualizer::Highlight::BASE_THEME = T.let(T.unsafe(nil), Hansi::Theme)

# source://mustermann-contrib//lib/mustermann/visualizer/highlight.rb#18
Mustermann::Visualizer::Highlight::DEFAULT_THEME = T.let(T.unsafe(nil), Hansi::Theme)

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#7
module Mustermann::Visualizer::Highlighter
  extend ::Mustermann::Visualizer::Highlighter

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter.rb#33
  def create(&block); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter.rb#16
  def highlight(pattern, renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter.rb#22
  def highlighter_for(pattern); end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#10
class Mustermann::Visualizer::Highlighter::AST
  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#64
  def initialize(pattern, renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#71
  def highlight; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#85
  def inject_literals(index); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#97
  def literal(start, stop); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#78
  def render(index); end

  class << self
    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#59
    def highlight(pattern, renderer); end

    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#54
    def highlight?(pattern); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#11
class Mustermann::Visualizer::Highlighter::AST::Index < ::Struct
  def payload; end
  def payload=(_); end
  def start; end
  def start=(_); end
  def stop; end
  def stop=(_); end
  def type; end
  def type=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ast.rb#12
Mustermann::Visualizer::Highlighter::AST::Indexer = T.let(T.unsafe(nil), T.untyped)

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#12
class Mustermann::Visualizer::Highlighter::AdHoc
  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#34
  def initialize(pattern, renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#54
  def apply(scanner); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#86
  def element(type, content = T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#69
  def escaped(content = T.unsafe(nil), char); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#43
  def highlight(stop = T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#74
  def nested(type, opening, closing, *separators); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#33
  def output; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#33
  def pattern; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#62
  def read_char(scanner); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#33
  def renderer; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#33
  def rules; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#33
  def scanner; end

  class << self
    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#14
    def highlight(pattern, renderer); end

    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#24
    def on(regexp, type = T.unsafe(nil), &callback); end

    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/ad_hoc.rb#19
    def rules; end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/composite.rb#7
module Mustermann::Visualizer::Highlighter::Composite
  extend ::Mustermann::Visualizer::Highlighter::Composite

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/composite.rb#16
  def highlight(pattern, renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/composite.rb#11
  def highlight?(pattern); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/composite.rb#23
  def highlight_nested(pattern, renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/composite.rb#35
  def nested_highlight(pattern, renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/composite.rb#40
  def quote(renderer, string, type = T.unsafe(nil)); end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/dummy.rb#8
module Mustermann::Visualizer::Highlighter::Dummy
  class << self
    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/dummy.rb#10
    def highlight(pattern, renderer); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#10
class Mustermann::Visualizer::Highlighter::Regular
  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#29
  def initialize(renderer); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#60
  def char_class; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#96
  def element(type, content = T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#84
  def escaped(char); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#35
  def highlight(pattern); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#26
  def output; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#70
  def potential_capture; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#26
  def renderer; end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#43
  def scan(stop = T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#26
  def scanner; end

  class << self
    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#21
    def highlight(pattern, renderer); end

    # source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#16
    def highlight?(pattern); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/highlighter/regular.rb#12
Mustermann::Visualizer::Highlighter::Regular::SPECIAL_ESCAPE = T.let(T.unsafe(nil), Array)

# source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#5
module Mustermann::Visualizer::PatternExtension
  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#53
  def color_inspect(base_color = T.unsafe(nil), **theme); end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#48
  def inspect; end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#60
  def pretty_print(q); end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#13
  def to_ansi(inspect: T.unsafe(nil), **theme); end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#21
  def to_html(inspect: T.unsafe(nil), tag: T.unsafe(nil), class_prefix: T.unsafe(nil), css: T.unsafe(nil), **theme); end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#43
  def to_s; end

  # source://mustermann-contrib//lib/mustermann/visualizer/pattern_extension.rb#29
  def to_tree; end
end

# source://mustermann-contrib//lib/mustermann/visualizer/renderer/ansi.rb#5
module Mustermann::Visualizer::Renderer; end

# source://mustermann-contrib//lib/mustermann/visualizer/renderer/ansi.rb#8
class Mustermann::Visualizer::Renderer::ANSI
  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/ansi.rb#10
  def initialize(target, mode: T.unsafe(nil), **options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/ansi.rb#17
  def render; end
end

# source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#7
class Mustermann::Visualizer::Renderer::Generic
  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#9
  def initialize(target, inspect: T.unsafe(nil), add_qoutes: T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#26
  def escape(value, inspect_value = T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#31
  def escape_string(string); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#41
  def post(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#36
  def pre(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#22
  def preamble; end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/generic.rb#16
  def render; end
end

# source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#11
class Mustermann::Visualizer::Renderer::HTML < ::Mustermann::Visualizer::Renderer::Generic
  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#13
  def initialize(target, tag: T.unsafe(nil), class_prefix: T.unsafe(nil), css: T.unsafe(nil), **options); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#30
  def escape_string(string); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#45
  def post(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#35
  def pre(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#20
  def preamble; end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/html.rb#25
  def stylesheet; end
end

# source://mustermann-contrib//lib/mustermann/visualizer/renderer/hansi_template.rb#11
class Mustermann::Visualizer::Renderer::HansiTemplate < ::Mustermann::Visualizer::Renderer::Generic
  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/hansi_template.rb#13
  def initialize(*_arg0, **_arg1); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/hansi_template.rb#19
  def escape_string(string); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/hansi_template.rb#29
  def post(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/hansi_template.rb#24
  def pre(type); end
end

# source://mustermann-contrib//lib/mustermann/visualizer/renderer/sexp.rb#10
class Mustermann::Visualizer::Renderer::Sexp < ::Mustermann::Visualizer::Renderer::Generic
  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/sexp.rb#24
  def escape_string(input); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/sexp.rb#32
  def post(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/sexp.rb#19
  def pre(type); end

  # source://mustermann-contrib//lib/mustermann/visualizer/renderer/sexp.rb#12
  def render; end
end

# source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#7
class Mustermann::Visualizer::Tree
  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#12
  def initialize(line, *children, prefix_color: T.unsafe(nil), before: T.unsafe(nil), after: T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#9
  def after; end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#9
  def before; end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#9
  def children; end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#9
  def line; end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#22
  def line_widths(offset = T.unsafe(nil)); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#9
  def prefix_color; end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#36
  def render(first_prefix, prefix, width); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#30
  def to_s; end

  private

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#50
  def deansi(string); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#45
  def length(string); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree.rb#55
  def ljust(string, width); end
end

# source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#10
class Mustermann::Visualizer::TreeRenderer < ::Mustermann::AST::Translator
  # source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#38
  def initialize(string); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#62
  def children_for(list); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#35
  def string; end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#44
  def sub(*args); end

  # source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#50
  def tree(node, *children, **typed_children); end

  class << self
    # source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#22
    def render(pattern, **options); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#14
class Mustermann::Visualizer::TreeRenderer::FakeNode < ::Struct
  def length; end
  def length=(_); end
  def start; end
  def start=(_); end
  def stop; end
  def stop=(_); end
  def type; end
  def type=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#0
class Mustermann::Visualizer::TreeRenderer::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # source://mustermann/3.0.3/lib/mustermann/ast/translator.rb#62
    def translator; end
  end
end

# source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#13
Mustermann::Visualizer::TreeRenderer::PREFIX_COLOR = T.let(T.unsafe(nil), Hansi::Color)

# source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#11
Mustermann::Visualizer::TreeRenderer::TEMPLATE = T.let(T.unsafe(nil), String)

# source://mustermann-contrib//lib/mustermann/visualizer/tree_renderer.rb#12
Mustermann::Visualizer::TreeRenderer::THEME = T.let(T.unsafe(nil), Hansi::Theme)
