# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mustermann` gem.
# Please instead update this file by running `bin/tapioca gem mustermann`.


# source://mustermann//lib/mustermann/ast/node.rb#1
module Mustermann
  class << self
    # source://mustermann//lib/mustermann.rb#89
    def [](name); end

    # source://mustermann//lib/mustermann.rb#120
    def extend_object(object); end

    # source://mustermann//lib/mustermann.rb#62
    def new(*input, type: T.unsafe(nil), operator: T.unsafe(nil), **options); end

    # source://mustermann//lib/mustermann.rb#115
    def normalized_type(type); end

    # source://mustermann//lib/mustermann.rb#110
    def register(name, type); end

    # source://mustermann//lib/mustermann.rb#101
    def try_require(path); end
  end
end

# source://mustermann//lib/mustermann/ast/node.rb#3
module Mustermann::AST; end

# source://mustermann//lib/mustermann/ast/compiler.rb#9
class Mustermann::AST::Compiler < ::Mustermann::AST::Translator
  # source://mustermann//lib/mustermann/ast/compiler.rb#151
  def compile(ast, except: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#126
  def encoded(char, uri_decode: T.unsafe(nil), space_matches_plus: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/translator.rb#70
  def error_class; end

  class << self
    # source://mustermann//lib/mustermann/ast/compiler.rb#142
    def compile(ast, **options); end
  end
end

# source://mustermann//lib/mustermann/ast/compiler.rb#38
class Mustermann::AST::Compiler::Capture < ::Mustermann::AST::Compiler::NodeTranslator
  # source://mustermann//lib/mustermann/ast/compiler.rb#49
  def pattern(capture: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#42
  def translate(**options); end

  private

  # source://mustermann//lib/mustermann/ast/compiler.rb#68
  def default(**options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#64
  def from_array(array, **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#63
  def from_hash(hash, **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#67
  def from_nil(**options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#66
  def from_string(string, **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#65
  def from_symbol(symbol, **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#61
  def qualified(string, greedy: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#62
  def with_lookahead(string, lookahead: T.unsafe(nil), **options); end
end

# source://mustermann//lib/mustermann/ast/compiler.rb#0
class Mustermann::AST::Compiler::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # source://mustermann//lib/mustermann/ast/translator.rb#62
    def translator; end
  end
end

# source://mustermann//lib/mustermann/ast/compiler.rb#72
class Mustermann::AST::Compiler::Splat < ::Mustermann::AST::Compiler::Capture
  # source://mustermann//lib/mustermann/ast/compiler.rb#76
  def pattern(**options); end
end

# source://mustermann//lib/mustermann/ast/compiler.rb#82
class Mustermann::AST::Compiler::Variable < ::Mustermann::AST::Compiler::Capture
  # source://mustermann//lib/mustermann/ast/compiler.rb#113
  def default(allow_reserved: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#103
  def parametric(string); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#94
  def pattern(parametric: T.unsafe(nil), separator: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#108
  def qualified(string, **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#118
  def register_param(parametric: T.unsafe(nil), split_params: T.unsafe(nil), separator: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/compiler.rb#86
  def translate(**options); end
end

# source://mustermann//lib/mustermann/ast/expander.rb#12
class Mustermann::AST::Expander < ::Mustermann::AST::Translator
  # source://mustermann//lib/mustermann/ast/expander.rb#80
  def add(ast); end

  # source://mustermann//lib/mustermann/ast/expander.rb#141
  def add_to(list, result); end

  # source://mustermann//lib/mustermann/ast/translator.rb#70
  def error_class; end

  # source://mustermann//lib/mustermann/ast/expander.rb#119
  def error_for(values); end

  # source://mustermann//lib/mustermann/ast/expander.rb#126
  def escape(string, *args, **_arg2); end

  # source://mustermann//lib/mustermann/ast/expander.rb#95
  def expand(values); end

  # source://mustermann//lib/mustermann/ast/expander.rb#105
  def expandable?(values); end

  # source://mustermann//lib/mustermann/ast/expander.rb#113
  def expandable_keys(keys); end

  # source://mustermann//lib/mustermann/ast/expander.rb#61
  def for_capture(node, **options); end

  # source://mustermann//lib/mustermann/ast/expander.rb#74
  def keys; end

  # source://mustermann//lib/mustermann/ast/expander.rb#68
  def mappings; end

  # source://mustermann//lib/mustermann/ast/expander.rb#135
  def pattern(string = T.unsafe(nil), *keys, **filters); end

  # source://mustermann//lib/mustermann/ast/expander.rb#89
  def pattern_for(node, **options); end
end

# source://mustermann//lib/mustermann/ast/expander.rb#0
class Mustermann::AST::Expander::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # source://mustermann//lib/mustermann/ast/translator.rb#62
    def translator; end
  end
end

# source://mustermann//lib/mustermann/ast/node.rb#5
class Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#43
  def initialize(payload = T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/ast/node.rb#65
  def each_leaf(&block); end

  # source://mustermann//lib/mustermann/ast/node.rb#49
  def is_a?(type); end

  # source://mustermann//lib/mustermann/ast/node.rb#78
  def length; end

  # source://mustermann//lib/mustermann/ast/node.rb#84
  def min_size; end

  # source://mustermann//lib/mustermann/ast/node.rb#56
  def parse; end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def payload; end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def payload=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def start; end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def start=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def stop; end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def stop=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#90
  def type; end

  class << self
    # source://mustermann//lib/mustermann/ast/node.rb#12
    def [](name); end

    # source://mustermann//lib/mustermann/ast/node.rb#29
    def constant_name(name); end

    # source://mustermann//lib/mustermann/ast/node.rb#38
    def parse(payload = T.unsafe(nil), **options, &block); end

    # source://mustermann//lib/mustermann/ast/node.rb#22
    def type; end
  end
end

# source://mustermann//lib/mustermann/ast/node.rb#95
class Mustermann::AST::Node::Capture < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#98
  def constraint; end

  # source://mustermann//lib/mustermann/ast/node.rb#98
  def constraint=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#106
  def convert; end

  # source://mustermann//lib/mustermann/ast/node.rb#106
  def convert=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#7
  def name; end

  # source://mustermann//lib/mustermann/ast/node.rb#110
  def parse; end

  # source://mustermann//lib/mustermann/ast/node.rb#102
  def qualifier; end

  # source://mustermann//lib/mustermann/ast/node.rb#102
  def qualifier=(_arg0); end
end

# source://mustermann//lib/mustermann/ast/node.rb#120
class Mustermann::AST::Node::Char < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#123
  def min_size; end
end

# source://mustermann//lib/mustermann/ast/node.rb#136
class Mustermann::AST::Node::Composition < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#138
  def initialize(payload = T.unsafe(nil), **options); end
end

# source://mustermann//lib/mustermann/ast/node.rb#130
class Mustermann::AST::Node::Expression < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#132
  def operator; end

  # source://mustermann//lib/mustermann/ast/node.rb#132
  def operator=(_arg0); end
end

# source://mustermann//lib/mustermann/ast/node.rb#144
class Mustermann::AST::Node::Group < ::Mustermann::AST::Node::Composition; end

# source://mustermann//lib/mustermann/ast/node.rb#195
class Mustermann::AST::Node::NamedSplat < ::Mustermann::AST::Node::Splat
  # source://mustermann//lib/mustermann/ast/node.rb#7
  def name; end
end

# source://mustermann//lib/mustermann/ast/node.rb#152
class Mustermann::AST::Node::Optional < ::Mustermann::AST::Node; end

# source://mustermann//lib/mustermann/ast/node.rb#156
class Mustermann::AST::Node::Or < ::Mustermann::AST::Node; end

# source://mustermann//lib/mustermann/ast/node.rb#160
class Mustermann::AST::Node::Root < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#162
  def pattern; end

  # source://mustermann//lib/mustermann/ast/node.rb#162
  def pattern=(_arg0); end

  class << self
    # source://mustermann//lib/mustermann/ast/node.rb#168
    def parse(string, &block); end
  end
end

# source://mustermann//lib/mustermann/ast/node.rb#177
class Mustermann::AST::Node::Separator < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#180
  def min_size; end
end

# source://mustermann//lib/mustermann/ast/node.rb#186
class Mustermann::AST::Node::Splat < ::Mustermann::AST::Node::Capture
  # source://mustermann//lib/mustermann/ast/node.rb#189
  def name; end
end

# source://mustermann//lib/mustermann/ast/node.rb#148
class Mustermann::AST::Node::Union < ::Mustermann::AST::Node::Composition; end

# source://mustermann//lib/mustermann/ast/node.rb#203
class Mustermann::AST::Node::Variable < ::Mustermann::AST::Node::Capture
  # source://mustermann//lib/mustermann/ast/node.rb#205
  def explode; end

  # source://mustermann//lib/mustermann/ast/node.rb#205
  def explode=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#205
  def prefix; end

  # source://mustermann//lib/mustermann/ast/node.rb#205
  def prefix=(_arg0); end
end

# source://mustermann//lib/mustermann/ast/node.rb#209
class Mustermann::AST::Node::WithLookAhead < ::Mustermann::AST::Node
  # source://mustermann//lib/mustermann/ast/node.rb#214
  def initialize(payload, at_end, **options); end

  # source://mustermann//lib/mustermann/ast/node.rb#211
  def at_end; end

  # source://mustermann//lib/mustermann/ast/node.rb#211
  def at_end=(_arg0); end

  # source://mustermann//lib/mustermann/ast/node.rb#211
  def head; end

  # source://mustermann//lib/mustermann/ast/node.rb#211
  def head=(_arg0); end
end

# source://mustermann//lib/mustermann/ast/translator.rb#13
class Mustermann::AST::Translator
  # source://mustermann//lib/mustermann/ast/translator.rb#108
  def decorator_for(node); end

  # source://mustermann//lib/mustermann/ast/translator.rb#70
  def error_class; end

  # source://mustermann//lib/mustermann/ast/translator.rb#124
  def escape(char, parser: T.unsafe(nil), escape: T.unsafe(nil), also_escape: T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/ast/translator.rb#116
  def translate(node, *args, **_arg2, &block); end

  class << self
    # source://mustermann//lib/mustermann/ast/translator.rb#98
    def create(&block); end

    # source://mustermann//lib/mustermann/ast/translator.rb#54
    def dispatch_table; end

    # source://mustermann//lib/mustermann/ast/translator.rb#60
    def inherited(subclass); end

    # source://mustermann//lib/mustermann/ast/translator.rb#69
    def raises(error); end

    # source://mustermann//lib/mustermann/ast/translator.rb#75
    def translate(*types, &block); end
  end
end

# source://mustermann//lib/mustermann/ast/translator.rb#19
class Mustermann::AST::Translator::NodeTranslator
  # source://mustermann//lib/mustermann/ast/translator.rb#33
  def initialize(node, translator); end

  # source://delegate/0.3.0/delegate.rb#402
  def node; end

  # source://mustermann//lib/mustermann/ast/translator.rb#43
  def t(*args, **_arg1, &block); end

  # source://mustermann//lib/mustermann/ast/translator.rb#39
  def translator; end

  class << self
    # source://mustermann//lib/mustermann/ast/translator.rb#22
    def register(*types); end
  end
end

# source://mustermann//lib/mustermann/ast/translator.rb#15
Mustermann::AST::Translator::URI_PARSER = T.let(T.unsafe(nil), URI::RFC2396_Parser)

# source://mustermann//lib/mustermann/caster.rb#15
class Mustermann::Caster
  # source://mustermann//lib/mustermann/caster.rb#18
  def initialize(*types, &block); end

  # source://mustermann//lib/mustermann/caster.rb#45
  def cast(hash); end

  # source://mustermann//lib/mustermann/caster.rb#34
  def caster_for(type, &block); end

  # source://mustermann//lib/mustermann/caster.rb#25
  def register(*types, &block); end
end

# source://mustermann//lib/mustermann/caster.rb#58
class Mustermann::Caster::Any
  # source://mustermann//lib/mustermann/caster.rb#60
  def initialize(&block); end

  # source://mustermann//lib/mustermann/caster.rb#66
  def cast(key, value); end
end

# source://mustermann//lib/mustermann/caster.rb#94
class Mustermann::Caster::Key < ::Mustermann::Caster::Any
  # source://mustermann//lib/mustermann/caster.rb#97
  def initialize(type, &block); end

  # source://mustermann//lib/mustermann/caster.rb#104
  def cast(key, value); end
end

# source://mustermann//lib/mustermann/caster.rb#77
class Mustermann::Caster::Value < ::Mustermann::Caster::Any
  # source://mustermann//lib/mustermann/caster.rb#80
  def initialize(type, &block); end

  # source://mustermann//lib/mustermann/caster.rb#87
  def cast(key, value); end
end

# source://mustermann//lib/mustermann/error.rb#5
class Mustermann::CompileError < ::Mustermann::Error; end

# source://mustermann//lib/mustermann/composite.rb#7
class Mustermann::Composite < ::Mustermann::Pattern
  # source://mustermann//lib/mustermann/composite.rb#27
  def initialize(patterns, operator: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/composite.rb#33
  def ==(pattern); end

  # source://mustermann//lib/mustermann/composite.rb#48
  def ===(string); end

  # source://mustermann//lib/mustermann/composite.rb#38
  def eql?(pattern); end

  # source://mustermann//lib/mustermann/composite.rb#69
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/composite.rb#43
  def hash; end

  # source://mustermann-contrib/3.0.3/lib/mustermann/visualizer/pattern_extension.rb#48
  def inspect; end

  # source://mustermann//lib/mustermann/composite.rb#58
  def match(string); end

  # source://mustermann//lib/mustermann/composite.rb#8
  def operator; end

  # source://mustermann//lib/mustermann/composite.rb#53
  def params(string); end

  # source://mustermann//lib/mustermann/composite.rb#8
  def patterns; end

  # source://mustermann//lib/mustermann/composite.rb#63
  def respond_to_special?(method); end

  # source://mustermann//lib/mustermann/composite.rb#92
  def simple_inspect; end

  # source://mustermann-contrib/3.0.3/lib/mustermann/visualizer/pattern_extension.rb#43
  def to_s; end

  # source://mustermann//lib/mustermann/composite.rb#76
  def to_templates; end

  private

  # source://mustermann//lib/mustermann/composite.rb#105
  def patterns_from(pattern, **options); end

  # source://mustermann//lib/mustermann/composite.rb#98
  def with_matching(string, method); end

  class << self
    # source://mustermann//lib/mustermann/composite.rb#18
    def new(*patterns, **options); end

    # source://mustermann//lib/mustermann/composite.rb#12
    def supported?(option, type: T.unsafe(nil), **options); end
  end
end

# source://mustermann//lib/mustermann/concat.rb#5
class Mustermann::Concat < ::Mustermann::Composite
  # source://mustermann//lib/mustermann/concat.rb#43
  def initialize(*_arg0, **_arg1); end

  # source://mustermann//lib/mustermann/concat.rb#55
  def ===(string); end

  # source://mustermann//lib/mustermann/concat.rb#90
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/concat.rb#60
  def match(string); end

  # source://mustermann//lib/mustermann/concat.rb#50
  def operator; end

  # source://mustermann//lib/mustermann/concat.rb#66
  def params(string); end

  # source://mustermann//lib/mustermann/concat.rb#77
  def peek_match(string); end

  # source://mustermann//lib/mustermann/concat.rb#85
  def peek_params(string); end

  # source://mustermann//lib/mustermann/concat.rb#72
  def peek_size(string); end

  # source://mustermann//lib/mustermann/concat.rb#103
  def respond_to_special?(method); end

  # source://mustermann//lib/mustermann/concat.rb#97
  def to_templates; end

  private

  # source://mustermann//lib/mustermann/concat.rb#129
  def combined_ast; end

  # source://mustermann//lib/mustermann/concat.rb#110
  def pump(string, inject_with: T.unsafe(nil), initial: T.unsafe(nil), with_size: T.unsafe(nil)); end
end

# source://mustermann//lib/mustermann/concat.rb#8
module Mustermann::Concat::Native
  # source://mustermann//lib/mustermann/concat.rb#11
  def +(other); end

  # source://mustermann//lib/mustermann/concat.rb#23
  def look_ahead(other); end

  private

  # source://mustermann//lib/mustermann/concat.rb#29
  def native_concat(other); end

  # source://mustermann//lib/mustermann/concat.rb#34
  def native_concat?(other); end
end

# source://mustermann//lib/mustermann.rb#13
Mustermann::DEFAULT_TYPE = T.let(T.unsafe(nil), Symbol)

# source://mustermann//lib/mustermann/equality_map.rb#18
class Mustermann::EqualityMap
  # source://mustermann//lib/mustermann/equality_map.rb#25
  def initialize; end

  # source://mustermann//lib/mustermann/equality_map.rb#33
  def fetch(key); end

  # source://mustermann//lib/mustermann/equality_map.rb#19
  def map; end

  private

  # source://mustermann//lib/mustermann/equality_map.rb#60
  def finalizer(hash); end

  # source://mustermann//lib/mustermann/equality_map.rb#49
  def track(key, object); end

  class << self
    # source://mustermann//lib/mustermann/equality_map.rb#21
    def new; end
  end
end

# source://mustermann//lib/mustermann/error.rb#4
class Mustermann::Error < ::StandardError; end

# source://mustermann//lib/mustermann/error.rb#7
class Mustermann::ExpandError < ::Mustermann::Error; end

# source://mustermann//lib/mustermann/expander.rb#15
class Mustermann::Expander
  # source://mustermann//lib/mustermann/expander.rb#21
  def initialize(*patterns, additional_values: T.unsafe(nil), **options, &block); end

  # source://mustermann//lib/mustermann/expander.rb#43
  def <<(*patterns); end

  # source://mustermann//lib/mustermann/expander.rb#158
  def ==(other); end

  # source://mustermann//lib/mustermann/expander.rb#43
  def add(*patterns); end

  # source://mustermann//lib/mustermann/expander.rb#16
  def additional_values; end

  # source://mustermann//lib/mustermann/expander.rb#115
  def cast(*types, &block); end

  # source://mustermann//lib/mustermann/expander.rb#164
  def eql?(other); end

  # source://mustermann//lib/mustermann/expander.rb#145
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/expander.rb#174
  def expandable?(values); end

  # source://mustermann//lib/mustermann/expander.rb#170
  def hash; end

  # source://mustermann//lib/mustermann/expander.rb#16
  def patterns; end

  private

  # source://mustermann//lib/mustermann/expander.rb#195
  def append(uri, values); end

  # source://mustermann//lib/mustermann/expander.rb#16
  def caster; end

  # source://mustermann//lib/mustermann/expander.rb#201
  def map_values(values); end

  # source://mustermann//lib/mustermann/expander.rb#191
  def slice(hash, keys); end

  # source://mustermann//lib/mustermann/expander.rb#185
  def split_values(values); end

  # source://mustermann//lib/mustermann/expander.rb#180
  def with_rest(values); end
end

# source://mustermann//lib/mustermann/error.rb#6
class Mustermann::ParseError < ::Mustermann::Error; end

# source://mustermann//lib/mustermann/pattern.rb#10
class Mustermann::Pattern
  include ::Mustermann

  # source://mustermann//lib/mustermann/pattern.rb#75
  def initialize(string, uri_decode: T.unsafe(nil), **options); end

  # source://mustermann//lib/mustermann/pattern.rb#315
  def &(other); end

  # source://mustermann//lib/mustermann/pattern.rb#336
  def +(other); end

  # source://mustermann//lib/mustermann/pattern.rb#119
  def ==(other); end

  # source://mustermann//lib/mustermann/pattern.rb#106
  def ===(string); end

  # source://mustermann//lib/mustermann/pattern.rb#98
  def =~(string); end

  # source://mustermann//lib/mustermann/pattern.rb#315
  def ^(other); end

  # source://mustermann//lib/mustermann/pattern.rb#391
  def always_array?(key); end

  # source://mustermann//lib/mustermann/pattern.rb#126
  def eql?(other); end

  # source://mustermann//lib/mustermann/pattern.rb#240
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/pattern.rb#112
  def hash; end

  # source://mustermann-contrib/3.0.3/lib/mustermann/visualizer/pattern_extension.rb#48
  def inspect; end

  # source://mustermann//lib/mustermann/pattern.rb#91
  def match(string); end

  # source://mustermann//lib/mustermann/pattern.rb#192
  def named_captures; end

  # source://mustermann//lib/mustermann/pattern.rb#198
  def names; end

  # source://mustermann//lib/mustermann/pattern.rb#67
  def options; end

  # source://mustermann//lib/mustermann/pattern.rb#204
  def params(string = T.unsafe(nil), captures: T.unsafe(nil), offset: T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/pattern.rb#153
  def peek(string); end

  # source://mustermann//lib/mustermann/pattern.rb#168
  def peek_match(string); end

  # source://mustermann//lib/mustermann/pattern.rb#185
  def peek_params(string); end

  # source://mustermann//lib/mustermann/pattern.rb#139
  def peek_size(string); end

  # source://mustermann//lib/mustermann/pattern.rb#353
  def respond_to?(method, *args); end

  # source://mustermann//lib/mustermann/pattern.rb#371
  def simple_inspect; end

  # source://mustermann//lib/mustermann/pattern.rb#346
  def to_proc; end

  # source://mustermann-contrib/3.0.3/lib/mustermann/visualizer/pattern_extension.rb#43
  def to_s; end

  # source://mustermann//lib/mustermann/pattern.rb#279
  def to_templates; end

  # source://mustermann//lib/mustermann/pattern.rb#63
  def uri_decode; end

  # source://mustermann//lib/mustermann/pattern.rb#315
  def |(other); end

  private

  # source://mustermann//lib/mustermann/pattern.rb#377
  def map_param(key, value); end

  # source://mustermann//lib/mustermann/pattern.rb#361
  def respond_to_special?(method); end

  # source://mustermann//lib/mustermann/pattern.rb#382
  def unescape(string, decode = T.unsafe(nil)); end

  class << self
    # source://mustermann//lib/mustermann/pattern.rb#50
    def new(string, ignore_unknown_options: T.unsafe(nil), **options); end

    # source://mustermann//lib/mustermann/pattern.rb#34
    def register(*names); end

    # source://mustermann//lib/mustermann/pattern.rb#40
    def supported?(option, **options); end

    # source://mustermann//lib/mustermann/pattern.rb#24
    def supported_options(*list); end
  end
end

# source://mustermann//lib/mustermann/pattern.rb#388
Mustermann::Pattern::ALWAYS_ARRAY = T.let(T.unsafe(nil), Array)

# source://mustermann//lib/mustermann/simple_match.rb#5
class Mustermann::SimpleMatch
  # source://mustermann//lib/mustermann/simple_match.rb#7
  def initialize(string = T.unsafe(nil), names: T.unsafe(nil), captures: T.unsafe(nil)); end

  # source://mustermann//lib/mustermann/simple_match.rb#38
  def +(other); end

  # source://mustermann//lib/mustermann/simple_match.rb#29
  def [](*args); end

  # source://mustermann//lib/mustermann/simple_match.rb#24
  def captures; end

  # source://mustermann//lib/mustermann/simple_match.rb#45
  def inspect; end

  # source://mustermann//lib/mustermann/simple_match.rb#19
  def names; end

  # source://mustermann//lib/mustermann/simple_match.rb#14
  def to_s; end
end
