# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-http` gem.
# Please instead update this file by running `bin/tapioca gem net-http`.


# source://net-http//lib/net/http.rb#724
class Net::HTTP < ::Net::Protocol
  # source://net-http//lib/net/http.rb#1148
  def initialize(address, port = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1488
  def active?; end

  # source://net-http//lib/net/http.rb#1265
  def address; end

  # source://net-http//lib/net/http.rb#1539
  def ca_file; end

  # source://net-http//lib/net/http.rb#1539
  def ca_file=(_arg0); end

  # source://net-http//lib/net/http.rb#1543
  def ca_path; end

  # source://net-http//lib/net/http.rb#1543
  def ca_path=(_arg0); end

  # source://net-http//lib/net/http.rb#1547
  def cert; end

  # source://net-http//lib/net/http.rb#1547
  def cert=(_arg0); end

  # source://net-http//lib/net/http.rb#1550
  def cert_store; end

  # source://net-http//lib/net/http.rb#1550
  def cert_store=(_arg0); end

  # source://net-http//lib/net/http.rb#1554
  def ciphers; end

  # source://net-http//lib/net/http.rb#1554
  def ciphers=(_arg0); end

  # source://net-http//lib/net/http.rb#1496
  def close_on_empty_response; end

  # source://net-http//lib/net/http.rb#1496
  def close_on_empty_response=(_arg0); end

  # source://net-http//lib/net/http.rb#1449
  def continue_timeout; end

  # source://net-http//lib/net/http.rb#1455
  def continue_timeout=(sec); end

  # source://net-http//lib/net/http.rb#2227
  def copy(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2201
  def delete(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1558
  def extra_chain_cert; end

  # source://net-http//lib/net/http.rb#1558
  def extra_chain_cert=(_arg0); end

  # source://net-http//lib/net/http.rb#1648
  def finish; end

  # source://net-http//lib/net/http.rb#2013
  def get(path, initheader = T.unsafe(nil), dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2280
  def get2(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2037
  def head(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2293
  def head2(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1472
  def ignore_eof; end

  # source://net-http//lib/net/http.rb#1472
  def ignore_eof=(_arg0); end

  # source://net-http//lib/net/http.rb#1206
  def inspect; end

  # source://net-http//lib/net/http.rb#1349
  def ipaddr; end

  # source://net-http//lib/net/http.rb#1361
  def ipaddr=(addr); end

  # source://net-http//lib/net/http.rb#1467
  def keep_alive_timeout; end

  # source://net-http//lib/net/http.rb#1467
  def keep_alive_timeout=(_arg0); end

  # source://net-http//lib/net/http.rb#1561
  def key; end

  # source://net-http//lib/net/http.rb#1561
  def key=(_arg0); end

  # source://net-http//lib/net/http.rb#1272
  def local_host; end

  # source://net-http//lib/net/http.rb#1272
  def local_host=(_arg0); end

  # source://net-http//lib/net/http.rb#1276
  def local_port; end

  # source://net-http//lib/net/http.rb#1276
  def local_port=(_arg0); end

  # source://net-http//lib/net/http.rb#2147
  def lock(path, body, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1405
  def max_retries; end

  # source://net-http//lib/net/http.rb#1395
  def max_retries=(retries); end

  # source://net-http//lib/net/http.rb#1576
  def max_version; end

  # source://net-http//lib/net/http.rb#1576
  def max_version=(_arg0); end

  # source://net-http//lib/net/http.rb#1572
  def min_version; end

  # source://net-http//lib/net/http.rb#1572
  def min_version=(_arg0); end

  # source://net-http//lib/net/http.rb#2241
  def mkcol(path, body = T.unsafe(nil), initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2214
  def move(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1371
  def open_timeout; end

  # source://net-http//lib/net/http.rb#1371
  def open_timeout=(_arg0); end

  # source://net-http//lib/net/http.rb#2174
  def options(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2100
  def patch(path, data, initheader = T.unsafe(nil), dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1597
  def peer_cert; end

  # source://net-http//lib/net/http.rb#1268
  def port; end

  # source://net-http//lib/net/http.rb#2071
  def post(path, data, initheader = T.unsafe(nil), dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2320
  def post2(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2188
  def propfind(path, body = T.unsafe(nil), initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2133
  def proppatch(path, body, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1881
  def proxy?; end

  # source://net-http//lib/net/http.rb#1903
  def proxy_address; end

  # source://net-http//lib/net/http.rb#1312
  def proxy_address=(_arg0); end

  # source://net-http//lib/net/http.rb#1308
  def proxy_from_env=(_arg0); end

  # source://net-http//lib/net/http.rb#1888
  def proxy_from_env?; end

  # source://net-http//lib/net/http.rb#1934
  def proxy_pass; end

  # source://net-http//lib/net/http.rb#1324
  def proxy_pass=(_arg0); end

  # source://net-http//lib/net/http.rb#1913
  def proxy_port; end

  # source://net-http//lib/net/http.rb#1316
  def proxy_port=(_arg0); end

  # source://net-http//lib/net/http.rb#1893
  def proxy_uri; end

  # source://net-http//lib/net/http.rb#1328
  def proxy_use_ssl=(_arg0); end

  # source://net-http//lib/net/http.rb#1923
  def proxy_user; end

  # source://net-http//lib/net/http.rb#1320
  def proxy_user=(_arg0); end

  # source://net-http//lib/net/http.rb#1903
  def proxyaddr; end

  # source://net-http//lib/net/http.rb#1913
  def proxyport; end

  # source://net-http//lib/net/http.rb#2119
  def put(path, data, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2334
  def put2(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1376
  def read_timeout; end

  # source://net-http//lib/net/http.rb#1418
  def read_timeout=(sec); end

  # source://net-http//lib/net/http.rb#2399
  def request(req, body = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2280
  def request_get(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2293
  def request_head(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2320
  def request_post(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2334
  def request_put(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1280
  def response_body_encoding; end

  # source://net-http//lib/net/http.rb#1300
  def response_body_encoding=(value); end

  # source://net-http//lib/net/http.rb#2363
  def send_request(name, path, data = T.unsafe(nil), header = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1259
  def set_debug_output(output); end

  # source://net-http//lib/net/http.rb#1564
  def ssl_timeout; end

  # source://net-http//lib/net/http.rb#1564
  def ssl_timeout=(_arg0); end

  # source://net-http//lib/net/http.rb#1568
  def ssl_version; end

  # source://net-http//lib/net/http.rb#1568
  def ssl_version=(_arg0); end

  # source://net-http//lib/net/http.rb#1625
  def start; end

  # source://net-http//lib/net/http.rb#1488
  def started?; end

  # source://net-http//lib/net/http.rb#2254
  def trace(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2161
  def unlock(path, body, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1510
  def use_ssl=(flag); end

  # source://net-http//lib/net/http.rb#1500
  def use_ssl?; end

  # source://net-http//lib/net/http.rb#1579
  def verify_callback; end

  # source://net-http//lib/net/http.rb#1579
  def verify_callback=(_arg0); end

  # source://net-http//lib/net/http.rb#1582
  def verify_depth; end

  # source://net-http//lib/net/http.rb#1582
  def verify_depth=(_arg0); end

  # source://net-http//lib/net/http.rb#1592
  def verify_hostname; end

  # source://net-http//lib/net/http.rb#1592
  def verify_hostname=(_arg0); end

  # source://net-http//lib/net/http.rb#1587
  def verify_mode; end

  # source://net-http//lib/net/http.rb#1587
  def verify_mode=(_arg0); end

  # source://net-http//lib/net/http.rb#1381
  def write_timeout; end

  # source://net-http//lib/net/http.rb#1442
  def write_timeout=(sec); end

  private

  # source://net-http//lib/net/http.rb#2581
  def D(msg); end

  # source://net-http//lib/net/http.rb#2573
  def addr_port; end

  # source://net-http//lib/net/http.rb#2490
  def begin_transport(req); end

  # source://net-http//lib/net/http.rb#1957
  def conn_address; end

  # source://net-http//lib/net/http.rb#1961
  def conn_port; end

  # source://net-http//lib/net/http.rb#1660
  def connect; end

  # source://net-http//lib/net/http.rb#2581
  def debug(msg); end

  # source://net-http//lib/net/http.rb#1802
  def do_finish; end

  # source://net-http//lib/net/http.rb#1654
  def do_start; end

  # source://net-http//lib/net/http.rb#1965
  def edit_path(path); end

  # source://net-http//lib/net/http.rb#2513
  def end_transport(req, res); end

  # source://net-http//lib/net/http.rb#2530
  def keep_alive?(req, res); end

  # source://net-http//lib/net/http.rb#1798
  def on_connect; end

  # source://net-http//lib/net/http.rb#2422
  def send_entity(path, data, initheader, dest, type, &block); end

  # source://net-http//lib/net/http.rb#2554
  def sspi_auth(req); end

  # source://net-http//lib/net/http.rb#2539
  def sspi_auth?(res); end

  # source://net-http//lib/net/http.rb#1787
  def timeouted_connect(conn_addr, conn_port); end

  # source://net-http//lib/net/http.rb#2435
  def transport_request(req); end

  # source://net-http//lib/net/http.rb#1949
  def unescape(value); end

  class << self
    # source://net-http//lib/net/http.rb#1829
    def Proxy(p_addr = T.unsafe(nil), p_port = T.unsafe(nil), p_user = T.unsafe(nil), p_pass = T.unsafe(nil), p_use_ssl = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#1142
    def default_configuration; end

    # source://net-http//lib/net/http.rb#1142
    def default_configuration=(_arg0); end

    # source://net-http//lib/net/http.rb#935
    def default_port; end

    # source://net-http//lib/net/http.rb#804
    def get(uri_or_host, path_or_headers = T.unsafe(nil), port = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#763
    def get_print(uri_or_host, path_or_headers = T.unsafe(nil), port = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#814
    def get_response(uri_or_host, path_or_headers = T.unsafe(nil), port = T.unsafe(nil), &block); end

    # source://net-http//lib/net/http.rb#943
    def http_default_port; end

    # source://net-http//lib/net/http.rb#951
    def https_default_port; end

    # source://net-http//lib/net/http.rb#748
    def is_version_1_1?; end

    # source://net-http//lib/net/http.rb#743
    def is_version_1_2?; end

    # source://net-http//lib/net/http.rb#1100
    def new(address, port = T.unsafe(nil), p_addr = T.unsafe(nil), p_port = T.unsafe(nil), p_user = T.unsafe(nil), p_pass = T.unsafe(nil), p_no_proxy = T.unsafe(nil), p_use_ssl = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#857
    def post(url, data, header = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#884
    def post_form(url, params); end

    # source://net-http//lib/net/http.rb#1861
    def proxy_address; end

    # source://net-http//lib/net/http.rb#1855
    def proxy_class?; end

    # source://net-http//lib/net/http.rb#1873
    def proxy_pass; end

    # source://net-http//lib/net/http.rb#1865
    def proxy_port; end

    # source://net-http//lib/net/http.rb#1876
    def proxy_use_ssl; end

    # source://net-http//lib/net/http.rb#1869
    def proxy_user; end

    # source://net-http//lib/net/http.rb#920
    def put(url, data, header = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#955
    def socket_type; end

    # source://net-http//lib/net/http.rb#1045
    def start(address, *arg, &block); end

    # source://net-http//lib/net/http.rb#748
    def version_1_1?; end

    # source://net-http//lib/net/http.rb#738
    def version_1_2; end

    # source://net-http//lib/net/http.rb#743
    def version_1_2?; end
  end
end

# source://net-http//lib/net/http/proxy_delta.rb#2
module Net::HTTP::ProxyDelta
  private

  # source://net-http//lib/net/http/proxy_delta.rb#5
  def conn_address; end

  # source://net-http//lib/net/http/proxy_delta.rb#9
  def conn_port; end

  # source://net-http//lib/net/http/proxy_delta.rb#13
  def edit_path(path); end
end

# source://net-http//lib/net/http.rb#1778
Net::HTTP::TCP_SOCKET_NEW_HAS_OPEN_TIMEOUT = T.let(T.unsafe(nil), FalseClass)

# source://net-http//lib/net/http.rb#727
Net::HTTP::VERSION = T.let(T.unsafe(nil), String)

# source://net-http//lib/net/http/responses.rb#325
class Net::HTTPAlreadyReported < ::Net::HTTPSuccess; end

# source://net-http//lib/net/http/responses.rb#327
Net::HTTPAlreadyReported::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#73
Net::HTTPClientError::EXCEPTION_TYPE = Net::HTTPClientException

# source://net-http//lib/net/http/exceptions.rb#24
class Net::HTTPClientException < ::Net::ProtoServerError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/responses.rb#157
class Net::HTTPEarlyHints < ::Net::HTTPInformation; end

# source://net-http//lib/net/http/responses.rb#159
Net::HTTPEarlyHints::HAS_BODY = T.let(T.unsafe(nil), FalseClass)

# source://net-http//lib/net/http/exceptions.rb#16
class Net::HTTPError < ::Net::ProtocolError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/exceptions.rb#6
module Net::HTTPExceptions
  # source://net-http//lib/net/http/exceptions.rb#7
  def initialize(msg, res); end

  # source://net-http//lib/net/http/exceptions.rb#11
  def response; end
end

# source://net-http//lib/net/http/exceptions.rb#28
class Net::HTTPFatalError < ::Net::ProtoFatalError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/generic_request.rb#11
class Net::HTTPGenericRequest
  include ::Net::HTTPHeader

  # source://net-http//lib/net/http/generic_request.rb#15
  def initialize(m, reqbody, resbody, uri_or_path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http/generic_request.rb#131
  def []=(key, val); end

  # source://net-http//lib/net/http/generic_request.rb#167
  def body; end

  # source://net-http//lib/net/http/generic_request.rb#176
  def body=(str); end

  # source://net-http//lib/net/http/generic_request.rb#155
  def body_exist?; end

  # source://net-http//lib/net/http/generic_request.rb#191
  def body_stream; end

  # source://net-http//lib/net/http/generic_request.rb#201
  def body_stream=(input); end

  # source://net-http//lib/net/http/generic_request.rb#92
  def decode_content; end

  # source://net-http//lib/net/http/generic_request.rb#220
  def exec(sock, ver, path); end

  # source://net-http//lib/net/http/generic_request.rb#98
  def inspect; end

  # source://net-http//lib/net/http/generic_request.rb#62
  def method; end

  # source://net-http//lib/net/http/generic_request.rb#69
  def path; end

  # source://net-http//lib/net/http/generic_request.rb#116
  def pretty_print(q); end

  # source://net-http//lib/net/http/generic_request.rb#142
  def request_body_permitted?; end

  # source://net-http//lib/net/http/generic_request.rb#151
  def response_body_permitted?; end

  # source://net-http//lib/net/http/generic_request.rb#208
  def set_body_internal(str); end

  # source://net-http//lib/net/http/generic_request.rb#232
  def update_uri(addr, port, ssl); end

  # source://net-http//lib/net/http/generic_request.rb#77
  def uri; end

  private

  # source://net-http//lib/net/http/generic_request.rb#334
  def encode_multipart_form_data(out, params, opt); end

  # source://net-http//lib/net/http/generic_request.rb#390
  def flush_buffer(out, buf, chunked_p); end

  # source://net-http//lib/net/http/generic_request.rb#385
  def quote_string(str, charset); end

  # source://net-http//lib/net/http/generic_request.rb#284
  def send_request_with_body(sock, ver, path, body); end

  # source://net-http//lib/net/http/generic_request.rb#308
  def send_request_with_body_data(sock, ver, path, params); end

  # source://net-http//lib/net/http/generic_request.rb#292
  def send_request_with_body_stream(sock, ver, path, f); end

  # source://net-http//lib/net/http/generic_request.rb#402
  def wait_for_continue(sock, ver); end

  # source://net-http//lib/net/http/generic_request.rb#415
  def write_header(sock, ver, path); end
end

# source://net-http//lib/net/http/generic_request.rb#266
class Net::HTTPGenericRequest::Chunker
  # source://net-http//lib/net/http/generic_request.rb#267
  def initialize(sock); end

  # source://net-http//lib/net/http/generic_request.rb#279
  def finish; end

  # source://net-http//lib/net/http/generic_request.rb#272
  def write(buf); end
end

# source://net-http//lib/net/http/header.rb#181
module Net::HTTPHeader
  # source://net-http//lib/net/http/header.rb#226
  def [](key); end

  # source://net-http//lib/net/http/header.rb#242
  def []=(key, val); end

  # source://net-http//lib/net/http/header.rb#263
  def add_field(key, val); end

  # source://net-http//lib/net/http/header.rb#949
  def basic_auth(account, password); end

  # source://net-http//lib/net/http/header.rb#488
  def canonical_each; end

  # source://net-http//lib/net/http/header.rb#658
  def chunked?; end

  # source://net-http//lib/net/http/header.rb#970
  def connection_close?; end

  # source://net-http//lib/net/http/header.rb#978
  def connection_keep_alive?; end

  # source://net-http//lib/net/http/header.rb#620
  def content_length; end

  # source://net-http//lib/net/http/header.rb#641
  def content_length=(len); end

  # source://net-http//lib/net/http/header.rb#674
  def content_range; end

  # source://net-http//lib/net/http/header.rb#705
  def content_type; end

  # source://net-http//lib/net/http/header.rb#776
  def content_type=(type, params = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#457
  def delete(key); end

  # source://net-http//lib/net/http/header.rb#368
  def each; end

  # source://net-http//lib/net/http/header.rb#488
  def each_capitalized; end

  # source://net-http//lib/net/http/header.rb#421
  def each_capitalized_name; end

  # source://net-http//lib/net/http/header.rb#368
  def each_header; end

  # source://net-http//lib/net/http/header.rb#395
  def each_key(&block); end

  # source://net-http//lib/net/http/header.rb#395
  def each_name(&block); end

  # source://net-http//lib/net/http/header.rb#442
  def each_value; end

  # source://net-http//lib/net/http/header.rb#345
  def fetch(key, *args, &block); end

  # source://net-http//lib/net/http/header.rb#816
  def form_data=(params, sep = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#310
  def get_fields(key); end

  # source://net-http//lib/net/http/header.rb#187
  def initialize_http_header(initheader); end

  # source://net-http//lib/net/http/header.rb#467
  def key?(key); end

  # source://net-http//lib/net/http/header.rb#210
  def length; end

  # source://net-http//lib/net/http/header.rb#727
  def main_type; end

  # source://net-http//lib/net/http/header.rb#960
  def proxy_basic_auth(account, password); end

  # source://net-http//lib/net/http/header.rb#513
  def range; end

  # source://net-http//lib/net/http/header.rb#580
  def range=(r, e = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#691
  def range_length; end

  # source://net-http//lib/net/http/header.rb#776
  def set_content_type(type, params = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#928
  def set_form(params, enctype = T.unsafe(nil), formopt = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#816
  def set_form_data(params, sep = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#580
  def set_range(r, e = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#210
  def size; end

  # source://net-http//lib/net/http/header.rb#742
  def sub_type; end

  # source://net-http//lib/net/http/header.rb#481
  def to_hash; end

  # source://net-http//lib/net/http/header.rb#757
  def type_params; end

  private

  # source://net-http//lib/net/http/header.rb#288
  def append_field_value(ary, val); end

  # source://net-http//lib/net/http/header.rb#964
  def basic_encode(account, password); end

  # source://net-http//lib/net/http/header.rb#497
  def capitalize(name); end

  # source://net-http//lib/net/http/header.rb#273
  def set_field(key, val); end
end

# source://net-http//lib/net/http/header.rb#185
Net::HTTPHeader::MAX_FIELD_LENGTH = T.let(T.unsafe(nil), Integer)

# source://net-http//lib/net/http/header.rb#183
Net::HTTPHeader::MAX_KEY_LENGTH = T.let(T.unsafe(nil), Integer)

# source://net-http//lib/net/http/responses.rb#26
Net::HTTPInformation::EXCEPTION_TYPE = Net::HTTPError

# source://net-http//lib/net/http/responses.rb#1125
class Net::HTTPLoopDetected < ::Net::HTTPServerError; end

# source://net-http//lib/net/http/responses.rb#1127
Net::HTTPLoopDetected::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#823
class Net::HTTPMisdirectedRequest < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#825
Net::HTTPMisdirectedRequest::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#402
Net::HTTPMovedTemporarily = Net::HTTPFound

# source://net-http//lib/net/http/responses.rb#365
Net::HTTPMultipleChoice = Net::HTTPMultipleChoices

# source://net-http//lib/net/http/responses.rb#1143
class Net::HTTPNotExtended < ::Net::HTTPServerError; end

# source://net-http//lib/net/http/responses.rb#1145
Net::HTTPNotExtended::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#730
class Net::HTTPPayloadTooLarge < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#732
Net::HTTPPayloadTooLarge::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#138
class Net::HTTPProcessing < ::Net::HTTPInformation; end

# source://net-http//lib/net/http/responses.rb#140
Net::HTTPProcessing::HAS_BODY = T.let(T.unsafe(nil), FalseClass)

# source://net-http//lib/net/http/responses.rb#784
class Net::HTTPRangeNotSatisfiable < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#786
Net::HTTPRangeNotSatisfiable::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#58
Net::HTTPRedirection::EXCEPTION_TYPE = Net::HTTPRetriableError

# source://net-http//lib/net/http/request.rb#75
class Net::HTTPRequest < ::Net::HTTPGenericRequest
  # source://net-http//lib/net/http/request.rb#82
  def initialize(path, initheader = T.unsafe(nil)); end
end

# source://net-http//lib/net/http/responses.rb#753
Net::HTTPRequestURITooLarge = Net::HTTPURITooLong

# source://net-http//lib/net/http/response.rb#135
class Net::HTTPResponse
  include ::Net::HTTPHeader

  # source://net-http//lib/net/http/response.rb#195
  def initialize(httpv, code, msg); end

  # source://net-http//lib/net/http/response.rb#401
  def body; end

  # source://net-http//lib/net/http/response.rb#406
  def body=(value); end

  # source://net-http//lib/net/http/response.rb#230
  def body_encoding; end

  # source://net-http//lib/net/http/response.rb#254
  def body_encoding=(value); end

  # source://net-http//lib/net/http/response.rb#214
  def code; end

  # source://net-http//lib/net/http/response.rb#271
  def code_type; end

  # source://net-http//lib/net/http/response.rb#226
  def decode_content; end

  # source://net-http//lib/net/http/response.rb#226
  def decode_content=(_arg0); end

  # source://net-http//lib/net/http/response.rb#401
  def entity; end

  # source://net-http//lib/net/http/response.rb#275
  def error!; end

  # source://net-http//lib/net/http/response.rb#281
  def error_type; end

  # source://net-http//lib/net/http/response.rb#303
  def header; end

  # source://net-http//lib/net/http/response.rb#209
  def http_version; end

  # source://net-http//lib/net/http/response.rb#261
  def ignore_eof; end

  # source://net-http//lib/net/http/response.rb#261
  def ignore_eof=(_arg0); end

  # source://net-http//lib/net/http/response.rb#263
  def inspect; end

  # source://net-http//lib/net/http/response.rb#217
  def message; end

  # source://net-http//lib/net/http/response.rb#217
  def msg; end

  # source://net-http//lib/net/http/response.rb#356
  def read_body(dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http/response.rb#308
  def read_header; end

  # source://net-http//lib/net/http/response.rb#317
  def reading_body(sock, reqmethodallowbody); end

  # source://net-http//lib/net/http/response.rb#298
  def response; end

  # source://net-http//lib/net/http/response.rb#222
  def uri; end

  # source://net-http//lib/net/http/response.rb#290
  def uri=(uri); end

  # source://net-http//lib/net/http/response.rb#286
  def value; end

  private

  # source://net-http//lib/net/http/response.rb#451
  def check_bom(str); end

  # source://net-http//lib/net/http/response.rb#415
  def detect_encoding(str, encoding = T.unsafe(nil)); end

  # source://net-http//lib/net/http/response.rb#541
  def extracting_encodings_from_meta_elements(value); end

  # source://net-http//lib/net/http/response.rb#506
  def get_attribute(ss); end

  # source://net-http//lib/net/http/response.rb#558
  def inflater; end

  # source://net-http//lib/net/http/response.rb#647
  def procdest(dest, block); end

  # source://net-http//lib/net/http/response.rb#593
  def read_body_0(dest); end

  # source://net-http//lib/net/http/response.rb#623
  def read_chunked(dest, chunk_data_io); end

  # source://net-http//lib/net/http/response.rb#465
  def scanning_meta(str); end

  # source://net-http//lib/net/http/response.rb#435
  def sniff_encoding(str, encoding = T.unsafe(nil)); end

  # source://net-http//lib/net/http/response.rb#643
  def stream_check; end

  class << self
    # source://net-http//lib/net/http/response.rb#138
    def body_permitted?; end

    # source://net-http//lib/net/http/response.rb#142
    def exception_type; end

    # source://net-http//lib/net/http/response.rb#146
    def read_new(sock); end

    private

    # source://net-http//lib/net/http/response.rb#171
    def each_response_header(sock); end

    # source://net-http//lib/net/http/response.rb#158
    def read_status_line(sock); end

    # source://net-http//lib/net/http/response.rb#165
    def response_class(code); end
  end
end

# source://net-http//lib/net/http/response.rb#661
class Net::HTTPResponse::Inflater
  # source://net-http//lib/net/http/response.rb#666
  def initialize(socket); end

  # source://net-http//lib/net/http/response.rb#684
  def bytes_inflated; end

  # source://net-http//lib/net/http/response.rb#675
  def finish; end

  # source://net-http//lib/net/http/response.rb#694
  def inflate_adapter(dest); end

  # source://net-http//lib/net/http/response.rb#721
  def read(clen, dest, ignore_eof = T.unsafe(nil)); end

  # source://net-http//lib/net/http/response.rb#730
  def read_all(dest); end
end

# source://net-http//lib/net/http/exceptions.rb#20
class Net::HTTPRetriableError < ::Net::ProtoRetriableError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/responses.rb#88
Net::HTTPServerError::EXCEPTION_TYPE = Net::HTTPFatalError

# source://net-http//lib/net/http.rb#2593
Net::HTTPSession = Net::HTTP

# source://net-http//lib/net/http/responses.rb#42
Net::HTTPSuccess::EXCEPTION_TYPE = Net::HTTPError

# source://net-http//lib/net/http/responses.rb#748
class Net::HTTPURITooLong < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#750
Net::HTTPURITooLong::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#11
Net::HTTPUnknownResponse::EXCEPTION_TYPE = Net::HTTPError

# source://net-http//lib/net/http/responses.rb#1091
class Net::HTTPVariantAlsoNegotiates < ::Net::HTTPServerError; end

# source://net-http//lib/net/http/responses.rb#1093
Net::HTTPVariantAlsoNegotiates::HAS_BODY = T.let(T.unsafe(nil), TrueClass)
