# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-http` gem.
# Please instead update this file by running `bin/tapioca gem net-http`.


# source://net-http//lib/net/http.rb#730
class Net::HTTP < ::Net::Protocol
  # source://net-http//lib/net/http.rb#1154
  def initialize(address, port = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1490
  def active?; end

  # source://net-http//lib/net/http.rb#1270
  def address; end

  # source://net-http//lib/net/http.rb#1541
  def ca_file; end

  # source://net-http//lib/net/http.rb#1541
  def ca_file=(_arg0); end

  # source://net-http//lib/net/http.rb#1545
  def ca_path; end

  # source://net-http//lib/net/http.rb#1545
  def ca_path=(_arg0); end

  # source://net-http//lib/net/http.rb#1549
  def cert; end

  # source://net-http//lib/net/http.rb#1549
  def cert=(_arg0); end

  # source://net-http//lib/net/http.rb#1552
  def cert_store; end

  # source://net-http//lib/net/http.rb#1552
  def cert_store=(_arg0); end

  # source://net-http//lib/net/http.rb#1556
  def ciphers; end

  # source://net-http//lib/net/http.rb#1556
  def ciphers=(_arg0); end

  # source://net-http//lib/net/http.rb#1498
  def close_on_empty_response; end

  # source://net-http//lib/net/http.rb#1498
  def close_on_empty_response=(_arg0); end

  # source://net-http//lib/net/http.rb#1451
  def continue_timeout; end

  # source://net-http//lib/net/http.rb#1457
  def continue_timeout=(sec); end

  # source://net-http//lib/net/http.rb#2201
  def copy(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2175
  def delete(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1560
  def extra_chain_cert; end

  # source://net-http//lib/net/http.rb#1560
  def extra_chain_cert=(_arg0); end

  # source://net-http//lib/net/http.rb#1776
  def finish; end

  # source://net-http//lib/net/http.rb#1987
  def get(path, initheader = T.unsafe(nil), dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2254
  def get2(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2011
  def head(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2267
  def head2(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1474
  def ignore_eof; end

  # source://net-http//lib/net/http.rb#1474
  def ignore_eof=(_arg0); end

  # source://net-http//lib/net/http.rb#1211
  def inspect; end

  # source://net-http//lib/net/http.rb#1351
  def ipaddr; end

  # source://net-http//lib/net/http.rb#1363
  def ipaddr=(addr); end

  # source://net-http//lib/net/http.rb#1469
  def keep_alive_timeout; end

  # source://net-http//lib/net/http.rb#1469
  def keep_alive_timeout=(_arg0); end

  # source://net-http//lib/net/http.rb#1563
  def key; end

  # source://net-http//lib/net/http.rb#1563
  def key=(_arg0); end

  # source://net-http//lib/net/http.rb#1277
  def local_host; end

  # source://net-http//lib/net/http.rb#1277
  def local_host=(_arg0); end

  # source://net-http//lib/net/http.rb#1281
  def local_port; end

  # source://net-http//lib/net/http.rb#1281
  def local_port=(_arg0); end

  # source://net-http//lib/net/http.rb#2121
  def lock(path, body, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1407
  def max_retries; end

  # source://net-http//lib/net/http.rb#1397
  def max_retries=(retries); end

  # source://net-http//lib/net/http.rb#1578
  def max_version; end

  # source://net-http//lib/net/http.rb#1578
  def max_version=(_arg0); end

  # source://net-http//lib/net/http.rb#1574
  def min_version; end

  # source://net-http//lib/net/http.rb#1574
  def min_version=(_arg0); end

  # source://net-http//lib/net/http.rb#2215
  def mkcol(path, body = T.unsafe(nil), initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2188
  def move(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1373
  def open_timeout; end

  # source://net-http//lib/net/http.rb#1373
  def open_timeout=(_arg0); end

  # source://net-http//lib/net/http.rb#2148
  def options(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2074
  def patch(path, data, initheader = T.unsafe(nil), dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1599
  def peer_cert; end

  # source://net-http//lib/net/http.rb#1273
  def port; end

  # source://net-http//lib/net/http.rb#2045
  def post(path, data, initheader = T.unsafe(nil), dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2294
  def post2(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2162
  def propfind(path, body = T.unsafe(nil), initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2107
  def proppatch(path, body, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1858
  def proxy?; end

  # source://net-http//lib/net/http.rb#1880
  def proxy_address; end

  # source://net-http//lib/net/http.rb#1317
  def proxy_address=(_arg0); end

  # source://net-http//lib/net/http.rb#1313
  def proxy_from_env=(_arg0); end

  # source://net-http//lib/net/http.rb#1865
  def proxy_from_env?; end

  # source://net-http//lib/net/http.rb#1911
  def proxy_pass; end

  # source://net-http//lib/net/http.rb#1329
  def proxy_pass=(_arg0); end

  # source://net-http//lib/net/http.rb#1890
  def proxy_port; end

  # source://net-http//lib/net/http.rb#1321
  def proxy_port=(_arg0); end

  # source://net-http//lib/net/http.rb#1870
  def proxy_uri; end

  # source://net-http//lib/net/http.rb#1330
  def proxy_use_ssl=(_arg0); end

  # source://net-http//lib/net/http.rb#1900
  def proxy_user; end

  # source://net-http//lib/net/http.rb#1325
  def proxy_user=(_arg0); end

  # source://net-http//lib/net/http.rb#1880
  def proxyaddr; end

  # source://net-http//lib/net/http.rb#1890
  def proxyport; end

  # source://net-http//lib/net/http.rb#2093
  def put(path, data, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2308
  def put2(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1378
  def read_timeout; end

  # source://net-http//lib/net/http.rb#1420
  def read_timeout=(sec); end

  # source://net-http//lib/net/http.rb#2373
  def request(req, body = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2254
  def request_get(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2267
  def request_head(path, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2294
  def request_post(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#2308
  def request_put(path, data, initheader = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http.rb#1285
  def response_body_encoding; end

  # source://net-http//lib/net/http.rb#1305
  def response_body_encoding=(value); end

  # source://net-http//lib/net/http.rb#2337
  def send_request(name, path, data = T.unsafe(nil), header = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1264
  def set_debug_output(output); end

  # source://net-http//lib/net/http.rb#1566
  def ssl_timeout; end

  # source://net-http//lib/net/http.rb#1566
  def ssl_timeout=(_arg0); end

  # source://net-http//lib/net/http.rb#1570
  def ssl_version; end

  # source://net-http//lib/net/http.rb#1570
  def ssl_version=(_arg0); end

  # source://net-http//lib/net/http.rb#1627
  def start; end

  # source://net-http//lib/net/http.rb#1490
  def started?; end

  # source://net-http//lib/net/http.rb#2228
  def trace(path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#2135
  def unlock(path, body, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http.rb#1512
  def use_ssl=(flag); end

  # source://net-http//lib/net/http.rb#1502
  def use_ssl?; end

  # source://net-http//lib/net/http.rb#1581
  def verify_callback; end

  # source://net-http//lib/net/http.rb#1581
  def verify_callback=(_arg0); end

  # source://net-http//lib/net/http.rb#1584
  def verify_depth; end

  # source://net-http//lib/net/http.rb#1584
  def verify_depth=(_arg0); end

  # source://net-http//lib/net/http.rb#1594
  def verify_hostname; end

  # source://net-http//lib/net/http.rb#1594
  def verify_hostname=(_arg0); end

  # source://net-http//lib/net/http.rb#1589
  def verify_mode; end

  # source://net-http//lib/net/http.rb#1589
  def verify_mode=(_arg0); end

  # source://net-http//lib/net/http.rb#1383
  def write_timeout; end

  # source://net-http//lib/net/http.rb#1444
  def write_timeout=(sec); end

  private

  # source://net-http//lib/net/http.rb#2553
  def D(msg); end

  # source://net-http//lib/net/http.rb#2545
  def addr_port; end

  # source://net-http//lib/net/http.rb#2462
  def begin_transport(req); end

  # source://net-http//lib/net/http.rb#1932
  def conn_address; end

  # source://net-http//lib/net/http.rb#1936
  def conn_port; end

  # source://net-http//lib/net/http.rb#1647
  def connect; end

  # source://net-http//lib/net/http.rb#2553
  def debug(msg); end

  # source://net-http//lib/net/http.rb#1781
  def do_finish; end

  # source://net-http//lib/net/http.rb#1641
  def do_start; end

  # source://net-http//lib/net/http.rb#1940
  def edit_path(path); end

  # source://net-http//lib/net/http.rb#2485
  def end_transport(req, res); end

  # source://net-http//lib/net/http.rb#2502
  def keep_alive?(req, res); end

  # source://net-http//lib/net/http.rb#1763
  def on_connect; end

  # source://net-http//lib/net/http.rb#2396
  def send_entity(path, data, initheader, dest, type, &block); end

  # source://net-http//lib/net/http.rb#2526
  def sspi_auth(req); end

  # source://net-http//lib/net/http.rb#2511
  def sspi_auth?(res); end

  # source://net-http//lib/net/http.rb#2407
  def transport_request(req); end

  # source://net-http//lib/net/http.rb#1925
  def unescape(value); end

  class << self
    # source://net-http//lib/net/http.rb#1808
    def Proxy(p_addr = T.unsafe(nil), p_port = T.unsafe(nil), p_user = T.unsafe(nil), p_pass = T.unsafe(nil), p_use_ssl = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#1148
    def default_configuration; end

    # source://net-http//lib/net/http.rb#1148
    def default_configuration=(_arg0); end

    # source://net-http//lib/net/http.rb#941
    def default_port; end

    # source://net-http//lib/net/http.rb#810
    def get(uri_or_host, path_or_headers = T.unsafe(nil), port = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#769
    def get_print(uri_or_host, path_or_headers = T.unsafe(nil), port = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#820
    def get_response(uri_or_host, path_or_headers = T.unsafe(nil), port = T.unsafe(nil), &block); end

    # source://net-http//lib/net/http.rb#949
    def http_default_port; end

    # source://net-http//lib/net/http.rb#957
    def https_default_port; end

    # source://net-http//lib/net/http.rb#754
    def is_version_1_1?; end

    # source://net-http//lib/net/http.rb#749
    def is_version_1_2?; end

    # source://net-http//lib/net/http.rb#1106
    def new(address, port = T.unsafe(nil), p_addr = T.unsafe(nil), p_port = T.unsafe(nil), p_user = T.unsafe(nil), p_pass = T.unsafe(nil), p_no_proxy = T.unsafe(nil), p_use_ssl = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#863
    def post(url, data, header = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#890
    def post_form(url, params); end

    # source://net-http//lib/net/http.rb#1838
    def proxy_address; end

    # source://net-http//lib/net/http.rb#1832
    def proxy_class?; end

    # source://net-http//lib/net/http.rb#1850
    def proxy_pass; end

    # source://net-http//lib/net/http.rb#1842
    def proxy_port; end

    # source://net-http//lib/net/http.rb#1853
    def proxy_use_ssl; end

    # source://net-http//lib/net/http.rb#1846
    def proxy_user; end

    # source://net-http//lib/net/http.rb#926
    def put(url, data, header = T.unsafe(nil)); end

    # source://net-http//lib/net/http.rb#961
    def socket_type; end

    # source://net-http//lib/net/http.rb#1051
    def start(address, *arg, &block); end

    # source://net-http//lib/net/http.rb#754
    def version_1_1?; end

    # source://net-http//lib/net/http.rb#744
    def version_1_2; end

    # source://net-http//lib/net/http.rb#749
    def version_1_2?; end
  end
end

# source://net-http//lib/net/http/proxy_delta.rb#2
module Net::HTTP::ProxyDelta
  private

  # source://net-http//lib/net/http/proxy_delta.rb#5
  def conn_address; end

  # source://net-http//lib/net/http/proxy_delta.rb#9
  def conn_port; end

  # source://net-http//lib/net/http/proxy_delta.rb#13
  def edit_path(path); end
end

# source://net-http//lib/net/http.rb#733
Net::HTTP::VERSION = T.let(T.unsafe(nil), String)

# source://net-http//lib/net/http/responses.rb#306
class Net::HTTPAlreadyReported < ::Net::HTTPSuccess; end

# source://net-http//lib/net/http/responses.rb#307
Net::HTTPAlreadyReported::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#67
Net::HTTPClientError::EXCEPTION_TYPE = Net::HTTPClientException

# source://net-http//lib/net/http/exceptions.rb#23
class Net::HTTPClientException < ::Net::ProtoServerError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/responses.rb#147
class Net::HTTPEarlyHints < ::Net::HTTPInformation; end

# source://net-http//lib/net/http/responses.rb#148
Net::HTTPEarlyHints::HAS_BODY = T.let(T.unsafe(nil), FalseClass)

# source://net-http//lib/net/http/exceptions.rb#15
class Net::HTTPError < ::Net::ProtocolError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/exceptions.rb#6
module Net::HTTPExceptions
  # source://net-http//lib/net/http/exceptions.rb#7
  def initialize(msg, res); end

  # source://net-http//lib/net/http/exceptions.rb#11
  def response; end
end

# source://net-http//lib/net/http/exceptions.rb#27
class Net::HTTPFatalError < ::Net::ProtoFatalError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/generic_request.rb#11
class Net::HTTPGenericRequest
  include ::Net::HTTPHeader

  # source://net-http//lib/net/http/generic_request.rb#15
  def initialize(m, reqbody, resbody, uri_or_path, initheader = T.unsafe(nil)); end

  # source://net-http//lib/net/http/generic_request.rb#109
  def []=(key, val); end

  # source://net-http//lib/net/http/generic_request.rb#145
  def body; end

  # source://net-http//lib/net/http/generic_request.rb#154
  def body=(str); end

  # source://net-http//lib/net/http/generic_request.rb#133
  def body_exist?; end

  # source://net-http//lib/net/http/generic_request.rb#169
  def body_stream; end

  # source://net-http//lib/net/http/generic_request.rb#179
  def body_stream=(input); end

  # source://net-http//lib/net/http/generic_request.rb#95
  def decode_content; end

  # source://net-http//lib/net/http/generic_request.rb#198
  def exec(sock, ver, path); end

  # source://net-http//lib/net/http/generic_request.rb#101
  def inspect; end

  # source://net-http//lib/net/http/generic_request.rb#65
  def method; end

  # source://net-http//lib/net/http/generic_request.rb#72
  def path; end

  # source://net-http//lib/net/http/generic_request.rb#120
  def request_body_permitted?; end

  # source://net-http//lib/net/http/generic_request.rb#129
  def response_body_permitted?; end

  # source://net-http//lib/net/http/generic_request.rb#186
  def set_body_internal(str); end

  # source://net-http//lib/net/http/generic_request.rb#210
  def update_uri(addr, port, ssl); end

  # source://net-http//lib/net/http/generic_request.rb#80
  def uri; end

  private

  # source://net-http//lib/net/http/generic_request.rb#312
  def encode_multipart_form_data(out, params, opt); end

  # source://net-http//lib/net/http/generic_request.rb#368
  def flush_buffer(out, buf, chunked_p); end

  # source://net-http//lib/net/http/generic_request.rb#363
  def quote_string(str, charset); end

  # source://net-http//lib/net/http/generic_request.rb#260
  def send_request_with_body(sock, ver, path, body); end

  # source://net-http//lib/net/http/generic_request.rb#286
  def send_request_with_body_data(sock, ver, path, params); end

  # source://net-http//lib/net/http/generic_request.rb#269
  def send_request_with_body_stream(sock, ver, path, f); end

  # source://net-http//lib/net/http/generic_request.rb#376
  def supply_default_content_type; end

  # source://net-http//lib/net/http/generic_request.rb#386
  def wait_for_continue(sock, ver); end

  # source://net-http//lib/net/http/generic_request.rb#399
  def write_header(sock, ver, path); end
end

# source://net-http//lib/net/http/generic_request.rb#242
class Net::HTTPGenericRequest::Chunker
  # source://net-http//lib/net/http/generic_request.rb#243
  def initialize(sock); end

  # source://net-http//lib/net/http/generic_request.rb#255
  def finish; end

  # source://net-http//lib/net/http/generic_request.rb#248
  def write(buf); end
end

# source://net-http//lib/net/http/header.rb#181
module Net::HTTPHeader
  # source://net-http//lib/net/http/header.rb#224
  def [](key); end

  # source://net-http//lib/net/http/header.rb#240
  def []=(key, val); end

  # source://net-http//lib/net/http/header.rb#261
  def add_field(key, val); end

  # source://net-http//lib/net/http/header.rb#945
  def basic_auth(account, password); end

  # source://net-http//lib/net/http/header.rb#484
  def canonical_each; end

  # source://net-http//lib/net/http/header.rb#654
  def chunked?; end

  # source://net-http//lib/net/http/header.rb#966
  def connection_close?; end

  # source://net-http//lib/net/http/header.rb#974
  def connection_keep_alive?; end

  # source://net-http//lib/net/http/header.rb#616
  def content_length; end

  # source://net-http//lib/net/http/header.rb#637
  def content_length=(len); end

  # source://net-http//lib/net/http/header.rb#670
  def content_range; end

  # source://net-http//lib/net/http/header.rb#701
  def content_type; end

  # source://net-http//lib/net/http/header.rb#772
  def content_type=(type, params = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#453
  def delete(key); end

  # source://net-http//lib/net/http/header.rb#364
  def each; end

  # source://net-http//lib/net/http/header.rb#484
  def each_capitalized; end

  # source://net-http//lib/net/http/header.rb#417
  def each_capitalized_name; end

  # source://net-http//lib/net/http/header.rb#364
  def each_header; end

  # source://net-http//lib/net/http/header.rb#391
  def each_key(&block); end

  # source://net-http//lib/net/http/header.rb#391
  def each_name(&block); end

  # source://net-http//lib/net/http/header.rb#438
  def each_value; end

  # source://net-http//lib/net/http/header.rb#341
  def fetch(key, *args, &block); end

  # source://net-http//lib/net/http/header.rb#812
  def form_data=(params, sep = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#306
  def get_fields(key); end

  # source://net-http//lib/net/http/header.rb#185
  def initialize_http_header(initheader); end

  # source://net-http//lib/net/http/header.rb#463
  def key?(key); end

  # source://net-http//lib/net/http/header.rb#208
  def length; end

  # source://net-http//lib/net/http/header.rb#723
  def main_type; end

  # source://net-http//lib/net/http/header.rb#956
  def proxy_basic_auth(account, password); end

  # source://net-http//lib/net/http/header.rb#509
  def range; end

  # source://net-http//lib/net/http/header.rb#576
  def range=(r, e = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#687
  def range_length; end

  # source://net-http//lib/net/http/header.rb#772
  def set_content_type(type, params = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#924
  def set_form(params, enctype = T.unsafe(nil), formopt = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#812
  def set_form_data(params, sep = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#576
  def set_range(r, e = T.unsafe(nil)); end

  # source://net-http//lib/net/http/header.rb#208
  def size; end

  # source://net-http//lib/net/http/header.rb#738
  def sub_type; end

  # source://net-http//lib/net/http/header.rb#477
  def to_hash; end

  # source://net-http//lib/net/http/header.rb#753
  def type_params; end

  private

  # source://net-http//lib/net/http/header.rb#285
  def append_field_value(ary, val); end

  # source://net-http//lib/net/http/header.rb#960
  def basic_encode(account, password); end

  # source://net-http//lib/net/http/header.rb#493
  def capitalize(name); end

  # source://net-http//lib/net/http/header.rb#270
  def set_field(key, val); end
end

# source://net-http//lib/net/http/header.rb#183
Net::HTTPHeader::MAX_FIELD_LENGTH = T.let(T.unsafe(nil), Integer)

# source://net-http//lib/net/http/header.rb#182
Net::HTTPHeader::MAX_KEY_LENGTH = T.let(T.unsafe(nil), Integer)

# source://net-http//lib/net/http/responses.rb#23
Net::HTTPInformation::EXCEPTION_TYPE = Net::HTTPError

# source://net-http//lib/net/http/responses.rb#1061
class Net::HTTPLoopDetected < ::Net::HTTPServerError; end

# source://net-http//lib/net/http/responses.rb#1062
Net::HTTPLoopDetected::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#776
class Net::HTTPMisdirectedRequest < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#777
Net::HTTPMisdirectedRequest::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#378
Net::HTTPMovedTemporarily = Net::HTTPFound

# source://net-http//lib/net/http/responses.rb#343
Net::HTTPMultipleChoice = Net::HTTPMultipleChoices

# source://net-http//lib/net/http/responses.rb#1078
class Net::HTTPNotExtended < ::Net::HTTPServerError; end

# source://net-http//lib/net/http/responses.rb#1079
Net::HTTPNotExtended::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#688
class Net::HTTPPayloadTooLarge < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#689
Net::HTTPPayloadTooLarge::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#129
class Net::HTTPProcessing < ::Net::HTTPInformation; end

# source://net-http//lib/net/http/responses.rb#130
Net::HTTPProcessing::HAS_BODY = T.let(T.unsafe(nil), FalseClass)

# source://net-http//lib/net/http/responses.rb#739
class Net::HTTPRangeNotSatisfiable < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#740
Net::HTTPRangeNotSatisfiable::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#53
Net::HTTPRedirection::EXCEPTION_TYPE = Net::HTTPRetriableError

# source://net-http//lib/net/http/request.rb#75
class Net::HTTPRequest < ::Net::HTTPGenericRequest
  # source://net-http//lib/net/http/request.rb#82
  def initialize(path, initheader = T.unsafe(nil)); end
end

# source://net-http//lib/net/http/responses.rb#709
Net::HTTPRequestURITooLarge = Net::HTTPURITooLong

# source://net-http//lib/net/http/response.rb#135
class Net::HTTPResponse
  include ::Net::HTTPHeader

  # source://net-http//lib/net/http/response.rb#194
  def initialize(httpv, code, msg); end

  # source://net-http//lib/net/http/response.rb#400
  def body; end

  # source://net-http//lib/net/http/response.rb#405
  def body=(value); end

  # source://net-http//lib/net/http/response.rb#229
  def body_encoding; end

  # source://net-http//lib/net/http/response.rb#253
  def body_encoding=(value); end

  # source://net-http//lib/net/http/response.rb#213
  def code; end

  # source://net-http//lib/net/http/response.rb#270
  def code_type; end

  # source://net-http//lib/net/http/response.rb#225
  def decode_content; end

  # source://net-http//lib/net/http/response.rb#225
  def decode_content=(_arg0); end

  # source://net-http//lib/net/http/response.rb#400
  def entity; end

  # source://net-http//lib/net/http/response.rb#274
  def error!; end

  # source://net-http//lib/net/http/response.rb#280
  def error_type; end

  # source://net-http//lib/net/http/response.rb#302
  def header; end

  # source://net-http//lib/net/http/response.rb#208
  def http_version; end

  # source://net-http//lib/net/http/response.rb#260
  def ignore_eof; end

  # source://net-http//lib/net/http/response.rb#260
  def ignore_eof=(_arg0); end

  # source://net-http//lib/net/http/response.rb#262
  def inspect; end

  # source://net-http//lib/net/http/response.rb#216
  def message; end

  # source://net-http//lib/net/http/response.rb#216
  def msg; end

  # source://net-http//lib/net/http/response.rb#355
  def read_body(dest = T.unsafe(nil), &block); end

  # source://net-http//lib/net/http/response.rb#307
  def read_header; end

  # source://net-http//lib/net/http/response.rb#316
  def reading_body(sock, reqmethodallowbody); end

  # source://net-http//lib/net/http/response.rb#297
  def response; end

  # source://net-http//lib/net/http/response.rb#221
  def uri; end

  # source://net-http//lib/net/http/response.rb#289
  def uri=(uri); end

  # source://net-http//lib/net/http/response.rb#285
  def value; end

  private

  # source://net-http//lib/net/http/response.rb#450
  def check_bom(str); end

  # source://net-http//lib/net/http/response.rb#414
  def detect_encoding(str, encoding = T.unsafe(nil)); end

  # source://net-http//lib/net/http/response.rb#540
  def extracting_encodings_from_meta_elements(value); end

  # source://net-http//lib/net/http/response.rb#505
  def get_attribute(ss); end

  # source://net-http//lib/net/http/response.rb#557
  def inflater; end

  # source://net-http//lib/net/http/response.rb#646
  def procdest(dest, block); end

  # source://net-http//lib/net/http/response.rb#592
  def read_body_0(dest); end

  # source://net-http//lib/net/http/response.rb#622
  def read_chunked(dest, chunk_data_io); end

  # source://net-http//lib/net/http/response.rb#464
  def scanning_meta(str); end

  # source://net-http//lib/net/http/response.rb#434
  def sniff_encoding(str, encoding = T.unsafe(nil)); end

  # source://net-http//lib/net/http/response.rb#642
  def stream_check; end

  class << self
    # source://net-http//lib/net/http/response.rb#138
    def body_permitted?; end

    # source://net-http//lib/net/http/response.rb#142
    def exception_type; end

    # source://net-http//lib/net/http/response.rb#146
    def read_new(sock); end

    private

    # source://net-http//lib/net/http/response.rb#170
    def each_response_header(sock); end

    # source://net-http//lib/net/http/response.rb#157
    def read_status_line(sock); end

    # source://net-http//lib/net/http/response.rb#164
    def response_class(code); end
  end
end

# source://net-http//lib/net/http/response.rb#660
class Net::HTTPResponse::Inflater
  # source://net-http//lib/net/http/response.rb#665
  def initialize(socket); end

  # source://net-http//lib/net/http/response.rb#683
  def bytes_inflated; end

  # source://net-http//lib/net/http/response.rb#674
  def finish; end

  # source://net-http//lib/net/http/response.rb#693
  def inflate_adapter(dest); end

  # source://net-http//lib/net/http/response.rb#720
  def read(clen, dest, ignore_eof = T.unsafe(nil)); end

  # source://net-http//lib/net/http/response.rb#729
  def read_all(dest); end
end

# source://net-http//lib/net/http/exceptions.rb#19
class Net::HTTPRetriableError < ::Net::ProtoRetriableError
  include ::Net::HTTPExceptions
end

# source://net-http//lib/net/http/responses.rb#81
Net::HTTPServerError::EXCEPTION_TYPE = Net::HTTPFatalError

# source://net-http//lib/net/http.rb#2565
Net::HTTPSession = Net::HTTP

# source://net-http//lib/net/http/responses.rb#38
Net::HTTPSuccess::EXCEPTION_TYPE = Net::HTTPError

# source://net-http//lib/net/http/responses.rb#705
class Net::HTTPURITooLong < ::Net::HTTPClientError; end

# source://net-http//lib/net/http/responses.rb#706
Net::HTTPURITooLong::HAS_BODY = T.let(T.unsafe(nil), TrueClass)

# source://net-http//lib/net/http/responses.rb#9
Net::HTTPUnknownResponse::EXCEPTION_TYPE = Net::HTTPError

# source://net-http//lib/net/http/responses.rb#1029
class Net::HTTPVariantAlsoNegotiates < ::Net::HTTPServerError; end

# source://net-http//lib/net/http/responses.rb#1030
Net::HTTPVariantAlsoNegotiates::HAS_BODY = T.let(T.unsafe(nil), TrueClass)
