# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `thread_safe` gem.
# Please instead update this file by running `bin/tapioca gem thread_safe`.


# source://thread_safe//lib/thread_safe/synchronized_delegator.rb#18
class SynchronizedDelegator < ::SimpleDelegator
  # source://thread_safe//lib/thread_safe/synchronized_delegator.rb#28
  def initialize(obj); end

  # source://thread_safe//lib/thread_safe/synchronized_delegator.rb#33
  def method_missing(method, *args, &block); end

  # source://thread_safe//lib/thread_safe/synchronized_delegator.rb#19
  def setup; end

  # source://thread_safe//lib/thread_safe/synchronized_delegator.rb#24
  def teardown; end
end

# source://thread_safe//lib/thread_safe/version.rb#1
module ThreadSafe; end

# source://thread_safe//lib/thread_safe.rb#34
ThreadSafe::Array = Array

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#180
class ThreadSafe::AtomicReferenceCacheBackend
  extend ::ThreadSafe::Util::Volatile

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#357
  def initialize(options = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#382
  def [](key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#390
  def []=(key, value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#529
  def clear; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#430
  def compute(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#395
  def compute_if_absent(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#418
  def compute_if_present(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#480
  def delete(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#484
  def delete_pair(key, value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#493
  def each_pair; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#524
  def empty?; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#460
  def get_and_set(key, value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#364
  def get_or_default(key, else_value = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#386
  def key?(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#440
  def merge_pair(key, value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#454
  def replace_if_exists(key, new_value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#450
  def replace_pair(key, old_value, new_value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#520
  def size; end

  private

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#678
  def attempt_compute(key, hash, current_table, i, node, node_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#708
  def attempt_get_and_set(key, value, hash, current_table, i, node, node_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#658
  def attempt_internal_compute_if_absent(key, hash, current_table, i, node, node_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#594
  def attempt_internal_replace(key, expected_old_value, hash, current_table, i, node, node_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#779
  def check_for_resize; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#904
  def decrement_size(by = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#617
  def find_value_in_node_list(node, key, hash, pure_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#900
  def increment_size; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#736
  def initialize_copy(other); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#761
  def initialize_table; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#633
  def internal_compute(key, &block); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#574
  def internal_replace(key, expected_old_value = T.unsafe(nil), &block); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#749
  def key_hash(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#847
  def lock_and_clean_up_reverse_forwarders(old_table, old_table_size, new_table, i, forwarder); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#801
  def rebuild(table); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#867
  def split_bin(new_table, i, node, node_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#860
  def split_old_bin(table, new_table, i, node, node_hash, forwarder); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#754
  def table_size_for(entry_count); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#744
  def try_await_lock(current_table, i, node); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#788
  def try_in_resize_lock(current_table, size_ctrl); end
end

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#339
ThreadSafe::AtomicReferenceCacheBackend::DEFAULT_CAPACITY = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#336
ThreadSafe::AtomicReferenceCacheBackend::HASH_BITS = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#334
ThreadSafe::AtomicReferenceCacheBackend::LOCKED = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#340
ThreadSafe::AtomicReferenceCacheBackend::MAX_CAPACITY = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#333
ThreadSafe::AtomicReferenceCacheBackend::MOVED = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#338
ThreadSafe::AtomicReferenceCacheBackend::NOW_RESIZING = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#226
class ThreadSafe::AtomicReferenceCacheBackend::Node
  include ::ThreadSafe::Util::CheapLockable
  extend ::ThreadSafe::Util::Volatile

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#243
  def initialize(hash, key, value, next_node = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#241
  def key; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#281
  def key?(key); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#303
  def locked?; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#285
  def matches?(key, hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#289
  def pure_hash; end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#260
  def try_await_lock(table, i); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#293
  def try_lock_via_hash(node_hash = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#307
  def unlock_via_hash(locked_hash, node_hash); end

  private

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#315
  def force_aquire_lock(table, i); end

  class << self
    # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#326
    def locked_hash?(hash); end
  end
end

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#237
ThreadSafe::AtomicReferenceCacheBackend::Node::HASH_BITS = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#235
ThreadSafe::AtomicReferenceCacheBackend::Node::LOCKED = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#234
ThreadSafe::AtomicReferenceCacheBackend::Node::MOVED = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#239
ThreadSafe::AtomicReferenceCacheBackend::Node::SPIN_LOCK_ATTEMPTS = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#236
ThreadSafe::AtomicReferenceCacheBackend::Node::WAITING = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#345
ThreadSafe::AtomicReferenceCacheBackend::TRANSFER_BUFFER_SIZE = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#181
class ThreadSafe::AtomicReferenceCacheBackend::Table < ::ThreadSafe::Util::PowerOfTwoTuple
  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#182
  def cas_new_node(i, hash, key, value); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#212
  def delete_node_at(i, node, predecessor_node); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#206
  def try_lock_via_hash(i, node, node_hash); end

  # source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#186
  def try_to_cas_in_computed(i, hash, key); end
end

# source://thread_safe//lib/thread_safe/atomic_reference_cache_backend.rb#335
ThreadSafe::AtomicReferenceCacheBackend::WAITING = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/cache.rb#23
class ThreadSafe::Cache < ::ThreadSafe::MriCacheBackend
  # source://thread_safe//lib/thread_safe/cache.rb#24
  def initialize(options = T.unsafe(nil), &block); end

  # source://thread_safe//lib/thread_safe/cache.rb#35
  def [](key); end

  # source://thread_safe//lib/thread_safe/cache.rb#98
  def each_key; end

  # source://thread_safe//lib/thread_safe/cache.rb#102
  def each_value; end

  # source://thread_safe//lib/thread_safe/cache.rb#112
  def empty?; end

  # source://thread_safe//lib/thread_safe/cache.rb#52
  def fetch(key, default_value = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/cache.rb#64
  def fetch_or_store(key, default_value = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/cache.rb#35
  def get(key); end

  # source://thread_safe//lib/thread_safe/cache.rb#106
  def key(value); end

  # source://thread_safe//lib/thread_safe/cache.rb#86
  def keys; end

  # source://thread_safe//lib/thread_safe/cache.rb#123
  def marshal_dump; end

  # source://thread_safe//lib/thread_safe/cache.rb#130
  def marshal_load(hash); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#12
  def put(key, value); end

  # source://thread_safe//lib/thread_safe/cache.rb#70
  def put_if_absent(key, value); end

  # source://thread_safe//lib/thread_safe/cache.rb#92
  def values; end

  private

  # source://thread_safe//lib/thread_safe/cache.rb#142
  def initialize_copy(other); end

  # source://thread_safe//lib/thread_safe/cache.rb#147
  def populate_from(hash); end

  # source://thread_safe//lib/thread_safe/cache.rb#138
  def raise_fetch_no_key; end

  # source://thread_safe//lib/thread_safe/cache.rb#152
  def validate_options_hash!(options); end
end

# source://thread_safe//lib/thread_safe/cache.rb#10
ThreadSafe::ConcurrentCacheBackend = ThreadSafe::MriCacheBackend

# source://thread_safe//lib/thread_safe.rb#35
ThreadSafe::Hash = Hash

# source://thread_safe//lib/thread_safe/mri_cache_backend.rb#2
class ThreadSafe::MriCacheBackend < ::ThreadSafe::NonConcurrentCacheBackend
  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#12
  def []=(key, value); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#56
  def clear; end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#28
  def compute(key); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#16
  def compute_if_absent(key); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#24
  def compute_if_present(key); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#48
  def delete(key); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#52
  def delete_pair(key, value); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#44
  def get_and_set(key, value); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#32
  def merge_pair(key, value); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#40
  def replace_if_exists(key, new_value); end

  # source://thread_safe//lib/thread_safe/mri_cache_backend.rb#36
  def replace_pair(key, old_value, new_value); end
end

# source://thread_safe//lib/thread_safe/mri_cache_backend.rb#10
ThreadSafe::MriCacheBackend::WRITE_LOCK = T.let(T.unsafe(nil), Thread::Mutex)

# source://thread_safe//lib/thread_safe.rb#9
ThreadSafe::NULL = T.let(T.unsafe(nil), Object)

# source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#2
class ThreadSafe::NonConcurrentCacheBackend
  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#7
  def initialize(options = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#11
  def [](key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#15
  def []=(key, value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#88
  def clear; end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#49
  def compute(key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#19
  def compute_if_absent(key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#43
  def compute_if_present(key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#75
  def delete(key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#79
  def delete_pair(key, value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#93
  def each_pair; end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#61
  def get_and_set(key, value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#104
  def get_or_default(key, default_value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#67
  def key?(key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#53
  def merge_pair(key, value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#36
  def replace_if_exists(key, new_value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#27
  def replace_pair(key, old_value, new_value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#100
  def size; end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#71
  def value?(value); end

  private

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#11
  def _get(key); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#15
  def _set(key, value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#118
  def dupped_backend; end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#112
  def initialize_copy(other); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#122
  def pair?(key, expected_value); end

  # source://thread_safe//lib/thread_safe/non_concurrent_cache_backend.rb#126
  def store_computed_value(key, new_value); end
end

# source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#2
class ThreadSafe::SynchronizedCacheBackend < ::ThreadSafe::NonConcurrentCacheBackend
  include ::Mutex_m

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#8
  def [](key); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#12
  def []=(key, value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#60
  def clear; end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#24
  def compute(key); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#16
  def compute_if_absent(key); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#20
  def compute_if_present(key); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#52
  def delete(key); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#56
  def delete_pair(key, value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#40
  def get_and_set(key, value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#68
  def get_or_default(key, default_value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#44
  def key?(key); end

  # source://mutex_m/0.1.2/mutex_m.rb#93
  def lock; end

  # source://mutex_m/0.1.2/mutex_m.rb#83
  def locked?; end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#28
  def merge_pair(key, value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#36
  def replace_if_exists(key, new_value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#32
  def replace_pair(key, old_value, new_value); end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#64
  def size; end

  # source://mutex_m/0.1.2/mutex_m.rb#78
  def synchronize(&block); end

  # source://mutex_m/0.1.2/mutex_m.rb#88
  def try_lock; end

  # source://mutex_m/0.1.2/mutex_m.rb#98
  def unlock; end

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#48
  def value?(value); end

  private

  # source://thread_safe//lib/thread_safe/synchronized_cache_backend.rb#73
  def dupped_backend; end
end

# source://thread_safe//lib/thread_safe/util.rb#2
module ThreadSafe::Util; end

# source://thread_safe//lib/thread_safe/util/adder.rb#22
class ThreadSafe::Util::Adder < ::ThreadSafe::Util::Striped64
  # source://thread_safe//lib/thread_safe/util/adder.rb#24
  def add(x); end

  # source://thread_safe//lib/thread_safe/util/adder.rb#38
  def decrement; end

  # source://thread_safe//lib/thread_safe/util/adder.rb#34
  def increment; end

  # source://thread_safe//lib/thread_safe/util/adder.rb#57
  def reset; end

  # source://thread_safe//lib/thread_safe/util/adder.rb#47
  def sum; end
end

# source://thread_safe//lib/thread_safe/util/atomic_reference.rb#3
ThreadSafe::Util::AtomicReference = ThreadSafe::Util::FullLockingAtomicReference

# source://thread_safe//lib/thread_safe/util.rb#5
ThreadSafe::Util::CPU_COUNT = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/util/cheap_lockable.rb#22
module ThreadSafe::Util::CheapLockable
  extend ::ThreadSafe::Util::Volatile

  private

  # source://thread_safe//lib/thread_safe/util/cheap_lockable.rb#98
  def cheap_broadcast; end

  # source://thread_safe//lib/thread_safe/util/cheap_lockable.rb#84
  def cheap_synchronize; end

  # source://thread_safe//lib/thread_safe/util/cheap_lockable.rb#91
  def cheap_wait; end
end

# source://thread_safe//lib/thread_safe/util.rb#3
ThreadSafe::Util::FIXNUM_BIT_SIZE = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/util/atomic_reference.rb#12
class ThreadSafe::Util::FullLockingAtomicReference
  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#13
  def initialize(value = T.unsafe(nil)); end

  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#28
  def compare_and_set(old_value, new_value); end

  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#18
  def get; end

  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#23
  def set(new_value); end

  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#18
  def value; end

  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#23
  def value=(new_value); end
end

# source://thread_safe//lib/thread_safe/util.rb#4
ThreadSafe::Util::MAX_INT = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/util/power_of_two_tuple.rb#3
class ThreadSafe::Util::PowerOfTwoTuple < ::ThreadSafe::Util::VolatileTuple
  # source://thread_safe//lib/thread_safe/util/power_of_two_tuple.rb#4
  def initialize(size); end

  # source://thread_safe//lib/thread_safe/util/power_of_two_tuple.rb#9
  def hash_to_index(hash); end

  # source://thread_safe//lib/thread_safe/util/power_of_two_tuple.rb#21
  def next_in_size_table; end

  # source://thread_safe//lib/thread_safe/util/power_of_two_tuple.rb#13
  def volatile_get_by_hash(hash); end

  # source://thread_safe//lib/thread_safe/util/power_of_two_tuple.rb#17
  def volatile_set_by_hash(hash, value); end
end

# source://thread_safe//lib/thread_safe/util/striped64.rb#64
class ThreadSafe::Util::Striped64
  extend ::ThreadSafe::Util::Volatile

  # source://thread_safe//lib/thread_safe/util/striped64.rb#89
  def initialize; end

  # source://thread_safe//lib/thread_safe/util/volatile.rb#44
  def busy?; end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#108
  def retry_update(x, hash_code, was_uncontended); end

  private

  # source://thread_safe//lib/thread_safe/util/striped64.rb#172
  def cas_base_computed; end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#192
  def expand_table_unless_stale(current_cells); end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#176
  def free?; end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#153
  def hash_code; end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#157
  def hash_code=(hash); end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#162
  def internal_reset(initial_value); end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#211
  def try_in_busy; end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#180
  def try_initialize_cells(x, hash); end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#202
  def try_to_install_new_cell(new_cell, hash); end
end

# source://thread_safe//lib/thread_safe/util/striped64.rb#71
class ThreadSafe::Util::Striped64::Cell < ::ThreadSafe::Util::FullLockingAtomicReference
  # source://thread_safe//lib/thread_safe/util/atomic_reference.rb#28
  def cas(old_value, new_value); end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#77
  def cas_computed; end

  # source://thread_safe//lib/thread_safe/util/striped64.rb#73
  def padding_; end
end

# source://thread_safe//lib/thread_safe/util/striped64.rb#149
ThreadSafe::Util::Striped64::THREAD_LOCAL_KEY = T.let(T.unsafe(nil), Symbol)

# source://thread_safe//lib/thread_safe/util/volatile.rb#3
module ThreadSafe::Util::Volatile
  # source://thread_safe//lib/thread_safe/util/volatile.rb#23
  def attr_volatile(*attr_names); end
end

# source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#10
class ThreadSafe::Util::VolatileTuple
  include ::Enumerable

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#15
  def initialize(size); end

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#32
  def cas(i, old_value, new_value); end

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#32
  def compare_and_set(i, old_value, new_value); end

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#41
  def each; end

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#37
  def size; end

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#24
  def volatile_get(i); end

  # source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#28
  def volatile_set(i, value); end
end

# source://thread_safe//lib/thread_safe/util/volatile_tuple.rb#13
ThreadSafe::Util::VolatileTuple::Tuple = Array

# source://thread_safe//lib/thread_safe/util/xor_shift_random.rb#14
module ThreadSafe::Util::XorShiftRandom
  extend ::ThreadSafe::Util::XorShiftRandom

  # source://thread_safe//lib/thread_safe/util/xor_shift_random.rb#19
  def get; end

  # source://thread_safe//lib/thread_safe/util/xor_shift_random.rb#33
  def xorshift(x); end
end

# source://thread_safe//lib/thread_safe/util/xor_shift_random.rb#16
ThreadSafe::Util::XorShiftRandom::MAX_XOR_SHIFTABLE_INT = T.let(T.unsafe(nil), Integer)

# source://thread_safe//lib/thread_safe/version.rb#2
ThreadSafe::VERSION = T.let(T.unsafe(nil), String)

# source://thread_safe//lib/thread_safe/version.rb#7
module Threadsafe
  class << self
    # source://thread_safe//lib/thread_safe/version.rb#10
    def const_missing(name); end
  end
end
