# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `timeout` gem.
# Please instead update this file by running `bin/tapioca gem timeout`.


# source://timeout//lib/timeout.rb#21
module Timeout
  private

  # source://timeout//lib/timeout.rb#308
  def timeout(*args, &block); end

  class << self
    # source://timeout//lib/timeout.rb#278
    def timeout(sec, klass = T.unsafe(nil), message = T.unsafe(nil), &block); end
  end
end

# source://timeout//lib/timeout.rb#33
class Timeout::Error < ::RuntimeError
  class << self
    # source://timeout//lib/timeout.rb#34
    def handle_timeout(message); end
  end
end

# source://timeout//lib/timeout.rb#26
class Timeout::ExitException < ::Exception
  # source://timeout//lib/timeout.rb#27
  def exception(*_arg0); end
end

# source://timeout//lib/timeout.rb#49
Timeout::GET_TIME = T.let(T.unsafe(nil), Method)

# source://timeout//lib/timeout.rb#143
class Timeout::Request
  # source://timeout//lib/timeout.rb#146
  def initialize(thread, timeout, exception_class, message); end

  # source://timeout//lib/timeout.rb#144
  def deadline; end

  # source://timeout//lib/timeout.rb#157
  def done?; end

  # source://timeout//lib/timeout.rb#163
  def expired?(now); end

  # source://timeout//lib/timeout.rb#177
  def finished; end

  # source://timeout//lib/timeout.rb#168
  def interrupt; end
end

# source://timeout//lib/timeout.rb#56
class Timeout::State
  # source://timeout//lib/timeout.rb#57
  def initialize; end

  # source://timeout//lib/timeout.rb#134
  def add_request(request); end

  # source://timeout//lib/timeout.rb#83
  def create_timeout_thread; end

  # source://timeout//lib/timeout.rb#120
  def ensure_timeout_thread_created; end

  class << self
    # source://timeout//lib/timeout.rb#78
    def instance; end
  end
end

# source://timeout//lib/timeout.rb#76
Timeout::State::GLOBAL_STATE = T.let(T.unsafe(nil), Timeout::State)

# source://timeout//lib/timeout.rb#185
module Timeout::Sync
  class << self
    # source://timeout//lib/timeout.rb#188
    def synchronize(mutex, &block); end
  end
end

# source://timeout//lib/timeout.rb#23
Timeout::VERSION = T.let(T.unsafe(nil), String)
