# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `abstract_type` gem.
# Please instead update this file by running `bin/tapioca gem abstract_type`.


# source://abstract_type//lib/abstract_type.rb#4
module AbstractType
  mixes_in_class_methods ::AbstractType::AbstractMethodDeclarations

  class << self
    private

    # source://abstract_type//lib/abstract_type.rb#32
    def create_new_method(abstract_class); end

    # source://abstract_type//lib/abstract_type.rb#14
    def included(descendant); end
  end
end

# source://abstract_type//lib/abstract_type.rb#44
module AbstractType::AbstractMethodDeclarations
  # source://abstract_type//lib/abstract_type.rb#61
  def abstract_method(*names); end

  # source://abstract_type//lib/abstract_type.rb#81
  def abstract_singleton_method(*names); end

  private

  # source://abstract_type//lib/abstract_type.rb#110
  def create_abstract_instance_method(name); end

  # source://abstract_type//lib/abstract_type.rb#96
  def create_abstract_singleton_method(name); end
end

# source://abstract_type//lib/abstract_type/version.rb#6
AbstractType::VERSION = T.let(T.unsafe(nil), String)
