# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `adamantium` gem.
# Please instead update this file by running `bin/tapioca gem adamantium`.


# source://adamantium//lib/adamantium.rb#7
module Adamantium
  include ::Memoizable

  mixes_in_class_methods ::Memoizable::ModuleMethods
  mixes_in_class_methods ::Adamantium::ModuleMethods
  mixes_in_class_methods ::Adamantium::ClassMethods

  # source://adamantium//lib/adamantium.rb#73
  def dup; end

  protected

  # source://adamantium//lib/adamantium.rb#84
  def transform(&block); end

  # source://adamantium//lib/adamantium.rb#97
  def transform_unless(condition, &block); end

  private

  def __adamantium_dup__; end

  class << self
    private

    # source://adamantium//lib/adamantium.rb#47
    def included(descendant); end
  end
end

# source://adamantium//lib/adamantium/class_methods.rb#6
module Adamantium::ClassMethods
  # source://adamantium//lib/adamantium/class_methods.rb#16
  def new(*_arg0); end
end

# source://adamantium//lib/adamantium.rb#10
module Adamantium::Flat
  include ::Memoizable
  include ::Adamantium

  mixes_in_class_methods ::Memoizable::ModuleMethods
  mixes_in_class_methods ::Adamantium::ModuleMethods
  mixes_in_class_methods ::Adamantium::ClassMethods

  # source://adamantium//lib/adamantium.rb#17
  def freezer; end

  class << self
    private

    # source://adamantium//lib/adamantium.rb#28
    def included(descendant); end
  end
end

# source://adamantium//lib/adamantium/freezer.rb#10
class Adamantium::Freezer
  class << self
    # source://adamantium//lib/adamantium/freezer.rb#111
    def get(name); end

    # source://adamantium//lib/adamantium/freezer.rb#130
    def parse(options); end

    private

    # source://adamantium//lib/adamantium/freezer.rb#29
    def call(object); end

    # source://adamantium//lib/adamantium/freezer.rb#49
    def freeze_value(value); end

    def new(*_arg0); end
  end
end

# source://adamantium//lib/adamantium/freezer.rb#73
class Adamantium::Freezer::Deep < ::Adamantium::Freezer
  class << self
    # source://adamantium//lib/adamantium/freezer.rb#29
    def call(object); end

    # source://adamantium//lib/adamantium/freezer.rb#82
    def freeze(value); end
  end
end

# source://adamantium//lib/adamantium/freezer.rb#56
class Adamantium::Freezer::Flat < ::Adamantium::Freezer
  class << self
    # source://adamantium//lib/adamantium/freezer.rb#29
    def call(object); end

    # source://adamantium//lib/adamantium/freezer.rb#65
    def freeze(value); end
  end
end

# source://adamantium//lib/adamantium/freezer.rb#89
Adamantium::Freezer::Noop = T.let(T.unsafe(nil), Proc)

# source://adamantium//lib/adamantium/freezer.rb#95
class Adamantium::Freezer::OptionError < ::RuntimeError; end

# source://adamantium//lib/adamantium/freezer.rb#92
class Adamantium::Freezer::UnknownFreezerError < ::RuntimeError; end

# source://adamantium//lib/adamantium/module_methods.rb#6
module Adamantium::ModuleMethods
  # source://adamantium//lib/adamantium/module_methods.rb#13
  def freezer; end

  # source://adamantium//lib/adamantium/module_methods.rb#28
  def memoize(*methods); end

  private

  # source://adamantium//lib/adamantium/module_methods.rb#45
  def included(descendant); end

  # source://adamantium//lib/adamantium/module_methods.rb#60
  def memoize_method(method_name, freezer); end
end

# source://adamantium//lib/adamantium/mutable.rb#16
module Adamantium::Mutable
  # source://adamantium//lib/adamantium/mutable.rb#32
  def freeze; end

  # source://adamantium//lib/adamantium/mutable.rb#50
  def frozen?; end
end

# source://adamantium//lib/adamantium/version.rb#6
Adamantium::VERSION = T.let(T.unsafe(nil), String)
