# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `anima` gem.
# Please instead update this file by running `bin/tapioca gem anima`.


# source://anima//lib/anima.rb#7
class Anima < ::Module
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat

  # source://anima//lib/anima.rb#18
  def initialize(*names); end

  # source://anima//lib/anima.rb#30
  def add(*names); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def attribute_names(&block); end

  # source://anima//lib/anima.rb#13
  def attributes; end

  # source://anima//lib/anima.rb#51
  def attributes_hash(object); end

  # source://anima//lib/anima.rb#72
  def initialize_instance(object, attribute_hash); end

  # source://anima//lib/anima.rb#42
  def remove(*names); end

  private

  # source://anima//lib/anima.rb#160
  def assert_known_attributes(klass, attribute_hash); end

  # source://anima//lib/anima.rb#133
  def included(descendant); end

  # source://anima//lib/anima.rb#176
  def new(attributes); end
end

# source://anima//lib/anima/attribute.rb#3
class Anima::Attribute
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat

  # source://anima//lib/anima/attribute.rb#9
  def initialize(name); end

  # source://anima//lib/anima/attribute.rb#38
  def get(object); end

  # source://anima//lib/anima/attribute.rb#21
  def instance_variable_name; end

  # source://anima//lib/anima/attribute.rb#29
  def load(object, attributes); end

  # source://anima//lib/anima/attribute.rb#16
  def name; end

  # source://anima//lib/anima/attribute.rb#48
  def set(object, value); end
end

# source://anima//lib/anima/error.rb#3
class Anima::Error < ::RuntimeError
  # source://anima//lib/anima/error.rb#15
  def initialize(klass, missing, unknown); end
end

# source://anima//lib/anima/error.rb#4
Anima::Error::FORMAT = T.let(T.unsafe(nil), String)

# source://anima//lib/anima.rb#81
module Anima::InstanceMethods
  # source://anima//lib/anima.rb#88
  def initialize(attributes); end

  # source://anima//lib/anima.rb#100
  def to_h; end

  # source://anima//lib/anima.rb#121
  def with(attributes); end
end
