# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `crass` gem.
# Please instead update this file by running `bin/tapioca gem crass`.


# source://crass//lib/crass/token-scanner.rb#3
module Crass
  class << self
    # source://crass//lib/crass.rb#22
    def parse(input, options = T.unsafe(nil)); end

    # source://crass//lib/crass.rb#30
    def parse_properties(input, options = T.unsafe(nil)); end
  end
end

# source://crass//lib/crass/parser.rb#10
class Crass::Parser
  # source://crass//lib/crass/parser.rb#140
  def initialize(input, options = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#153
  def consume_at_rule(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#200
  def consume_component_value(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#225
  def consume_declaration(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#292
  def consume_declarations(input = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#342
  def consume_function(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#383
  def consume_qualified_rule(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#424
  def consume_rules(flags = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#460
  def consume_simple_block(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#526
  def create_node(type, properties = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#534
  def create_selector(input); end

  # source://crass//lib/crass/parser.rb#542
  def create_style_rule(rule); end

  # source://crass//lib/crass/parser.rb#501
  def discard_block(input); end

  # source://crass//lib/crass/parser.rb#551
  def parse_component_value(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#578
  def parse_component_values(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#592
  def parse_declaration(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#620
  def parse_declarations(input = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#628
  def parse_properties(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#654
  def parse_rule(input = T.unsafe(nil)); end

  # source://crass//lib/crass/parser.rb#683
  def parse_value(nodes); end

  # source://crass//lib/crass/parser.rb#134
  def tokens; end

  class << self
    # source://crass//lib/crass/parser.rb#39
    def parse_properties(input, options = T.unsafe(nil)); end

    # source://crass//lib/crass/parser.rb#50
    def parse_rules(input, options = T.unsafe(nil)); end

    # source://crass//lib/crass/parser.rb#68
    def parse_stylesheet(input, options = T.unsafe(nil)); end

    # source://crass//lib/crass/parser.rb#88
    def stringify(nodes, options = T.unsafe(nil)); end
  end
end

# source://crass//lib/crass/parser.rb#11
Crass::Parser::BLOCK_END_TOKENS = T.let(T.unsafe(nil), Hash)

# source://crass//lib/crass/parser.rb#29
Crass::Parser::DEFAULT_MAXIMUM_DEPTH = T.let(T.unsafe(nil), Integer)

# source://crass//lib/crass/scanner.rb#8
class Crass::Scanner
  # source://crass//lib/crass/scanner.rb#29
  def initialize(input); end

  # source://crass//lib/crass/scanner.rb#38
  def consume; end

  # source://crass//lib/crass/scanner.rb#50
  def consume_rest; end

  # source://crass//lib/crass/scanner.rb#11
  def current; end

  # source://crass//lib/crass/scanner.rb#66
  def eos?; end

  # source://crass//lib/crass/scanner.rb#72
  def mark; end

  # source://crass//lib/crass/scanner.rb#79
  def marked; end

  # source://crass//lib/crass/scanner.rb#15
  def marker; end

  # source://crass//lib/crass/scanner.rb#15
  def marker=(_arg0); end

  # source://crass//lib/crass/scanner.rb#91
  def peek(length = T.unsafe(nil)); end

  # source://crass//lib/crass/scanner.rb#23
  def pos; end

  # source://crass//lib/crass/scanner.rb#23
  def pos=(_arg0); end

  # source://crass//lib/crass/scanner.rb#103
  def reconsume; end

  # source://crass//lib/crass/scanner.rb#109
  def reset; end

  # source://crass//lib/crass/scanner.rb#122
  def scan(pattern); end

  # source://crass//lib/crass/scanner.rb#134
  def scan_until(pattern); end

  # source://crass//lib/crass/scanner.rb#26
  def string; end
end

# source://crass//lib/crass/token-scanner.rb#6
class Crass::TokenScanner
  # source://crass//lib/crass/token-scanner.rb#9
  def initialize(tokens); end

  # source://crass//lib/crass/token-scanner.rb#16
  def collect; end

  # source://crass//lib/crass/token-scanner.rb#24
  def consume; end

  # source://crass//lib/crass/token-scanner.rb#7
  def current; end

  # source://crass//lib/crass/token-scanner.rb#32
  def peek; end

  # source://crass//lib/crass/token-scanner.rb#7
  def pos; end

  # source://crass//lib/crass/token-scanner.rb#39
  def reconsume; end

  # source://crass//lib/crass/token-scanner.rb#44
  def reset; end

  # source://crass//lib/crass/token-scanner.rb#7
  def tokens; end
end

# source://crass//lib/crass/tokenizer.rb#9
class Crass::Tokenizer
  # source://crass//lib/crass/tokenizer.rb#62
  def initialize(input, options = T.unsafe(nil)); end

  # source://crass//lib/crass/tokenizer.rb#70
  def consume; end

  # source://crass//lib/crass/tokenizer.rb#276
  def consume_bad_url; end

  # source://crass//lib/crass/tokenizer.rb#302
  def consume_comments; end

  # source://crass//lib/crass/tokenizer.rb#327
  def consume_escaped; end

  # source://crass//lib/crass/tokenizer.rb#351
  def consume_ident; end

  # source://crass//lib/crass/tokenizer.rb#376
  def consume_name; end

  # source://crass//lib/crass/tokenizer.rb#408
  def consume_number; end

  # source://crass//lib/crass/tokenizer.rb#431
  def consume_numeric; end

  # source://crass//lib/crass/tokenizer.rb#470
  def consume_string(ending = T.unsafe(nil)); end

  # source://crass//lib/crass/tokenizer.rb#511
  def consume_unicode_range; end

  # source://crass//lib/crass/tokenizer.rb#543
  def consume_url; end

  # source://crass//lib/crass/tokenizer.rb#591
  def convert_string_to_number(str); end

  # source://crass//lib/crass/tokenizer.rb#643
  def create_token(type, properties = T.unsafe(nil)); end

  # source://crass//lib/crass/tokenizer.rb#654
  def preprocess(input); end

  # source://crass//lib/crass/tokenizer.rb#669
  def start_identifier?(text = T.unsafe(nil)); end

  # source://crass//lib/crass/tokenizer.rb#693
  def start_number?(text = T.unsafe(nil)); end

  # source://crass//lib/crass/tokenizer.rb#712
  def tokenize; end

  # source://crass//lib/crass/tokenizer.rb#729
  def valid_escape?(text = T.unsafe(nil)); end

  class << self
    # source://crass//lib/crass/tokenizer.rb#45
    def tokenize(input, options = T.unsafe(nil)); end
  end
end

# source://crass//lib/crass/tokenizer.rb#10
Crass::Tokenizer::RE_COMMENT_CLOSE = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#11
Crass::Tokenizer::RE_DIGIT = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#12
Crass::Tokenizer::RE_ESCAPE = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#13
Crass::Tokenizer::RE_HEX = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#14
Crass::Tokenizer::RE_NAME = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#15
Crass::Tokenizer::RE_NAME_START = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#16
Crass::Tokenizer::RE_NON_PRINTABLE = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#17
Crass::Tokenizer::RE_NUMBER_DECIMAL = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#18
Crass::Tokenizer::RE_NUMBER_EXPONENT = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#19
Crass::Tokenizer::RE_NUMBER_SIGN = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#21
Crass::Tokenizer::RE_NUMBER_STR = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#33
Crass::Tokenizer::RE_QUOTED_URL_START = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#35
Crass::Tokenizer::RE_UNICODE_RANGE_END = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#34
Crass::Tokenizer::RE_UNICODE_RANGE_START = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#36
Crass::Tokenizer::RE_WHITESPACE = T.let(T.unsafe(nil), Regexp)

# source://crass//lib/crass/tokenizer.rb#37
Crass::Tokenizer::RE_WHITESPACE_ANCHORED = T.let(T.unsafe(nil), Regexp)
