# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `equalizer` gem.
# Please instead update this file by running `bin/tapioca gem equalizer`.


# source://equalizer//lib/equalizer.rb#4
class Equalizer < ::Module
  # source://equalizer//lib/equalizer.rb#15
  def initialize(*keys); end

  private

  # source://equalizer//lib/equalizer.rb#52
  def define_cmp_method; end

  # source://equalizer//lib/equalizer.rb#67
  def define_hash_method; end

  # source://equalizer//lib/equalizer.rb#79
  def define_inspect_method; end

  # source://equalizer//lib/equalizer.rb#41
  def define_methods; end

  # source://equalizer//lib/equalizer.rb#31
  def included(descendant); end
end

# source://equalizer//lib/equalizer.rb#89
module Equalizer::Methods
  # source://equalizer//lib/equalizer.rb#116
  def ==(other); end

  # source://equalizer//lib/equalizer.rb#101
  def eql?(other); end
end
