# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `factory_bot` gem.
# Please instead update this file by running `bin/tapioca gem factory_bot`.


# source://factory_bot//lib/factory_bot/internal.rb#1
module FactoryBot
  extend ::FactoryBot::Syntax::Methods
  extend ::FactoryBot::Syntax::Default

  class << self
    # source://factory_bot//lib/factory_bot/aliases.rb#3
    def aliases; end

    # source://factory_bot//lib/factory_bot/aliases.rb#3
    def aliases=(_arg0); end

    # source://factory_bot//lib/factory_bot/aliases.rb#11
    def aliases_for(attribute); end

    # source://factory_bot//lib/factory_bot.rb#58
    def automatically_define_enum_traits; end

    # source://factory_bot//lib/factory_bot.rb#58
    def automatically_define_enum_traits=(val); end

    # source://factory_bot//lib/factory_bot.rb#79
    def build_stubbed_starting_id=(starting_id); end

    # source://factory_bot//lib/factory_bot/find_definitions.rb#7
    def definition_file_paths; end

    # source://factory_bot//lib/factory_bot/find_definitions.rb#7
    def definition_file_paths=(_arg0); end

    # source://factory_bot//lib/factory_bot.rb#84
    def factories(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/find_definitions.rb#12
    def find_definitions; end

    # source://factory_bot//lib/factory_bot.rb#68
    def lint(*args); end

    # source://factory_bot//lib/factory_bot.rb#84
    def register_strategy(strategy_name, strategy_class, &_arg2); end

    # source://factory_bot//lib/factory_bot/reload.rb#2
    def reload; end

    # source://factory_bot//lib/factory_bot.rb#84
    def rewind_sequences(&_arg0); end

    # source://factory_bot//lib/factory_bot.rb#84
    def strategy_by_name(name, &_arg1); end

    # source://factory_bot//lib/factory_bot.rb#55
    def use_parent_strategy; end

    # source://factory_bot//lib/factory_bot.rb#55
    def use_parent_strategy=(val); end
  end
end

# source://factory_bot//lib/factory_bot/errors.rb#3
class FactoryBot::AssociationDefinitionError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/attribute/dynamic.rb#2
class FactoryBot::Attribute
  # source://factory_bot//lib/factory_bot/attribute.rb#10
  def initialize(name, ignored); end

  # source://factory_bot//lib/factory_bot/attribute.rb#23
  def alias_for?(attr); end

  # source://factory_bot//lib/factory_bot/attribute.rb#19
  def association?; end

  # source://factory_bot//lib/factory_bot/attribute.rb#8
  def ignored; end

  # source://factory_bot//lib/factory_bot/attribute.rb#8
  def name; end

  # source://factory_bot//lib/factory_bot/attribute.rb#15
  def to_proc; end
end

# source://factory_bot//lib/factory_bot/attribute/association.rb#4
class FactoryBot::Attribute::Association < ::FactoryBot::Attribute
  # source://factory_bot//lib/factory_bot/attribute/association.rb#7
  def initialize(name, factory, overrides); end

  # source://factory_bot//lib/factory_bot/attribute/association.rb#22
  def association?; end

  # source://factory_bot//lib/factory_bot/attribute/association.rb#5
  def factory; end

  # source://factory_bot//lib/factory_bot/attribute/association.rb#13
  def to_proc; end
end

# source://factory_bot//lib/factory_bot/attribute/dynamic.rb#4
class FactoryBot::Attribute::Dynamic < ::FactoryBot::Attribute
  # source://factory_bot//lib/factory_bot/attribute/dynamic.rb#5
  def initialize(name, ignored, block); end

  # source://factory_bot//lib/factory_bot/attribute/dynamic.rb#10
  def to_proc; end
end

# source://factory_bot//lib/factory_bot/attribute/sequence.rb#4
class FactoryBot::Attribute::Sequence < ::FactoryBot::Attribute
  # source://factory_bot//lib/factory_bot/attribute/sequence.rb#5
  def initialize(name, sequence, ignored); end

  # source://factory_bot//lib/factory_bot/attribute/sequence.rb#10
  def to_proc; end
end

# source://factory_bot//lib/factory_bot/attribute_assigner.rb#3
class FactoryBot::AttributeAssigner
  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#4
  def initialize(evaluator, build_class, &instance_builder); end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#22
  def hash; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#12
  def object; end

  private

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#98
  def alias_names_to_ignore; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#86
  def association_names; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#70
  def attribute_names_to_assign; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#66
  def attributes_to_set_on_hash; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#62
  def attributes_to_set_on_instance; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#50
  def build_class_instance; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#54
  def build_hash; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#39
  def decorated_evaluator; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#58
  def get(attribute_name); end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#94
  def hash_instance_methods_to_respond_to; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#106
  def ignorable_alias?(attribute, override); end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#82
  def ignored_attribute_names; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#32
  def method_tracking_evaluator; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#46
  def methods_invoked_on_evaluator; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#78
  def non_ignored_attribute_names; end

  # source://factory_bot//lib/factory_bot/attribute_assigner.rb#90
  def override_names; end
end

# source://factory_bot//lib/factory_bot/errors.rb#18
class FactoryBot::AttributeDefinitionError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/attribute_list.rb#3
class FactoryBot::AttributeList
  include ::Enumerable

  # source://factory_bot//lib/factory_bot/attribute_list.rb#6
  def initialize(name = T.unsafe(nil), attributes = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#38
  def apply_attributes(attributes_to_apply); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#26
  def associations; end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#11
  def define_attribute(attribute); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#18
  def each(&block); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#30
  def ignored; end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#22
  def names; end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#34
  def non_ignored; end

  private

  # source://factory_bot//lib/factory_bot/attribute_list.rb#44
  def add_attribute(attribute); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#62
  def attribute_defined?(attribute_name); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#49
  def ensure_attribute_not_defined!(attribute); end

  # source://factory_bot//lib/factory_bot/attribute_list.rb#55
  def ensure_attribute_not_self_referencing!(attribute); end
end

# source://factory_bot//lib/factory_bot/callback.rb#2
class FactoryBot::Callback
  # source://factory_bot//lib/factory_bot/callback.rb#5
  def initialize(name, block); end

  # source://factory_bot//lib/factory_bot/callback.rb#18
  def ==(other); end

  # source://factory_bot//lib/factory_bot/callback.rb#3
  def name; end

  # source://factory_bot//lib/factory_bot/callback.rb#10
  def run(instance, evaluator); end

  protected

  # source://factory_bot//lib/factory_bot/callback.rb#25
  def block; end

  private

  # source://factory_bot//lib/factory_bot/callback.rb#29
  def syntax_runner; end
end

# source://factory_bot//lib/factory_bot/callbacks_observer.rb#3
class FactoryBot::CallbacksObserver
  # source://factory_bot//lib/factory_bot/callbacks_observer.rb#4
  def initialize(callbacks, evaluator); end

  # source://factory_bot//lib/factory_bot/callbacks_observer.rb#9
  def update(name, result_instance); end

  private

  # source://factory_bot//lib/factory_bot/callbacks_observer.rb#17
  def callbacks_by_name(name); end
end

# source://factory_bot//lib/factory_bot/configuration.rb#3
class FactoryBot::Configuration
  # source://factory_bot//lib/factory_bot/configuration.rb#13
  def initialize; end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def after(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def before(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def callback(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#4
  def callback_names; end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def callbacks(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def constructor(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#4
  def factories; end

  # source://factory_bot//lib/factory_bot/configuration.rb#29
  def initialize_with(&block); end

  # source://factory_bot//lib/factory_bot/configuration.rb#4
  def inline_sequences; end

  # source://factory_bot//lib/factory_bot/configuration.rb#4
  def sequences; end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def skip_create(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#4
  def strategies; end

  # source://factory_bot//lib/factory_bot/configuration.rb#26
  def to_create(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/configuration.rb#4
  def traits; end
end

# source://factory_bot//lib/factory_bot/declaration/dynamic.rb#2
class FactoryBot::Declaration
  # source://factory_bot//lib/factory_bot/declaration.rb#10
  def initialize(name, ignored = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/declaration.rb#8
  def name; end

  # source://factory_bot//lib/factory_bot/declaration.rb#15
  def to_attributes; end

  protected

  # source://factory_bot//lib/factory_bot/declaration.rb#21
  def ignored; end
end

# source://factory_bot//lib/factory_bot/declaration/association.rb#4
class FactoryBot::Declaration::Association < ::FactoryBot::Declaration
  # source://factory_bot//lib/factory_bot/declaration/association.rb#5
  def initialize(name, *options); end

  # source://factory_bot//lib/factory_bot/declaration/association.rb#13
  def ==(other); end

  protected

  # source://factory_bot//lib/factory_bot/declaration/association.rb#21
  def options; end

  private

  # source://factory_bot//lib/factory_bot/declaration/association.rb#27
  def build; end

  # source://factory_bot//lib/factory_bot/declaration/association.rb#25
  def factory_name; end

  # source://factory_bot//lib/factory_bot/declaration/association.rb#25
  def overrides; end

  # source://factory_bot//lib/factory_bot/declaration/association.rb#39
  def raise_if_arguments_are_declarations!; end

  # source://factory_bot//lib/factory_bot/declaration/association.rb#25
  def traits; end
end

# source://factory_bot//lib/factory_bot/declaration/dynamic.rb#4
class FactoryBot::Declaration::Dynamic < ::FactoryBot::Declaration
  # source://factory_bot//lib/factory_bot/declaration/dynamic.rb#5
  def initialize(name, ignored = T.unsafe(nil), block = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/declaration/dynamic.rb#10
  def ==(other); end

  protected

  # source://factory_bot//lib/factory_bot/declaration/dynamic.rb#19
  def block; end

  private

  # source://factory_bot//lib/factory_bot/declaration/dynamic.rb#23
  def build; end
end

# source://factory_bot//lib/factory_bot/declaration/implicit.rb#4
class FactoryBot::Declaration::Implicit < ::FactoryBot::Declaration
  # source://factory_bot//lib/factory_bot/declaration/implicit.rb#5
  def initialize(name, factory = T.unsafe(nil), ignored = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/declaration/implicit.rb#10
  def ==(other); end

  protected

  # source://factory_bot//lib/factory_bot/declaration/implicit.rb#19
  def factory; end

  private

  # source://factory_bot//lib/factory_bot/declaration/implicit.rb#23
  def build; end
end

# source://factory_bot//lib/factory_bot/declaration_list.rb#3
class FactoryBot::DeclarationList
  include ::Enumerable

  # source://factory_bot//lib/factory_bot/declaration_list.rb#6
  def initialize(name = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/declaration_list.rb#23
  def attributes; end

  # source://factory_bot//lib/factory_bot/declaration_list.rb#12
  def declare_attribute(declaration); end

  # source://factory_bot//lib/factory_bot/declaration_list.rb#31
  def each(&block); end

  # source://factory_bot//lib/factory_bot/declaration_list.rb#19
  def overridable; end

  private

  # source://factory_bot//lib/factory_bot/declaration_list.rb#37
  def delete_declaration(declaration); end

  # source://factory_bot//lib/factory_bot/declaration_list.rb#45
  def overridable?; end

  # source://factory_bot//lib/factory_bot/declaration_list.rb#41
  def to_attributes; end
end

# source://factory_bot//lib/factory_bot/decorator.rb#2
class FactoryBot::Decorator < ::BasicObject
  # source://factory_bot//lib/factory_bot/decorator.rb#5
  def initialize(component); end

  # source://factory_bot//lib/factory_bot/decorator.rb#9
  def method_missing(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/decorator.rb#13
  def send(*_arg0, **_arg1, &_arg2); end

  private

  # source://factory_bot//lib/factory_bot/decorator.rb#17
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end

  class << self
    # source://factory_bot//lib/factory_bot/decorator.rb#21
    def const_missing(name); end
  end
end

# source://factory_bot//lib/factory_bot/decorator/attribute_hash.rb#3
class FactoryBot::Decorator::AttributeHash < ::FactoryBot::Decorator
  # source://factory_bot//lib/factory_bot/decorator/attribute_hash.rb#4
  def initialize(component, attributes = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/decorator/attribute_hash.rb#9
  def attributes; end
end

# source://factory_bot//lib/factory_bot/decorator/disallows_duplicates_registry.rb#3
class FactoryBot::Decorator::DisallowsDuplicatesRegistry < ::FactoryBot::Decorator
  # source://factory_bot//lib/factory_bot/decorator/disallows_duplicates_registry.rb#4
  def register(name, item); end
end

# source://factory_bot//lib/factory_bot/decorator/invocation_tracker.rb#3
class FactoryBot::Decorator::InvocationTracker < ::FactoryBot::Decorator
  # source://factory_bot//lib/factory_bot/decorator/invocation_tracker.rb#4
  def initialize(component); end

  # source://factory_bot//lib/factory_bot/decorator/invocation_tracker.rb#15
  def __invoked_methods__; end

  # source://factory_bot//lib/factory_bot/decorator/invocation_tracker.rb#9
  def method_missing(name, *args, **_arg2, &block); end
end

# source://factory_bot//lib/factory_bot/decorator/new_constructor.rb#3
class FactoryBot::Decorator::NewConstructor < ::FactoryBot::Decorator
  # source://factory_bot//lib/factory_bot/decorator/new_constructor.rb#4
  def initialize(component, build_class); end

  # source://factory_bot//lib/factory_bot/decorator/new_constructor.rb#9
  def new(*_arg0, **_arg1, &_arg2); end
end

# source://factory_bot//lib/factory_bot/definition.rb#3
class FactoryBot::Definition
  # source://factory_bot//lib/factory_bot/definition.rb#7
  def initialize(name, base_traits = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/definition.rb#86
  def add_callback(callback); end

  # source://factory_bot//lib/factory_bot/definition.rb#110
  def after(*names, &block); end

  # source://factory_bot//lib/factory_bot/definition.rb#82
  def append_traits(new_traits); end

  # source://factory_bot//lib/factory_bot/definition.rb#24
  def attributes; end

  # source://factory_bot//lib/factory_bot/definition.rb#106
  def before(*names, &block); end

  # source://factory_bot//lib/factory_bot/definition.rb#114
  def callback(*names, &block); end

  # source://factory_bot//lib/factory_bot/definition.rb#45
  def callbacks; end

  # source://factory_bot//lib/factory_bot/definition.rb#49
  def compile(klass = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/definition.rb#41
  def constructor; end

  # source://factory_bot//lib/factory_bot/definition.rb#4
  def declarations; end

  # source://factory_bot//lib/factory_bot/definition.rb#22
  def declare_attribute(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/definition.rb#102
  def define_constructor(&block); end

  # source://factory_bot//lib/factory_bot/definition.rb#94
  def define_trait(trait); end

  # source://factory_bot//lib/factory_bot/definition.rb#4
  def defined_traits; end

  # source://factory_bot//lib/factory_bot/definition.rb#78
  def inherit_traits(new_traits); end

  # source://factory_bot//lib/factory_bot/definition.rb#5
  def klass; end

  # source://factory_bot//lib/factory_bot/definition.rb#5
  def klass=(_arg0); end

  # source://factory_bot//lib/factory_bot/definition.rb#4
  def name; end

  # source://factory_bot//lib/factory_bot/definition.rb#73
  def overridable; end

  # source://factory_bot//lib/factory_bot/definition.rb#98
  def register_enum(enum); end

  # source://factory_bot//lib/factory_bot/definition.rb#4
  def registered_enums; end

  # source://factory_bot//lib/factory_bot/definition.rb#90
  def skip_create; end

  # source://factory_bot//lib/factory_bot/definition.rb#33
  def to_create(&block); end

  private

  # source://factory_bot//lib/factory_bot/definition.rb#151
  def additional_traits; end

  # source://factory_bot//lib/factory_bot/definition.rb#171
  def aggregate_from_traits_and_self(method_name, &block); end

  # source://factory_bot//lib/factory_bot/definition.rb#196
  def automatically_register_defined_enums(klass); end

  # source://factory_bot//lib/factory_bot/definition.rb#200
  def automatically_register_defined_enums?(klass); end

  # source://factory_bot//lib/factory_bot/definition.rb#122
  def base_traits; end

  # source://factory_bot//lib/factory_bot/definition.rb#131
  def error_with_definition_name(error); end

  # source://factory_bot//lib/factory_bot/definition.rb#181
  def expand_enum_traits(klass); end

  # source://factory_bot//lib/factory_bot/definition.rb#164
  def initialize_copy(source); end

  # source://factory_bot//lib/factory_bot/definition.rb#155
  def trait_by_name(name); end

  # source://factory_bot//lib/factory_bot/definition.rb#159
  def trait_for(name); end
end

# source://factory_bot//lib/factory_bot/definition_hierarchy.rb#2
class FactoryBot::DefinitionHierarchy
  # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#3
  def callbacks(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#3
  def constructor(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#3
  def to_create(*_arg0, **_arg1, &_arg2); end

  class << self
    # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#5
    def build_from_definition(definition); end

    private

    # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#11
    def add_callbacks(callbacks); end

    # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#20
    def build_constructor(&block); end

    # source://factory_bot//lib/factory_bot/definition_hierarchy.rb#29
    def build_to_create(&block); end
  end
end

# source://factory_bot//lib/factory_bot/definition_proxy.rb#2
class FactoryBot::DefinitionProxy
  # source://factory_bot//lib/factory_bot/definition_proxy.rb#26
  def initialize(definition, ignore = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#47
  def add_attribute(name, &block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#22
  def after(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#151
  def association(name, *options); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#22
  def before(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#22
  def callback(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#24
  def child_factories; end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#171
  def factory(name, options = T.unsafe(nil), &block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#237
  def initialize_with(&block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#91
  def method_missing(name, *args, &block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#122
  def sequence(name, *_arg1, **_arg2, &_arg3); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#32
  def singleton_method_added(name); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#167
  def skip_create; end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#163
  def to_create(&block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#175
  def trait(name, &block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#233
  def traits_for_enum(attribute_name, values = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#52
  def transient(&block); end

  private

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#243
  def __declare_attribute__(name, block); end

  # source://factory_bot//lib/factory_bot/definition_proxy.rb#252
  def __valid_association_options?(options); end
end

# source://factory_bot//lib/factory_bot/definition_proxy.rb#3
FactoryBot::DefinitionProxy::UNPROXIED_METHODS = T.let(T.unsafe(nil), Array)

# source://factory_bot//lib/factory_bot.rb#53
FactoryBot::Deprecation = T.let(T.unsafe(nil), ActiveSupport::Deprecation)

# source://factory_bot//lib/factory_bot/errors.rb#12
class FactoryBot::DuplicateDefinitionError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/enum.rb#3
class FactoryBot::Enum
  # source://factory_bot//lib/factory_bot/enum.rb#4
  def initialize(attribute_name, values = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/enum.rb#9
  def build_traits(klass); end

  private

  # source://factory_bot//lib/factory_bot/enum.rb#21
  def build_trait(trait_name, attribute_name, value); end

  # source://factory_bot//lib/factory_bot/enum.rb#17
  def enum_values(klass); end
end

# source://factory_bot//lib/factory_bot/evaluation.rb#2
class FactoryBot::Evaluation
  # source://factory_bot//lib/factory_bot/evaluation.rb#3
  def initialize(evaluator, attribute_assigner, to_create, observer); end

  # source://factory_bot//lib/factory_bot/evaluation.rb#12
  def create(result_instance); end

  # source://factory_bot//lib/factory_bot/evaluation.rb#10
  def hash(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/evaluation.rb#19
  def notify(name, result_instance); end

  # source://factory_bot//lib/factory_bot/evaluation.rb#10
  def object(*_arg0, **_arg1, &_arg2); end
end

# source://factory_bot//lib/factory_bot/evaluator.rb#6
class FactoryBot::Evaluator
  # source://factory_bot//lib/factory_bot/evaluator.rb#13
  def initialize(build_strategy, overrides = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/evaluator.rb#50
  def __override_names__; end

  # source://factory_bot//lib/factory_bot/evaluator.rb#24
  def association(factory_name, *traits_and_overrides); end

  # source://factory_bot//lib/factory_bot/evaluator.rb#7
  def attribute_lists; end

  # source://factory_bot//lib/factory_bot/evaluator.rb#7
  def attribute_lists=(_arg0); end

  # source://factory_bot//lib/factory_bot/evaluator.rb#7
  def attribute_lists?; end

  # source://factory_bot//lib/factory_bot/evaluator.rb#54
  def increment_sequence(sequence); end

  # source://factory_bot//lib/factory_bot/evaluator.rb#36
  def instance; end

  # source://factory_bot//lib/factory_bot/evaluator.rb#36
  def instance=(_arg0); end

  # source://factory_bot//lib/factory_bot/evaluator.rb#38
  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end

  private

  # source://factory_bot//lib/factory_bot/evaluator.rb#46
  def respond_to_missing?(method_name, _include_private = T.unsafe(nil)); end

  class << self
    # source://factory_bot//lib/factory_bot/evaluator.rb#58
    def attribute_list; end

    # source://factory_bot//lib/factory_bot/evaluator.rb#7
    def attribute_lists; end

    # source://factory_bot//lib/factory_bot/evaluator.rb#7
    def attribute_lists=(value); end

    # source://factory_bot//lib/factory_bot/evaluator.rb#7
    def attribute_lists?; end

    # source://factory_bot//lib/factory_bot/evaluator.rb#66
    def define_attribute(name, &block); end

    private

    # source://activesupport/8.0.1/lib/active_support/class_attribute.rb#15
    def __class_attr_attribute_lists; end

    # source://activesupport/8.0.1/lib/active_support/class_attribute.rb#17
    def __class_attr_attribute_lists=(new_value); end
  end
end

# source://factory_bot//lib/factory_bot/evaluator_class_definer.rb#3
class FactoryBot::EvaluatorClassDefiner
  # source://factory_bot//lib/factory_bot/evaluator_class_definer.rb#4
  def initialize(attributes, parent_class); end

  # source://factory_bot//lib/factory_bot/evaluator_class_definer.rb#13
  def evaluator_class; end
end

# source://factory_bot//lib/factory_bot/factory.rb#6
class FactoryBot::Factory
  # source://factory_bot//lib/factory_bot/factory.rb#9
  def initialize(name, options = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def add_callback(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def append_traits(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#52
  def associations; end

  # source://factory_bot//lib/factory_bot/factory.rb#22
  def build_class; end

  # source://factory_bot//lib/factory_bot/factory.rb#85
  def compile; end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def constructor(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def declare_attribute(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def define_trait(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def defined_traits(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#7
  def definition; end

  # source://factory_bot//lib/factory_bot/factory.rb#48
  def human_names; end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def inherit_traits(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#7
  def name; end

  # source://factory_bot//lib/factory_bot/factory.rb#81
  def names; end

  # source://factory_bot//lib/factory_bot/factory.rb#32
  def run(build_strategy, overrides, &block); end

  # source://factory_bot//lib/factory_bot/factory.rb#19
  def to_create(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/factory.rb#95
  def with_traits(traits); end

  protected

  # source://factory_bot//lib/factory_bot/factory.rb#111
  def attributes; end

  # source://factory_bot//lib/factory_bot/factory.rb#126
  def build_hierarchy; end

  # source://factory_bot//lib/factory_bot/factory.rb#130
  def callbacks; end

  # source://factory_bot//lib/factory_bot/factory.rb#103
  def class_name; end

  # source://factory_bot//lib/factory_bot/factory.rb#138
  def compiled_constructor; end

  # source://factory_bot//lib/factory_bot/factory.rb#134
  def compiled_to_create; end

  # source://factory_bot//lib/factory_bot/factory.rb#107
  def evaluator_class; end

  # source://factory_bot//lib/factory_bot/factory.rb#118
  def hierarchy_class; end

  # source://factory_bot//lib/factory_bot/factory.rb#122
  def hierarchy_instance; end

  private

  # source://factory_bot//lib/factory_bot/factory.rb#144
  def assert_valid_options(options); end

  # source://factory_bot//lib/factory_bot/factory.rb#156
  def initialize_copy(source); end

  # source://factory_bot//lib/factory_bot/factory.rb#148
  def parent; end
end

# source://factory_bot//lib/factory_bot/factory_runner.rb#2
class FactoryBot::FactoryRunner
  # source://factory_bot//lib/factory_bot/factory_runner.rb#3
  def initialize(name, strategy, traits_and_overrides); end

  # source://factory_bot//lib/factory_bot/factory_runner.rb#11
  def run(runner_strategy = T.unsafe(nil), &block); end
end

# source://factory_bot//lib/factory_bot/internal.rb#3
module FactoryBot::Internal
  class << self
    # source://factory_bot//lib/factory_bot/internal.rb#5
    def after(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def before(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def callbacks(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#19
    def configuration; end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def constructor(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def factories(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#69
    def factory_by_name(name); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def initialize_with(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def inline_sequences(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#82
    def register_default_strategies; end

    # source://factory_bot//lib/factory_bot/internal.rb#62
    def register_factory(factory); end

    # source://factory_bot//lib/factory_bot/internal.rb#27
    def register_inline_sequence(sequence); end

    # source://factory_bot//lib/factory_bot/internal.rb#46
    def register_sequence(sequence); end

    # source://factory_bot//lib/factory_bot/internal.rb#73
    def register_strategy(strategy_name, strategy_class); end

    # source://factory_bot//lib/factory_bot/internal.rb#35
    def register_trait(trait); end

    # source://factory_bot//lib/factory_bot/internal.rb#23
    def reset_configuration; end

    # source://factory_bot//lib/factory_bot/internal.rb#31
    def rewind_inline_sequences; end

    # source://factory_bot//lib/factory_bot/internal.rb#57
    def rewind_sequences; end

    # source://factory_bot//lib/factory_bot/internal.rb#53
    def sequence_by_name(name); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def sequences(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def skip_create(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def strategies(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#78
    def strategy_by_name(name); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def to_create(*_arg0, **_arg1, &_arg2); end

    # source://factory_bot//lib/factory_bot/internal.rb#42
    def trait_by_name(name, klass); end

    # source://factory_bot//lib/factory_bot/internal.rb#5
    def traits(*_arg0, **_arg1, &_arg2); end
  end
end

# source://factory_bot//lib/factory_bot/errors.rb#9
class FactoryBot::InvalidCallbackNameError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/errors.rb#27
class FactoryBot::InvalidFactoryError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/linter.rb#2
class FactoryBot::Linter
  # source://factory_bot//lib/factory_bot/linter.rb#3
  def initialize(factories, strategy: T.unsafe(nil), traits: T.unsafe(nil), verbose: T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/linter.rb#11
  def lint!; end

  private

  # source://factory_bot//lib/factory_bot/linter.rb#21
  def calculate_invalid_factories; end

  # source://factory_bot//lib/factory_bot/linter.rb#90
  def error_message; end

  # source://factory_bot//lib/factory_bot/linter.rb#102
  def error_message_type; end

  # source://factory_bot//lib/factory_bot/linter.rb#19
  def factories_to_lint; end

  # source://factory_bot//lib/factory_bot/linter.rb#19
  def factory_strategy; end

  # source://factory_bot//lib/factory_bot/linter.rb#19
  def invalid_factories; end

  # source://factory_bot//lib/factory_bot/linter.rb#62
  def lint(factory); end

  # source://factory_bot//lib/factory_bot/linter.rb#70
  def lint_factory(factory); end

  # source://factory_bot//lib/factory_bot/linter.rb#80
  def lint_traits(factory); end
end

# source://factory_bot//lib/factory_bot/linter.rb#28
class FactoryBot::Linter::FactoryError
  # source://factory_bot//lib/factory_bot/linter.rb#29
  def initialize(wrapped_error, factory); end

  # source://factory_bot//lib/factory_bot/linter.rb#46
  def location; end

  # source://factory_bot//lib/factory_bot/linter.rb#34
  def message; end

  # source://factory_bot//lib/factory_bot/linter.rb#39
  def verbose_message; end
end

# source://factory_bot//lib/factory_bot/linter.rb#51
class FactoryBot::Linter::FactoryTraitError < ::FactoryBot::Linter::FactoryError
  # source://factory_bot//lib/factory_bot/linter.rb#52
  def initialize(wrapped_error, factory, trait_name); end

  # source://factory_bot//lib/factory_bot/linter.rb#57
  def location; end
end

# source://factory_bot//lib/factory_bot/errors.rb#24
class FactoryBot::MethodDefinitionError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/null_factory.rb#3
class FactoryBot::NullFactory
  # source://factory_bot//lib/factory_bot/null_factory.rb#6
  def initialize; end

  # source://factory_bot//lib/factory_bot/null_factory.rb#10
  def attributes(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/null_factory.rb#10
  def callbacks(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/null_factory.rb#16
  def class_name; end

  # source://factory_bot//lib/factory_bot/null_factory.rb#13
  def compile; end

  # source://factory_bot//lib/factory_bot/null_factory.rb#10
  def constructor(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/null_factory.rb#10
  def defined_traits(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/null_factory.rb#4
  def definition; end

  # source://factory_bot//lib/factory_bot/null_factory.rb#19
  def evaluator_class; end

  # source://factory_bot//lib/factory_bot/null_factory.rb#23
  def hierarchy_class; end

  # source://factory_bot//lib/factory_bot/null_factory.rb#10
  def to_create(*_arg0, **_arg1, &_arg2); end
end

# source://factory_bot//lib/factory_bot/null_object.rb#3
class FactoryBot::NullObject < ::BasicObject
  # source://factory_bot//lib/factory_bot/null_object.rb#4
  def initialize(methods_to_respond_to); end

  # source://factory_bot//lib/factory_bot/null_object.rb#8
  def method_missing(name, *args, &block); end

  # source://factory_bot//lib/factory_bot/null_object.rb#16
  def respond_to?(method); end
end

# source://factory_bot//lib/factory_bot/registry.rb#4
class FactoryBot::Registry
  include ::Enumerable

  # source://factory_bot//lib/factory_bot/registry.rb#9
  def initialize(name); end

  # source://factory_bot//lib/factory_bot/registry.rb#22
  def [](name); end

  # source://factory_bot//lib/factory_bot/registry.rb#14
  def clear; end

  # source://factory_bot//lib/factory_bot/registry.rb#18
  def each(&block); end

  # source://factory_bot//lib/factory_bot/registry.rb#22
  def find(name); end

  # source://factory_bot//lib/factory_bot/registry.rb#7
  def name; end

  # source://factory_bot//lib/factory_bot/registry.rb#30
  def register(name, item); end

  # source://factory_bot//lib/factory_bot/registry.rb#34
  def registered?(name); end

  private

  # source://factory_bot//lib/factory_bot/registry.rb#40
  def key_error_with_custom_message(key_error); end

  # source://factory_bot//lib/factory_bot/registry.rb#50
  def new_key_error(message, key_error); end
end

# source://factory_bot//lib/factory_bot/sequence.rb#5
class FactoryBot::Sequence
  # source://factory_bot//lib/factory_bot/sequence.rb#8
  def initialize(name, *args, &proc); end

  # source://factory_bot//lib/factory_bot/sequence.rb#6
  def name; end

  # source://factory_bot//lib/factory_bot/sequence.rb#33
  def names; end

  # source://factory_bot//lib/factory_bot/sequence.rb#21
  def next(scope = T.unsafe(nil)); end

  # source://factory_bot//lib/factory_bot/sequence.rb#37
  def rewind; end

  private

  # source://factory_bot//lib/factory_bot/sequence.rb#47
  def increment_value; end

  # source://factory_bot//lib/factory_bot/sequence.rb#43
  def value; end
end

# source://factory_bot//lib/factory_bot/sequence.rb#51
class FactoryBot::Sequence::EnumeratorAdapter
  # source://factory_bot//lib/factory_bot/sequence.rb#52
  def initialize(value); end

  # source://factory_bot//lib/factory_bot/sequence.rb#61
  def next; end

  # source://factory_bot//lib/factory_bot/sequence.rb#57
  def peek; end

  # source://factory_bot//lib/factory_bot/sequence.rb#65
  def rewind; end
end

# source://factory_bot//lib/factory_bot/errors.rb#15
class FactoryBot::SequenceAbuseError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/strategy/build.rb#2
module FactoryBot::Strategy; end

# source://factory_bot//lib/factory_bot/strategy/attributes_for.rb#3
class FactoryBot::Strategy::AttributesFor
  # source://factory_bot//lib/factory_bot/strategy/attributes_for.rb#4
  def association(runner); end

  # source://factory_bot//lib/factory_bot/strategy/attributes_for.rb#8
  def result(evaluation); end

  # source://factory_bot//lib/factory_bot/strategy/attributes_for.rb#12
  def to_sym; end
end

# source://factory_bot//lib/factory_bot/strategy/build.rb#3
class FactoryBot::Strategy::Build
  # source://factory_bot//lib/factory_bot/strategy/build.rb#4
  def association(runner); end

  # source://factory_bot//lib/factory_bot/strategy/build.rb#8
  def result(evaluation); end

  # source://factory_bot//lib/factory_bot/strategy/build.rb#14
  def to_sym; end
end

# source://factory_bot//lib/factory_bot/strategy/create.rb#3
class FactoryBot::Strategy::Create
  # source://factory_bot//lib/factory_bot/strategy/create.rb#4
  def association(runner); end

  # source://factory_bot//lib/factory_bot/strategy/create.rb#8
  def result(evaluation); end

  # source://factory_bot//lib/factory_bot/strategy/create.rb#17
  def to_sym; end
end

# source://factory_bot//lib/factory_bot/strategy/null.rb#3
class FactoryBot::Strategy::Null
  # source://factory_bot//lib/factory_bot/strategy/null.rb#4
  def association(runner); end

  # source://factory_bot//lib/factory_bot/strategy/null.rb#7
  def result(evaluation); end

  # source://factory_bot//lib/factory_bot/strategy/null.rb#10
  def to_sym; end
end

# source://factory_bot//lib/factory_bot/strategy/stub.rb#3
class FactoryBot::Strategy::Stub
  # source://factory_bot//lib/factory_bot/strategy/stub.rb#31
  def association(runner); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#35
  def result(evaluation); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#44
  def to_sym; end

  private

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#98
  def clear_changes_information(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#85
  def has_settable_id?(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#114
  def missing_created_at?(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#120
  def missing_updated_at?(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#50
  def next_id(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#104
  def set_timestamps(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#58
  def stub_database_interaction_on_result(result_instance); end

  # source://factory_bot//lib/factory_bot/strategy/stub.rb#91
  def uuid_primary_key?(result_instance); end

  class << self
    # source://factory_bot//lib/factory_bot/strategy/stub.rb#27
    def next_id=(id); end
  end
end

# source://factory_bot//lib/factory_bot/strategy/stub.rb#6
FactoryBot::Strategy::Stub::DISABLED_PERSISTENCE_METHODS = T.let(T.unsafe(nil), Array)

# source://factory_bot//lib/factory_bot/strategy_calculator.rb#3
class FactoryBot::StrategyCalculator
  # source://factory_bot//lib/factory_bot/strategy_calculator.rb#4
  def initialize(name_or_object); end

  # source://factory_bot//lib/factory_bot/strategy_calculator.rb#8
  def strategy; end

  private

  # source://factory_bot//lib/factory_bot/strategy_calculator.rb#18
  def strategy_is_object?; end

  # source://factory_bot//lib/factory_bot/strategy_calculator.rb#22
  def strategy_name_to_object; end
end

# source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#3
class FactoryBot::StrategySyntaxMethodRegistrar
  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#4
  def initialize(strategy_name); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#8
  def define_strategy_methods; end

  private

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#32
  def define_list_strategy_method; end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#47
  def define_pair_strategy_method; end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#24
  def define_singular_strategy_method; end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#55
  def define_syntax_method(name, &block); end

  class << self
    # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#14
    def with_index(block, index); end
  end
end

# source://factory_bot//lib/factory_bot/syntax/methods.rb#2
module FactoryBot::Syntax; end

# source://factory_bot//lib/factory_bot/syntax/default.rb#3
module FactoryBot::Syntax::Default
  include ::FactoryBot::Syntax::Methods

  # source://factory_bot//lib/factory_bot/syntax/default.rb#6
  def define(&block); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#10
  def modify(&block); end
end

# source://factory_bot//lib/factory_bot/syntax/default.rb#14
class FactoryBot::Syntax::Default::DSL
  # source://factory_bot//lib/factory_bot/syntax/default.rb#40
  def after(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#40
  def before(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#40
  def callback(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#15
  def factory(name, options = T.unsafe(nil), &block); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#40
  def initialize_with(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#28
  def sequence(name, *_arg1, **_arg2, &_arg3); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#40
  def skip_create(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#40
  def to_create(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/syntax/default.rb#32
  def trait(name, &block); end

  class << self
    # source://factory_bot//lib/factory_bot/syntax/default.rb#36
    def run(block); end
  end
end

# source://factory_bot//lib/factory_bot/syntax/default.rb#49
class FactoryBot::Syntax::Default::ModifyDSL
  # source://factory_bot//lib/factory_bot/syntax/default.rb#50
  def factory(name, _options = T.unsafe(nil), &block); end

  class << self
    # source://factory_bot//lib/factory_bot/syntax/default.rb#56
    def run(block); end
  end
end

# source://factory_bot//lib/factory_bot/syntax/methods.rb#32
module FactoryBot::Syntax::Methods
  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def alchemrest_hash_for(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def alchemrest_hash_for_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def alchemrest_hash_for_pair(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def alchemrest_record_for(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def alchemrest_record_for_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def alchemrest_record_for_pair(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def attributes_for(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def attributes_for_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def attributes_for_pair(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def build(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def build_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def build_pair(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def build_stubbed(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def build_stubbed_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def build_stubbed_pair(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def create(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def create_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def create_pair(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/syntax/methods.rb#113
  def generate(name); end

  # source://factory_bot//lib/factory_bot/syntax/methods.rb#127
  def generate_list(name, count); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#27
  def null(name, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#35
  def null_list(name, amount, *traits_and_overrides, &block); end

  # source://factory_bot//lib/factory_bot/strategy_syntax_method_registrar.rb#50
  def null_pair(name, *traits_and_overrides, &block); end
end

# source://factory_bot//lib/factory_bot/syntax_runner.rb#3
class FactoryBot::SyntaxRunner
  include ::FactoryBot::Syntax::Methods
end

# source://factory_bot//lib/factory_bot/trait.rb#3
class FactoryBot::Trait
  # source://factory_bot//lib/factory_bot/trait.rb#6
  def initialize(name, &block); end

  # source://factory_bot//lib/factory_bot/trait.rb#24
  def ==(other); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def add_callback(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def attributes(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def callbacks(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def constructor(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def declare_attribute(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def define_trait(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#4
  def definition; end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def klass(*_arg0, **_arg1, &_arg2); end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def klass=(arg); end

  # source://factory_bot//lib/factory_bot/trait.rb#4
  def name; end

  # source://factory_bot//lib/factory_bot/trait.rb#20
  def names; end

  # source://factory_bot//lib/factory_bot/trait.rb#17
  def to_create(*_arg0, **_arg1, &_arg2); end

  protected

  # source://factory_bot//lib/factory_bot/trait.rb#31
  def block; end
end

# source://factory_bot//lib/factory_bot/errors.rb#6
class FactoryBot::TraitDefinitionError < ::RuntimeError; end

# source://factory_bot//lib/factory_bot/version.rb#2
FactoryBot::VERSION = T.let(T.unsafe(nil), String)
