# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-retry` gem.
# Please instead update this file by running `bin/tapioca gem faraday-retry`.


# source://faraday-retry//lib/faraday/retriable_response.rb#4
module Faraday
  class << self
    # source://faraday/1.10.3/lib/faraday.rb#81
    def default_adapter; end

    # source://faraday/1.10.3/lib/faraday.rb#137
    def default_adapter=(adapter); end

    # source://faraday/1.10.3/lib/faraday.rb#155
    def default_connection; end

    # source://faraday/1.10.3/lib/faraday.rb#84
    def default_connection=(_arg0); end

    # source://faraday/1.10.3/lib/faraday.rb#162
    def default_connection_options; end

    # source://faraday/1.10.3/lib/faraday.rb#169
    def default_connection_options=(options); end

    # source://faraday/1.10.3/lib/faraday.rb#89
    def ignore_env_proxy; end

    # source://faraday/1.10.3/lib/faraday.rb#89
    def ignore_env_proxy=(_arg0); end

    # source://faraday/1.10.3/lib/faraday.rb#72
    def lib_path; end

    # source://faraday/1.10.3/lib/faraday.rb#72
    def lib_path=(_arg0); end

    # source://faraday/1.10.3/lib/faraday.rb#118
    def new(url = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # source://faraday/1.10.3/lib/faraday.rb#128
    def require_lib(*libs); end

    # source://faraday/1.10.3/lib/faraday.rb#128
    def require_libs(*libs); end

    # source://faraday/1.10.3/lib/faraday.rb#142
    def respond_to_missing?(symbol, include_private = T.unsafe(nil)); end

    # source://faraday/1.10.3/lib/faraday.rb#68
    def root_path; end

    # source://faraday/1.10.3/lib/faraday.rb#68
    def root_path=(_arg0); end

    private

    # source://faraday/1.10.3/lib/faraday.rb#178
    def method_missing(name, *args, &block); end
  end
end

# source://faraday-retry//lib/faraday/retriable_response.rb#6
class Faraday::RetriableResponse < ::Faraday::Error; end

# source://faraday-retry//lib/faraday/retry/middleware.rb#4
module Faraday::Retry; end

# source://faraday-retry//lib/faraday/retry/middleware.rb#17
class Faraday::Retry::Middleware < ::Faraday::Middleware
  # source://faraday-retry//lib/faraday/retry/middleware.rb#114
  def initialize(app, options = T.unsafe(nil)); end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#166
  def build_exception_matcher(exceptions); end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#120
  def calculate_sleep_amount(retries, env); end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#134
  def call(env); end

  private

  # source://faraday-retry//lib/faraday/retry/middleware.rb#203
  def calculate_retry_after(env); end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#218
  def calculate_retry_interval(retries); end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#187
  def retry_request?(env, exception); end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#192
  def rewind_files(body); end
end

# source://faraday-retry//lib/faraday/retry/middleware.rb#18
Faraday::Retry::Middleware::DEFAULT_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# source://faraday-retry//lib/faraday/retry/middleware.rb#22
Faraday::Retry::Middleware::IDEMPOTENT_METHODS = T.let(T.unsafe(nil), Array)

# source://faraday-retry//lib/faraday/retry/middleware.rb#29
class Faraday::Retry::Middleware::Options < ::Faraday::Options
  # source://faraday-retry//lib/faraday/retry/middleware.rb#57
  def backoff_factor; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#61
  def exceptions; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#45
  def interval; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#53
  def interval_randomness; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#41
  def max; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#49
  def max_interval; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#65
  def methods; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#73
  def retry_block; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#69
  def retry_if; end

  # source://faraday-retry//lib/faraday/retry/middleware.rb#77
  def retry_statuses; end

  class << self
    # source://faraday-retry//lib/faraday/retry/middleware.rb#33
    def from(value); end
  end
end

# source://faraday-retry//lib/faraday/retry/middleware.rb#31
Faraday::Retry::Middleware::Options::DEFAULT_CHECK = T.let(T.unsafe(nil), Proc)

# source://faraday-retry//lib/faraday/retry/version.rb#5
Faraday::Retry::VERSION = T.let(T.unsafe(nil), String)
