# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday` gem.
# Please instead update this file by running `bin/tapioca gem faraday`.


# source://faraday//lib/faraday/middleware_registry.rb#5
module Faraday
  class << self
    # source://faraday//lib/faraday.rb#81
    def default_adapter; end

    # source://faraday//lib/faraday.rb#137
    def default_adapter=(adapter); end

    # source://faraday//lib/faraday.rb#155
    def default_connection; end

    # source://faraday//lib/faraday.rb#84
    def default_connection=(_arg0); end

    # source://faraday//lib/faraday.rb#162
    def default_connection_options; end

    # source://faraday//lib/faraday.rb#169
    def default_connection_options=(options); end

    # source://faraday//lib/faraday.rb#89
    def ignore_env_proxy; end

    # source://faraday//lib/faraday.rb#89
    def ignore_env_proxy=(_arg0); end

    # source://faraday//lib/faraday.rb#72
    def lib_path; end

    # source://faraday//lib/faraday.rb#72
    def lib_path=(_arg0); end

    # source://faraday//lib/faraday.rb#118
    def new(url = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # source://faraday//lib/faraday.rb#128
    def require_lib(*libs); end

    # source://faraday//lib/faraday.rb#128
    def require_libs(*libs); end

    # source://faraday//lib/faraday.rb#142
    def respond_to_missing?(symbol, include_private = T.unsafe(nil)); end

    # source://faraday//lib/faraday.rb#68
    def root_path; end

    # source://faraday//lib/faraday.rb#68
    def root_path=(_arg0); end

    private

    # source://faraday//lib/faraday.rb#178
    def method_missing(name, *args, &block); end
  end
end

# source://faraday//lib/faraday/adapter.rb#6
class Faraday::Adapter
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::DependencyLoader
  extend ::Faraday::Adapter::Parallelism
  extend ::Faraday::AutoloadHelper

  # source://faraday//lib/faraday/adapter.rb#33
  def initialize(_app = T.unsafe(nil), opts = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter.rb#60
  def call(env); end

  # source://faraday//lib/faraday/adapter.rb#55
  def close; end

  # source://faraday//lib/faraday/adapter.rb#46
  def connection(env); end

  private

  # source://faraday//lib/faraday/adapter.rb#91
  def request_timeout(type, options); end

  # source://faraday//lib/faraday/adapter.rb#67
  def save_response(env, status, body, headers = T.unsafe(nil), reason_phrase = T.unsafe(nil)); end
end

# source://faraday//lib/faraday/adapter.rb#10
Faraday::Adapter::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/adapter.rb#17
module Faraday::Adapter::Parallelism
  # source://faraday//lib/faraday/adapter.rb#24
  def inherited(subclass); end

  # source://faraday//lib/faraday/adapter.rb#18
  def supports_parallel=(_arg0); end

  # source://faraday//lib/faraday/adapter.rb#20
  def supports_parallel?; end
end

# source://faraday//lib/faraday/adapter.rb#99
Faraday::Adapter::TIMEOUT_KEYS = T.let(T.unsafe(nil), Hash)

# source://faraday//lib/faraday/adapter/test.rb#45
class Faraday::Adapter::Test < ::Faraday::Adapter
  # source://faraday//lib/faraday/adapter/test.rb#226
  def initialize(app, stubs = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#237
  def call(env); end

  # source://faraday//lib/faraday/adapter/test.rb#232
  def configure; end

  # source://faraday//lib/faraday/adapter/test.rb#46
  def stubs; end

  # source://faraday//lib/faraday/adapter/test.rb#46
  def stubs=(_arg0); end
end

# source://faraday//lib/faraday/adapter/test.rb#167
class Faraday::Adapter::Test::Stub < ::Struct
  # source://faraday//lib/faraday/adapter/test.rb#206
  def headers_match?(request_headers); end

  # source://faraday//lib/faraday/adapter/test.rb#168
  def matches?(env); end

  # source://faraday//lib/faraday/adapter/test.rb#193
  def params_match?(env); end

  # source://faraday//lib/faraday/adapter/test.rb#184
  def path_match?(request_path, meta); end

  # source://faraday//lib/faraday/adapter/test.rb#221
  def to_s; end
end

# source://faraday//lib/faraday/adapter/test.rb#49
class Faraday::Adapter::Test::Stubs
  # source://faraday//lib/faraday/adapter/test.rb#53
  def initialize(strict_mode: T.unsafe(nil)); end

  # source://faraday//lib/faraday/adapter/test.rb#101
  def delete(path, headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#61
  def empty?; end

  # source://faraday//lib/faraday/adapter/test.rb#81
  def get(path, headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#85
  def head(path, headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#66
  def match(env); end

  # source://faraday//lib/faraday/adapter/test.rb#105
  def options(path, headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#97
  def patch(path, body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#89
  def post(path, body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#93
  def put(path, body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/adapter/test.rb#126
  def strict_mode=(value); end

  # source://faraday//lib/faraday/adapter/test.rb#110
  def verify_stubbed_calls; end

  protected

  # source://faraday//lib/faraday/adapter/test.rb#156
  def matches?(stack, env); end

  # source://faraday//lib/faraday/adapter/test.rb#137
  def new_stub(request_method, path, headers = T.unsafe(nil), body = T.unsafe(nil), &block); end
end

# source://faraday//lib/faraday/adapter/test.rb#50
class Faraday::Adapter::Test::Stubs::NotFound < ::StandardError; end

# source://faraday//lib/faraday/adapter/typhoeus.rb#7
class Faraday::Adapter::Typhoeus < ::Faraday::Adapter
  # source://faraday//lib/faraday/adapter/typhoeus.rb#9
  def call; end
end

# source://faraday//lib/faraday/adapter_registry.rb#8
class Faraday::AdapterRegistry
  # source://faraday//lib/faraday/adapter_registry.rb#9
  def initialize; end

  # source://faraday//lib/faraday/adapter_registry.rb#14
  def get(name); end

  # source://faraday//lib/faraday/adapter_registry.rb#23
  def set(klass, name = T.unsafe(nil)); end
end

# source://faraday//lib/faraday/autoload.rb#8
module Faraday::AutoloadHelper
  # source://faraday//lib/faraday/autoload.rb#49
  def all_loaded_constants; end

  # source://faraday//lib/faraday/autoload.rb#25
  def autoload_all(prefix, options); end

  # source://faraday//lib/faraday/autoload.rb#39
  def load_autoloaded_constants; end
end

# source://faraday//lib/faraday/error.rb#89
class Faraday::BadRequestError < ::Faraday::ClientError; end

# source://faraday//lib/faraday.rb#60
Faraday::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/error.rb#85
class Faraday::ClientError < ::Faraday::Error; end

# source://faraday//lib/faraday/error.rb#109
class Faraday::ConflictError < ::Faraday::ClientError; end

# source://faraday//lib/faraday/connection.rb#17
class Faraday::Connection
  extend ::Forwardable
  extend ::Faraday::Deprecate

  # source://faraday//lib/faraday/connection.rb#65
  def initialize(url = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#348
  def _deprecated_authorization(type, token); end

  # source://faraday//lib/faraday/connection.rb#301
  def _deprecated_basic_auth(login, pass); end

  # source://faraday//lib/faraday/connection.rb#321
  def _deprecated_token_auth(token, options = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def adapter(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def app(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/deprecate.rb#86
  def authorization(*args, &block); end

  # source://faraday//lib/faraday/deprecate.rb#86
  def basic_auth(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def build(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#542
  def build_exclusive_url(url = T.unsafe(nil), params = T.unsafe(nil), params_encoder = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#525
  def build_request(method); end

  # source://faraday//lib/faraday/connection.rb#479
  def build_url(url = T.unsafe(nil), extra_params = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#33
  def builder; end

  # source://faraday//lib/faraday/connection.rb#127
  def close; end

  # source://faraday//lib/faraday/connection.rb#363
  def default_parallel_manager; end

  # source://faraday//lib/faraday/connection.rb#42
  def default_parallel_manager=(_arg0); end

  # source://faraday//lib/faraday/connection.rb#201
  def delete(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#566
  def dup; end

  # source://faraday//lib/faraday/connection.rb#622
  def find_default_proxy; end

  # source://faraday//lib/faraday/connection.rb#201
  def get(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#201
  def head(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#26
  def headers; end

  # source://faraday//lib/faraday/connection.rb#116
  def headers=(hash); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def host(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def host=(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#389
  def in_parallel(manager = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#378
  def in_parallel?; end

  # source://faraday//lib/faraday/connection.rb#98
  def initialize_proxy(url, options); end

  # source://faraday//lib/faraday/connection.rb#224
  def options(*args); end

  # source://faraday//lib/faraday/connection.rb#39
  def parallel_manager; end

  # source://faraday//lib/faraday/connection.rb#23
  def params; end

  # source://faraday//lib/faraday/connection.rb#110
  def params=(hash); end

  # source://faraday//lib/faraday/connection.rb#282
  def patch(url = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def path_prefix(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#454
  def path_prefix=(value); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def port(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def port=(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#282
  def post(url = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/connection.rb#45
  def proxy; end

  # source://faraday//lib/faraday/connection.rb#405
  def proxy=(new_value); end

  # source://faraday//lib/faraday/connection.rb#630
  def proxy_for_request(url); end

  # source://faraday//lib/faraday/connection.rb#597
  def proxy_from_env(url); end

  # source://faraday//lib/faraday/connection.rb#282
  def put(url = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def request(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def response(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#503
  def run_request(method, url, body, headers); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def scheme(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def scheme=(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#589
  def set_authorization_header(header_type, *args); end

  # source://faraday//lib/faraday/connection.rb#443
  def set_basic_auth(user, password); end

  # source://faraday//lib/faraday/connection.rb#36
  def ssl; end

  # source://faraday//lib/faraday/connection.rb#640
  def support_parallel?(adapter); end

  # source://faraday//lib/faraday/deprecate.rb#86
  def token_auth(*args, &block); end

  # source://faraday//lib/faraday/connection.rb#201
  def trace(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # source://faraday//lib/faraday/connection.rb#30
  def url_prefix; end

  # source://faraday//lib/faraday/connection.rb#428
  def url_prefix=(url, encoder = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def use(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/connection.rb#583
  def with_uri_credentials(uri); end
end

# source://faraday//lib/faraday/connection.rb#19
Faraday::Connection::METHODS = T.let(T.unsafe(nil), Set)

# source://faraday//lib/faraday/connection.rb#20
Faraday::Connection::USER_AGENT = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/error.rb#136
class Faraday::ConnectionFailed < ::Faraday::Error; end

# source://faraday//lib/faraday/options/connection_options.rb#8
class Faraday::ConnectionOptions < ::Faraday::Options
  # source://faraday//lib/faraday/options.rb#177
  def builder_class; end

  # source://faraday//lib/faraday/options/connection_options.rb#18
  def new_builder(block); end

  # source://faraday//lib/faraday/options.rb#177
  def request; end

  # source://faraday//lib/faraday/options.rb#177
  def ssl; end
end

# source://faraday//lib/faraday/encoders/nested_params_encoder.rb#75
module Faraday::DecodeMethods
  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#81
  def decode(query); end

  protected

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#138
  def add_to_context(is_array, context, value, subkey); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#101
  def decode_pair(key, value, context); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#145
  def dehash(hash, depth); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#133
  def match_context(context, subkey); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#123
  def new_context(subkey, is_array, context); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#113
  def prepare_context(context, subkey, is_array, last_subkey); end
end

# source://faraday//lib/faraday/encoders/nested_params_encoder.rb#99
Faraday::DecodeMethods::SUBKEYS_REGEX = T.let(T.unsafe(nil), Regexp)

# source://faraday//lib/faraday/dependency_loader.rb#7
module Faraday::DependencyLoader
  # source://faraday//lib/faraday/dependency_loader.rb#12
  def dependency(lib = T.unsafe(nil)); end

  # source://faraday//lib/faraday/dependency_loader.rb#30
  def inherited(subclass); end

  # source://faraday//lib/faraday/dependency_loader.rb#8
  def load_error; end

  # source://faraday//lib/faraday/dependency_loader.rb#26
  def loaded?; end

  # source://faraday//lib/faraday/dependency_loader.rb#18
  def new(*_arg0, **_arg1); end

  private

  # source://faraday//lib/faraday/dependency_loader.rb#37
  def load_error=(_arg0); end
end

# source://faraday//lib/faraday/deprecate.rb#49
module Faraday::Deprecate
  private

  # source://faraday//lib/faraday/deprecate.rb#81
  def deprecate(name, repl, ver, custom_message = T.unsafe(nil)); end

  # source://faraday//lib/faraday/deprecate.rb#65
  def skip_during; end

  class << self
    # source://faraday//lib/faraday/deprecate.rb#81
    def deprecate(name, repl, ver, custom_message = T.unsafe(nil)); end

    # source://faraday//lib/faraday/deprecate.rb#50
    def skip; end

    # source://faraday//lib/faraday/deprecate.rb#60
    def skip=(value); end

    # source://faraday//lib/faraday/deprecate.rb#65
    def skip_during; end
  end
end

# source://faraday//lib/faraday/deprecate.rb#9
module Faraday::DeprecatedClass
  class << self
    # source://faraday//lib/faraday/deprecate.rb#10
    def proxy_class(origclass, ver = T.unsafe(nil)); end
  end
end

# source://faraday//lib/faraday/encoders/nested_params_encoder.rb#5
module Faraday::EncodeMethods
  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#11
  def encode(params); end

  protected

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#64
  def encode_array(parent, value); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#53
  def encode_hash(parent, value); end

  # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#40
  def encode_pair(parent, value); end
end

# source://faraday//lib/faraday/options/env.rb#52
class Faraday::Env < ::Faraday::Options
  extend ::Forwardable

  # source://faraday//lib/faraday/options/env.rb#84
  def [](key); end

  # source://faraday//lib/faraday/options/env.rb#96
  def []=(key, value); end

  # source://faraday//lib/faraday/options/env.rb#113
  def body; end

  # source://faraday//lib/faraday/options/env.rb#117
  def body=(value); end

  # source://faraday//lib/faraday/options/env.rb#133
  def clear_body; end

  # source://faraday//lib/faraday/options/env.rb#109
  def current_body; end

  # source://faraday//lib/faraday/options/env.rb#161
  def custom_members; end

  # source://faraday//lib/faraday/options/env.rb#167
  def in_member_set?(key); end

  # source://faraday//lib/faraday/options/env.rb#149
  def inspect; end

  # source://faraday//lib/faraday/options/env.rb#128
  def needs_body?; end

  # source://faraday//lib/faraday/options/env.rb#145
  def parallel?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def params_encoder(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/options/env.rb#140
  def parse_body?; end

  # source://faraday//lib/faraday/options/env.rb#122
  def success?; end

  class << self
    # source://faraday//lib/faraday/options/env.rb#75
    def from(value); end

    # source://faraday//lib/faraday/options/env.rb#177
    def member_set; end
  end
end

# source://faraday//lib/faraday/options/env.rb#55
Faraday::Env::ContentLength = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/options/env.rb#62
Faraday::Env::MethodsWithBodies = T.let(T.unsafe(nil), Set)

# source://faraday//lib/faraday/options/env.rb#56
Faraday::Env::StatusesWithoutBody = T.let(T.unsafe(nil), Set)

# source://faraday//lib/faraday/options/env.rb#57
Faraday::Env::SuccessfulStatuses = T.let(T.unsafe(nil), Range)

# source://faraday//lib/faraday/error.rb#6
class Faraday::Error < ::StandardError
  # source://faraday//lib/faraday/error.rb#9
  def initialize(exc, response = T.unsafe(nil)); end

  # source://faraday//lib/faraday/error.rb#15
  def backtrace; end

  # source://faraday//lib/faraday/error.rb#23
  def inspect; end

  # source://faraday//lib/faraday/error.rb#7
  def response; end

  # source://faraday//lib/faraday/error.rb#39
  def response_body; end

  # source://faraday//lib/faraday/error.rb#35
  def response_headers; end

  # source://faraday//lib/faraday/error.rb#31
  def response_status; end

  # source://faraday//lib/faraday/error.rb#7
  def wrapped_exception; end

  protected

  # source://faraday//lib/faraday/error.rb#74
  def exc_msg_and_response(exc, response = T.unsafe(nil)); end

  # source://faraday//lib/faraday/error.rb#64
  def exc_msg_and_response!(exc, response = T.unsafe(nil)); end
end

# source://faraday//lib/faraday/encoders/flat_params_encoder.rb#6
module Faraday::FlatParamsEncoder
  class << self
    # source://faraday//lib/faraday/encoders/flat_params_encoder.rb#74
    def decode(query); end

    # source://faraday//lib/faraday/encoders/flat_params_encoder.rb#23
    def encode(params); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def escape(*args, **_arg1, &block); end

    # source://faraday//lib/faraday/encoders/flat_params_encoder.rb#99
    def sort_params; end

    # source://faraday//lib/faraday/encoders/flat_params_encoder.rb#99
    def sort_params=(_arg0); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def unescape(*args, **_arg1, &block); end
  end
end

# source://faraday//lib/faraday/error.rb#97
class Faraday::ForbiddenError < ::Faraday::ClientError; end

# source://faraday//lib/faraday/logging/formatter.rb#5
module Faraday::Logging; end

# source://faraday//lib/faraday/logging/formatter.rb#7
class Faraday::Logging::Formatter
  extend ::Forwardable

  # source://faraday//lib/faraday/logging/formatter.rb#13
  def initialize(logger:, options:); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def debug(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def error(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def fatal(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/logging/formatter.rb#39
  def filter(filter_word, filter_replacement); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def info(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/logging/formatter.rb#21
  def request(env); end

  # source://faraday//lib/faraday/logging/formatter.rb#31
  def response(env); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def warn(*args, **_arg1, &block); end

  private

  # source://faraday//lib/faraday/logging/formatter.rb#79
  def apply_filters(output); end

  # source://faraday//lib/faraday/logging/formatter.rb#49
  def dump_body(body); end

  # source://faraday//lib/faraday/logging/formatter.rb#45
  def dump_headers(headers); end

  # source://faraday//lib/faraday/logging/formatter.rb#99
  def log_body(type, body); end

  # source://faraday//lib/faraday/logging/formatter.rb#70
  def log_body?(type); end

  # source://faraday//lib/faraday/logging/formatter.rb#94
  def log_headers(type, headers); end

  # source://faraday//lib/faraday/logging/formatter.rb#61
  def log_headers?(type); end

  # source://faraday//lib/faraday/logging/formatter.rb#86
  def log_level; end

  # source://faraday//lib/faraday/logging/formatter.rb#57
  def pretty_inspect(body); end
end

# source://faraday//lib/faraday/logging/formatter.rb#10
Faraday::Logging::Formatter::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://faraday//lib/faraday/methods.rb#5
Faraday::METHODS_WITH_BODY = T.let(T.unsafe(nil), Array)

# source://faraday//lib/faraday/methods.rb#4
Faraday::METHODS_WITH_QUERY = T.let(T.unsafe(nil), Array)

# source://faraday//lib/faraday/middleware.rb#5
class Faraday::Middleware
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::DependencyLoader

  # source://faraday//lib/faraday/middleware.rb#11
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://faraday//lib/faraday/middleware.rb#9
  def app; end

  # source://faraday//lib/faraday/middleware.rb#16
  def call(env); end

  # source://faraday//lib/faraday/middleware.rb#23
  def close; end

  # source://faraday//lib/faraday/middleware.rb#9
  def options; end
end

# source://faraday//lib/faraday/middleware_registry.rb#8
module Faraday::MiddlewareRegistry
  # source://faraday//lib/faraday/middleware_registry.rb#99
  def fetch_middleware(key); end

  # source://faraday//lib/faraday/middleware_registry.rb#103
  def load_middleware(key); end

  # source://faraday//lib/faraday/middleware_registry.rb#89
  def lookup_middleware(key); end

  # source://faraday//lib/faraday/middleware_registry.rb#94
  def middleware_mutex(&block); end

  # source://faraday//lib/faraday/middleware_registry.rb#54
  def register_middleware(autoload_path = T.unsafe(nil), mapping = T.unsafe(nil)); end

  # source://faraday//lib/faraday/middleware_registry.rb#68
  def unregister_middleware(key); end
end

# source://faraday//lib/faraday/encoders/nested_params_encoder.rb#162
module Faraday::NestedParamsEncoder
  extend ::Faraday::EncodeMethods
  extend ::Faraday::DecodeMethods

  class << self
    # source://forwardable/1.3.3/forwardable.rb#231
    def escape(*args, **_arg1, &block); end

    # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#164
    def sort_params; end

    # source://faraday//lib/faraday/encoders/nested_params_encoder.rb#164
    def sort_params=(_arg0); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def unescape(*args, **_arg1, &block); end
  end
end

# source://faraday//lib/faraday/error.rb#128
class Faraday::NilStatusError < ::Faraday::ServerError
  # source://faraday//lib/faraday/error.rb#129
  def initialize(exc, response = T.unsafe(nil)); end
end

# source://faraday//lib/faraday/options.rb#6
class Faraday::Options < ::Struct
  # source://faraday//lib/faraday/options.rb#185
  def [](key); end

  # source://faraday//lib/faraday/options.rb#46
  def clear; end

  # source://faraday//lib/faraday/options.rb#71
  def deep_dup; end

  # source://faraday//lib/faraday/options.rb#39
  def delete(key); end

  # source://faraday//lib/faraday/options.rb#13
  def each; end

  # source://faraday//lib/faraday/options.rb#106
  def each_key(&block); end

  # source://faraday//lib/faraday/options.rb#120
  def each_value(&block); end

  # source://faraday//lib/faraday/options.rb#101
  def empty?; end

  # source://faraday//lib/faraday/options.rb#76
  def fetch(key, *args); end

  # source://faraday//lib/faraday/options.rb#113
  def has_key?(key); end

  # source://faraday//lib/faraday/options.rb#127
  def has_value?(value); end

  # source://faraday//lib/faraday/options.rb#144
  def inspect; end

  # source://faraday//lib/faraday/options.rb#113
  def key?(key); end

  # source://faraday//lib/faraday/options.rb#96
  def keys; end

  # source://faraday//lib/faraday/options.rb#66
  def merge(other); end

  # source://faraday//lib/faraday/options.rb#51
  def merge!(other); end

  # source://faraday//lib/faraday/options.rb#194
  def symbolized_key_set; end

  # source://faraday//lib/faraday/options.rb#134
  def to_hash; end

  # source://faraday//lib/faraday/options.rb#22
  def update(obj); end

  # source://faraday//lib/faraday/options.rb#127
  def value?(value); end

  # source://faraday//lib/faraday/options.rb#91
  def values_at(*keys); end

  class << self
    # source://faraday//lib/faraday/options.rb#166
    def attribute_options; end

    # source://faraday//lib/faraday/options.rb#204
    def fetch_error_class; end

    # source://faraday//lib/faraday/options.rb#8
    def from(value); end

    # source://faraday//lib/faraday/options.rb#198
    def inherited(subclass); end

    # source://faraday//lib/faraday/options.rb#170
    def memoized(key, &block); end

    # source://faraday//lib/faraday/options.rb#181
    def memoized_attributes; end

    # source://faraday//lib/faraday/options.rb#156
    def options(mapping); end

    # source://faraday//lib/faraday/options.rb#161
    def options_for(key); end
  end
end

# source://faraday//lib/faraday/error.rb#144
class Faraday::ParsingError < ::Faraday::Error; end

# source://faraday//lib/faraday/error.rb#105
class Faraday::ProxyAuthError < ::Faraday::ClientError; end

# source://faraday//lib/faraday/options/proxy_options.rb#6
class Faraday::ProxyOptions < ::Faraday::Options
  extend ::Forwardable

  # source://forwardable/1.3.3/forwardable.rb#231
  def host(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def host=(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/options.rb#177
  def password; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def path(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def path=(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def port(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def port=(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def scheme(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def scheme=(*args, **_arg1, &block); end

  # source://faraday//lib/faraday/options.rb#177
  def user; end

  class << self
    # source://faraday//lib/faraday/options/proxy_options.rb#11
    def from(value); end
  end
end

# source://faraday//lib/faraday/rack_builder.rb#15
class Faraday::RackBuilder
  # source://faraday//lib/faraday/rack_builder.rb#61
  def initialize(handlers = T.unsafe(nil), adapter = T.unsafe(nil), &block); end

  # source://faraday//lib/faraday/rack_builder.rb#179
  def ==(other); end

  # source://faraday//lib/faraday/rack_builder.rb#80
  def [](idx); end

  # source://faraday//lib/faraday/rack_builder.rb#111
  def adapter(klass = T.unsafe(nil), *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#164
  def app; end

  # source://faraday//lib/faraday/rack_builder.rb#73
  def build(options = T.unsafe(nil)); end

  # source://faraday//lib/faraday/rack_builder.rb#205
  def build_env(connection, request); end

  # source://faraday//lib/faraday/rack_builder.rb#153
  def build_response(connection, request); end

  # source://faraday//lib/faraday/rack_builder.rb#141
  def delete(handler); end

  # source://faraday//lib/faraday/rack_builder.rb#185
  def dup; end

  # source://faraday//lib/faraday/rack_builder.rb#19
  def handlers; end

  # source://faraday//lib/faraday/rack_builder.rb#19
  def handlers=(_arg0); end

  # source://faraday//lib/faraday/rack_builder.rb#120
  def insert(index, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#129
  def insert_after(index, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#120
  def insert_before(index, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#85
  def lock!; end

  # source://faraday//lib/faraday/rack_builder.rb#89
  def locked?; end

  # source://faraday//lib/faraday/rack_builder.rb#103
  def request(key, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#107
  def response(key, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#134
  def swap(index, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#171
  def to_app; end

  # source://faraday//lib/faraday/rack_builder.rb#93
  def use(klass, *args, **_arg2, &block); end

  private

  # source://faraday//lib/faraday/rack_builder.rb#230
  def adapter_set?; end

  # source://faraday//lib/faraday/rack_builder.rb#242
  def assert_index(index); end

  # source://faraday//lib/faraday/rack_builder.rb#234
  def is_adapter?(klass); end

  # source://faraday//lib/faraday/rack_builder.rb#224
  def raise_if_adapter(klass); end

  # source://faraday//lib/faraday/rack_builder.rb#220
  def raise_if_locked; end

  # source://faraday//lib/faraday/rack_builder.rb#238
  def use_symbol(mod, key, *args, **_arg3, &block); end
end

# source://faraday//lib/faraday/rack_builder.rb#26
class Faraday::RackBuilder::Handler
  # source://faraday//lib/faraday/rack_builder.rb#31
  def initialize(klass, *args, **_arg2, &block); end

  # source://faraday//lib/faraday/rack_builder.rb#46
  def ==(other); end

  # source://faraday//lib/faraday/rack_builder.rb#56
  def build(app = T.unsafe(nil)); end

  # source://faraday//lib/faraday/rack_builder.rb#42
  def inspect; end

  # source://faraday//lib/faraday/rack_builder.rb#38
  def klass; end

  # source://faraday//lib/faraday/rack_builder.rb#29
  def name; end
end

# source://faraday//lib/faraday/rack_builder.rb#27
Faraday::RackBuilder::Handler::REGISTRY = T.let(T.unsafe(nil), Faraday::AdapterRegistry)

# source://faraday//lib/faraday/rack_builder.rb#218
Faraday::RackBuilder::LOCK_ERR = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/rack_builder.rb#17
Faraday::RackBuilder::NO_ARGUMENT = T.let(T.unsafe(nil), Object)

# source://faraday//lib/faraday/rack_builder.rb#22
class Faraday::RackBuilder::StackLocked < ::RuntimeError; end

# source://faraday//lib/faraday/request.rb#31
class Faraday::Request < ::Struct
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::Deprecate
  extend ::Faraday::AutoloadHelper

  # source://faraday//lib/faraday/request.rb#112
  def [](key); end

  # source://faraday//lib/faraday/request.rb#118
  def []=(key, value); end

  # source://faraday//lib/faraday/request.rb#60
  def _deprecated_method; end

  # source://faraday//lib/faraday/request.rb#81
  def headers=(hash); end

  # source://faraday//lib/faraday/request.rb#125
  def marshal_dump; end

  # source://faraday//lib/faraday/request.rb#139
  def marshal_load(serialised); end

  # source://faraday//lib/faraday/deprecate.rb#86
  def method(*args, &block); end

  # source://faraday//lib/faraday/request.rb#70
  def params=(hash); end

  # source://faraday//lib/faraday/request.rb#149
  def to_env(connection); end

  # source://faraday//lib/faraday/request.rb#94
  def url(path, params = T.unsafe(nil)); end

  class << self
    # source://faraday//lib/faraday/request.rb#54
    def create(request_method); end
  end
end

# source://faraday//lib/faraday/request/authorization.rb#8
class Faraday::Request::Authorization < ::Faraday::Middleware
  # source://faraday//lib/faraday/request/authorization.rb#48
  def initialize(app, type, param); end

  # source://faraday//lib/faraday/request/authorization.rb#55
  def on_request(env); end

  class << self
    # source://faraday//lib/faraday/request/authorization.rb#34
    def build_hash(type, hash); end

    # source://faraday//lib/faraday/request/authorization.rb#16
    def header(type, token); end
  end
end

# source://faraday//lib/faraday/request/authorization.rb#10
Faraday::Request::Authorization::KEY = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/request/basic_authentication.rb#8
class Faraday::Request::BasicAuthentication < ::Faraday::Request::Authorization
  class << self
    # source://faraday//lib/faraday/request/basic_authentication.rb#13
    def header(login, pass); end
  end
end

# source://faraday//lib/faraday/request/instrumentation.rb#6
class Faraday::Request::Instrumentation < ::Faraday::Middleware
  # source://faraday//lib/faraday/request/instrumentation.rb#40
  def initialize(app, options = T.unsafe(nil)); end

  # source://faraday//lib/faraday/request/instrumentation.rb#47
  def call(env); end
end

# source://faraday//lib/faraday/request/instrumentation.rb#8
class Faraday::Request::Instrumentation::Options < ::Faraday::Options
  # source://faraday//lib/faraday/request/instrumentation.rb#15
  def instrumenter; end

  # source://faraday//lib/faraday/request/instrumentation.rb#10
  def name; end
end

# source://faraday//lib/faraday/request/json.rb#14
class Faraday::Request::Json < ::Faraday::Middleware
  # source://faraday//lib/faraday/request/json.rb#18
  def on_request(env); end

  private

  # source://faraday//lib/faraday/request/json.rb#42
  def body?(env); end

  # source://faraday//lib/faraday/request/json.rb#26
  def encode(data); end

  # source://faraday//lib/faraday/request/json.rb#30
  def match_content_type(env); end

  # source://faraday//lib/faraday/request/json.rb#37
  def process_request?(env); end

  # source://faraday//lib/faraday/request/json.rb#46
  def request_type(env); end
end

# source://faraday//lib/faraday/request/json.rb#15
Faraday::Request::Json::MIME_TYPE = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/request/json.rb#16
Faraday::Request::Json::MIME_TYPE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://faraday//lib/faraday.rb#32
Faraday::Request::Multipart = Faraday::Multipart::Middleware

# source://faraday//lib/faraday.rb#33
Faraday::Request::Retry = Faraday::Retry::Middleware

# source://faraday//lib/faraday/request/token_authentication.rb#7
class Faraday::Request::TokenAuthentication < ::Faraday::Request::Authorization
  # source://faraday//lib/faraday/request/token_authentication.rb#15
  def initialize(app, token, options = T.unsafe(nil)); end

  class << self
    # source://faraday//lib/faraday/request/token_authentication.rb#9
    def header(token, options = T.unsafe(nil)); end
  end
end

# source://faraday//lib/faraday/request/url_encoded.rb#6
class Faraday::Request::UrlEncoded < ::Faraday::Middleware
  # source://faraday//lib/faraday/request/url_encoded.rb#20
  def call(env); end

  # source://faraday//lib/faraday/request/url_encoded.rb#30
  def match_content_type(env); end

  # source://faraday//lib/faraday/request/url_encoded.rb#41
  def process_request?(env); end

  # source://faraday//lib/faraday/request/url_encoded.rb#49
  def request_type(env); end

  class << self
    # source://faraday//lib/faraday/request/url_encoded.rb#12
    def mime_type; end

    # source://faraday//lib/faraday/request/url_encoded.rb#12
    def mime_type=(_arg0); end
  end
end

# source://faraday//lib/faraday/request/url_encoded.rb#8
Faraday::Request::UrlEncoded::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# source://faraday//lib/faraday/options/request_options.rb#8
class Faraday::RequestOptions < ::Faraday::Options
  # source://faraday//lib/faraday/options/request_options.rb#10
  def []=(key, value); end

  # source://faraday//lib/faraday/options/request_options.rb#18
  def stream_response?; end
end

# source://faraday//lib/faraday/error.rb#101
class Faraday::ResourceNotFound < ::Faraday::ClientError; end

# source://faraday//lib/faraday/response.rb#7
class Faraday::Response
  extend ::Forwardable
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::AutoloadHelper

  # source://faraday//lib/faraday/response.rb#28
  def initialize(env = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def [](*args, **_arg1, &block); end

  # source://faraday//lib/faraday/response.rb#96
  def apply_request(request_env); end

  # source://faraday//lib/faraday/response.rb#49
  def body; end

  # source://faraday//lib/faraday/response.rb#33
  def env; end

  # source://faraday//lib/faraday/response.rb#66
  def finish(env); end

  # source://faraday//lib/faraday/response.rb#53
  def finished?; end

  # source://faraday//lib/faraday/response.rb#43
  def headers; end

  # source://faraday//lib/faraday/response.rb#86
  def marshal_dump; end

  # source://faraday//lib/faraday/response.rb#90
  def marshal_load(env); end

  # source://faraday//lib/faraday/response.rb#57
  def on_complete(&block); end

  # source://faraday//lib/faraday/response.rb#39
  def reason_phrase; end

  # source://faraday//lib/faraday/response.rb#35
  def status; end

  # source://faraday//lib/faraday/response.rb#74
  def success?; end

  # source://faraday//lib/faraday/response.rb#78
  def to_hash; end
end

# source://faraday//lib/faraday/response/json.rb#8
class Faraday::Response::Json < ::Faraday::Response::Middleware
  # source://faraday//lib/faraday/response/json.rb#9
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://faraday//lib/faraday/response/json.rb#16
  def on_complete(env); end

  private

  # source://faraday//lib/faraday/response/json.rb#29
  def parse(body); end

  # source://faraday//lib/faraday/response/json.rb#33
  def parse_response?(env); end

  # source://faraday//lib/faraday/response/json.rb#22
  def process_response(env); end

  # source://faraday//lib/faraday/response/json.rb#38
  def process_response_type?(env); end

  # source://faraday//lib/faraday/response/json.rb#45
  def response_type(env); end
end

# source://faraday//lib/faraday/response/logger.rb#12
class Faraday::Response::Logger < ::Faraday::Response::Middleware
  # source://faraday//lib/faraday/response/logger.rb#13
  def initialize(app, logger = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://faraday//lib/faraday/response/logger.rb#21
  def call(env); end

  # source://faraday//lib/faraday/response/logger.rb#26
  def on_complete(env); end
end

# source://faraday//lib/faraday/response.rb#9
class Faraday::Response::Middleware < ::Faraday::Middleware
  # source://faraday//lib/faraday/response.rb#13
  def on_complete(env); end
end

# source://faraday//lib/faraday/response/raise_error.rb#7
class Faraday::Response::RaiseError < ::Faraday::Response::Middleware
  # source://faraday//lib/faraday/response/raise_error.rb#13
  def on_complete(env); end

  # source://faraday//lib/faraday/response/raise_error.rb#40
  def response_values(env); end
end

# source://faraday//lib/faraday/response/raise_error.rb#9
Faraday::Response::RaiseError::ClientErrorStatuses = T.let(T.unsafe(nil), Range)

# source://faraday//lib/faraday/response/raise_error.rb#10
Faraday::Response::RaiseError::ServerErrorStatuses = T.let(T.unsafe(nil), Range)

# source://faraday//lib/faraday/error.rb#140
class Faraday::SSLError < ::Faraday::Error; end

# source://faraday//lib/faraday/options/ssl_options.rb#47
class Faraday::SSLOptions < ::Faraday::Options
  # source://faraday//lib/faraday/options/ssl_options.rb#55
  def disable?; end

  # source://faraday//lib/faraday/options/ssl_options.rb#50
  def verify?; end
end

# source://faraday//lib/faraday/error.rb#117
class Faraday::ServerError < ::Faraday::Error; end

# source://faraday//lib/faraday/error.rb#121
class Faraday::TimeoutError < ::Faraday::ServerError
  # source://faraday//lib/faraday/error.rb#122
  def initialize(exc = T.unsafe(nil), response = T.unsafe(nil)); end
end

# source://faraday//lib/faraday.rb#12
Faraday::Timer = Timeout

# source://faraday//lib/faraday/error.rb#93
class Faraday::UnauthorizedError < ::Faraday::ClientError; end

# source://faraday//lib/faraday/error.rb#113
class Faraday::UnprocessableEntityError < ::Faraday::ClientError; end

# source://faraday//lib/faraday/utils/headers.rb#4
module Faraday::Utils
  private

  # source://faraday//lib/faraday/utils.rb#63
  def URI(url); end

  # source://faraday//lib/faraday/utils.rb#15
  def build_nested_query(params); end

  # source://faraday//lib/faraday/utils.rb#11
  def build_query(params); end

  # source://faraday//lib/faraday/utils.rb#109
  def deep_merge(source, hash); end

  # source://faraday//lib/faraday/utils.rb#97
  def deep_merge!(target, hash); end

  # source://faraday//lib/faraday/utils.rb#50
  def default_params_encoder; end

  # source://faraday//lib/faraday/utils.rb#19
  def default_space_encoding; end

  # source://faraday//lib/faraday/utils.rb#73
  def default_uri_parser; end

  # source://faraday//lib/faraday/utils.rb#80
  def default_uri_parser=(parser); end

  # source://faraday//lib/faraday/utils.rb#29
  def escape(str); end

  # source://faraday//lib/faraday/utils.rb#90
  def normalize_path(url); end

  # source://faraday//lib/faraday/utils.rb#46
  def parse_nested_query(query); end

  # source://faraday//lib/faraday/utils.rb#42
  def parse_query(query); end

  # source://faraday//lib/faraday/utils.rb#113
  def sort_query_params(query); end

  # source://faraday//lib/faraday/utils.rb#35
  def unescape(str); end

  class << self
    # source://faraday//lib/faraday/utils.rb#63
    def URI(url); end

    # source://faraday//lib/faraday/utils.rb#15
    def build_nested_query(params); end

    # source://faraday//lib/faraday/utils.rb#11
    def build_query(params); end

    # source://faraday//lib/faraday/utils.rb#109
    def deep_merge(source, hash); end

    # source://faraday//lib/faraday/utils.rb#97
    def deep_merge!(target, hash); end

    # source://faraday//lib/faraday/utils.rb#50
    def default_params_encoder; end

    # source://faraday//lib/faraday/utils.rb#55
    def default_params_encoder=(_arg0); end

    # source://faraday//lib/faraday/utils.rb#19
    def default_space_encoding; end

    # source://faraday//lib/faraday/utils.rb#24
    def default_space_encoding=(_arg0); end

    # source://faraday//lib/faraday/utils.rb#73
    def default_uri_parser; end

    # source://faraday//lib/faraday/utils.rb#80
    def default_uri_parser=(parser); end

    # source://faraday//lib/faraday/utils.rb#29
    def escape(str); end

    # source://faraday//lib/faraday/utils.rb#90
    def normalize_path(url); end

    # source://faraday//lib/faraday/utils.rb#46
    def parse_nested_query(query); end

    # source://faraday//lib/faraday/utils.rb#42
    def parse_query(query); end

    # source://faraday//lib/faraday/utils.rb#113
    def sort_query_params(query); end

    # source://faraday//lib/faraday/utils.rb#35
    def unescape(str); end
  end
end

# source://faraday//lib/faraday/utils.rb#39
Faraday::Utils::DEFAULT_SEP = T.let(T.unsafe(nil), Regexp)

# source://faraday//lib/faraday/utils.rb#27
Faraday::Utils::ESCAPE_RE = T.let(T.unsafe(nil), Regexp)

# source://faraday//lib/faraday/utils/headers.rb#9
class Faraday::Utils::Headers < ::Hash
  # source://faraday//lib/faraday/utils/headers.rb#20
  def initialize(hash = T.unsafe(nil)); end

  # source://faraday//lib/faraday/utils/headers.rb#52
  def [](key); end

  # source://faraday//lib/faraday/utils/headers.rb#57
  def []=(key, val); end

  # source://faraday//lib/faraday/utils/headers.rb#71
  def delete(key); end

  # source://faraday//lib/faraday/utils/headers.rb#65
  def fetch(key, *args, &block); end

  # source://faraday//lib/faraday/utils/headers.rb#80
  def has_key?(key); end

  # source://faraday//lib/faraday/utils/headers.rb#80
  def include?(key); end

  # source://faraday//lib/faraday/utils/headers.rb#26
  def initialize_names; end

  # source://faraday//lib/faraday/utils/headers.rb#80
  def key?(key); end

  # source://faraday//lib/faraday/utils/headers.rb#80
  def member?(key); end

  # source://faraday//lib/faraday/utils/headers.rb#95
  def merge(other); end

  # source://faraday//lib/faraday/utils/headers.rb#88
  def merge!(other); end

  # source://faraday//lib/faraday/utils/headers.rb#111
  def parse(header_string); end

  # source://faraday//lib/faraday/utils/headers.rb#100
  def replace(other); end

  # source://faraday//lib/faraday/utils/headers.rb#107
  def to_hash; end

  # source://faraday//lib/faraday/utils/headers.rb#88
  def update(other); end

  protected

  # source://faraday//lib/faraday/utils/headers.rb#129
  def names; end

  private

  # source://faraday//lib/faraday/utils/headers.rb#134
  def add_parsed(key, value); end

  # source://faraday//lib/faraday/utils/headers.rb#31
  def initialize_copy(other); end

  class << self
    # source://faraday//lib/faraday/utils/headers.rb#14
    def allocate; end

    # source://faraday//lib/faraday/utils/headers.rb#10
    def from(value); end
  end
end

# source://faraday//lib/faraday/utils/headers.rb#40
Faraday::Utils::Headers::KeyMap = T.let(T.unsafe(nil), Hash)

# source://faraday//lib/faraday/utils/params_hash.rb#6
class Faraday::Utils::ParamsHash < ::Hash
  # source://faraday//lib/faraday/utils/params_hash.rb#7
  def [](key); end

  # source://faraday//lib/faraday/utils/params_hash.rb#11
  def []=(key, value); end

  # source://faraday//lib/faraday/utils/params_hash.rb#15
  def delete(key); end

  # source://faraday//lib/faraday/utils/params_hash.rb#19
  def has_key?(key); end

  # source://faraday//lib/faraday/utils/params_hash.rb#19
  def include?(key); end

  # source://faraday//lib/faraday/utils/params_hash.rb#19
  def key?(key); end

  # source://faraday//lib/faraday/utils/params_hash.rb#19
  def member?(key); end

  # source://faraday//lib/faraday/utils/params_hash.rb#35
  def merge(params); end

  # source://faraday//lib/faraday/utils/params_hash.rb#27
  def merge!(params); end

  # source://faraday//lib/faraday/utils/params_hash.rb#44
  def merge_query(query, encoder = T.unsafe(nil)); end

  # source://faraday//lib/faraday/utils/params_hash.rb#39
  def replace(other); end

  # source://faraday//lib/faraday/utils/params_hash.rb#50
  def to_query(encoder = T.unsafe(nil)); end

  # source://faraday//lib/faraday/utils/params_hash.rb#27
  def update(params); end

  private

  # source://faraday//lib/faraday/utils/params_hash.rb#56
  def convert_key(key); end
end

# source://faraday//lib/faraday/version.rb#4
Faraday::VERSION = T.let(T.unsafe(nil), String)
