# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ice_nine` gem.
# Please instead update this file by running `bin/tapioca gem ice_nine`.


# source://ice_nine//lib/ice_nine/support/recursion_guard.rb#3
module IceNine
  class << self
    # source://ice_nine//lib/ice_nine.rb#37
    def deep_freeze(object); end

    # source://ice_nine//lib/ice_nine.rb#58
    def deep_freeze!(object); end
  end
end

# source://ice_nine//lib/ice_nine/freezer.rb#6
class IceNine::Freezer
  class << self
    # source://ice_nine//lib/ice_nine/freezer.rb#27
    def [](mod); end

    # source://ice_nine//lib/ice_nine/freezer.rb#40
    def deep_freeze(object); end

    # source://ice_nine//lib/ice_nine/freezer.rb#53
    def deep_freeze!(object); end

    protected

    # source://ice_nine//lib/ice_nine/freezer.rb#86
    def const_lookup(namespace); end

    # source://ice_nine//lib/ice_nine/freezer.rb#98
    def guarded_deep_freeze(object, recursion_guard); end

    private

    # source://ice_nine//lib/ice_nine/freezer.rb#67
    def find(name); end
  end
end

# source://ice_nine//lib/ice_nine/freezer/array.rb#7
class IceNine::Freezer::Array < ::IceNine::Freezer::Object
  class << self
    # source://ice_nine//lib/ice_nine/freezer/array.rb#19
    def guarded_deep_freeze(array, recursion_guard); end
  end
end

# source://ice_nine//lib/ice_nine/freezer/object.rb#47
IceNine::Freezer::BasicObject = IceNine::Freezer::Object

# source://ice_nine//lib/ice_nine/freezer/false_class.rb#7
class IceNine::Freezer::FalseClass < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/hash.rb#7
class IceNine::Freezer::Hash < ::IceNine::Freezer::Object
  class << self
    # source://ice_nine//lib/ice_nine/freezer/hash.rb#20
    def guarded_deep_freeze(hash, recursion_guard); end

    private

    # source://ice_nine//lib/ice_nine/freezer/hash.rb#35
    def freeze_key_value_pairs(hash, recursion_guard); end
  end
end

# source://ice_nine//lib/ice_nine/freezer/hash/state.rb#8
class IceNine::Freezer::Hash::State < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/module.rb#7
class IceNine::Freezer::Module < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/nil_class.rb#7
class IceNine::Freezer::NilClass < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/no_freeze.rb#7
class IceNine::Freezer::NoFreeze < ::IceNine::Freezer
  class << self
    # source://ice_nine//lib/ice_nine/freezer/no_freeze.rb#19
    def guarded_deep_freeze(object, _recursion_guard); end
  end
end

# source://ice_nine//lib/ice_nine/freezer/numeric.rb#7
class IceNine::Freezer::Numeric < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/object.rb#7
class IceNine::Freezer::Object < ::IceNine::Freezer
  class << self
    # source://ice_nine//lib/ice_nine/freezer/object.rb#18
    def guarded_deep_freeze(object, recursion_guard); end

    private

    # source://ice_nine//lib/ice_nine/freezer/object.rb#34
    def freeze_instance_variables(object, recursion_guard); end
  end
end

# source://ice_nine//lib/ice_nine/freezer/range.rb#7
class IceNine::Freezer::Range < ::IceNine::Freezer::Object
  class << self
    # source://ice_nine//lib/ice_nine/freezer/range.rb#20
    def guarded_deep_freeze(range, recursion_guard); end
  end
end

# source://ice_nine//lib/ice_nine/freezer/rubinius.rb#7
class IceNine::Freezer::Rubinius < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/struct.rb#7
class IceNine::Freezer::Struct < ::IceNine::Freezer::Array; end

# source://ice_nine//lib/ice_nine/freezer/symbol.rb#7
class IceNine::Freezer::Symbol < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/freezer/true_class.rb#7
class IceNine::Freezer::TrueClass < ::IceNine::Freezer::NoFreeze; end

# source://ice_nine//lib/ice_nine/support/recursion_guard.rb#8
class IceNine::RecursionGuard; end

# source://ice_nine//lib/ice_nine/support/recursion_guard.rb#42
class IceNine::RecursionGuard::Frozen < ::IceNine::RecursionGuard
  # source://ice_nine//lib/ice_nine/support/recursion_guard.rb#49
  def guard(object); end
end

# source://ice_nine//lib/ice_nine/support/recursion_guard.rb#12
class IceNine::RecursionGuard::ObjectSet < ::IceNine::RecursionGuard
  # source://ice_nine//lib/ice_nine/support/recursion_guard.rb#17
  def initialize; end

  # source://ice_nine//lib/ice_nine/support/recursion_guard.rb#32
  def guard(object); end
end

# source://ice_nine//lib/ice_nine/version.rb#6
IceNine::VERSION = T.let(T.unsafe(nil), String)
