# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `json` gem.
# Please instead update this file by running `bin/tapioca gem json`.


# source://json//lib/json/version.rb#3
module JSON
  private

  # source://json//lib/json/common.rb#932
  def dump(obj, anIO = T.unsafe(nil), limit = T.unsafe(nil), kwargs = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#462
  def fast_generate(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#977
  def fast_unparse(*_arg0, **_arg1, &_arg2); end

  # source://json//lib/json/common.rb#441
  def generate(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#856
  def load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#390
  def load_file(filespec, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#401
  def load_file!(filespec, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#353
  def parse(source, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#375
  def parse!(source, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#509
  def pretty_generate(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#987
  def pretty_unparse(*_arg0, **_arg1, &_arg2); end

  # source://json//lib/json/common.rb#997
  def restore(*_arg0, **_arg1, &_arg2); end

  # source://json//lib/json/common.rb#967
  def unparse(*_arg0, **_arg1, &_arg2); end

  # source://json//lib/json/common.rb#685
  def unsafe_load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  class << self
    # source://json//lib/json/common.rb#132
    def [](object, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#236
    def create_id; end

    # source://json//lib/json/common.rb#230
    def create_id=(new_value); end

    # source://json//lib/json/common.rb#104
    def deprecation_warning(message, uplevel = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#932
    def dump(obj, anIO = T.unsafe(nil), limit = T.unsafe(nil), kwargs = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#462
    def fast_generate(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#977
    def fast_unparse(*_arg0, **_arg1, &_arg2); end

    # source://json//lib/json/common.rb#441
    def generate(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#179
    def generator; end

    # source://json//lib/json/common.rb#156
    def generator=(generator); end

    # source://json//lib/json/common.rb#856
    def load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#390
    def load_file(filespec, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#401
    def load_file!(filespec, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#353
    def parse(source, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#375
    def parse!(source, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#146
    def parser; end

    # source://json//lib/json/common.rb#149
    def parser=(parser); end

    # source://json//lib/json/common.rb#509
    def pretty_generate(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#987
    def pretty_unparse(*_arg0, **_arg1, &_arg2); end

    # source://json//lib/json/common.rb#997
    def restore(*_arg0, **_arg1, &_arg2); end

    # source://json//lib/json/common.rb#182
    def state; end

    # source://json//lib/json/common.rb#182
    def state=(_arg0); end

    # source://json//lib/json/common.rb#967
    def unparse(*_arg0, **_arg1, &_arg2); end

    # source://json//lib/json/common.rb#685
    def unsafe_load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    private

    # source://json//lib/json/common.rb#1010
    def const_missing(const_name); end

    # source://json//lib/json/common.rb#205
    def deprecated_singleton_attr_accessor(*attrs); end

    # source://json//lib/json/common.rb#187
    def on_mixed_keys_hash(hash, do_raise); end
  end
end

# source://json//lib/json/common.rb#1036
class JSON::Coder
  # source://json//lib/json/common.rb#1061
  def initialize(options = T.unsafe(nil), &as_json); end

  # source://json//lib/json/common.rb#1079
  def dump(object, io = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#1079
  def generate(object, io = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#1088
  def load(source); end

  # source://json//lib/json/common.rb#1097
  def load_file(path); end

  # source://json//lib/json/common.rb#1088
  def parse(source); end
end

# source://json//lib/json/ext/generator/state.rb#6
class JSON::Ext::Generator::State
  # source://json//lib/json/ext/generator/state.rb#13
  def initialize(opts = T.unsafe(nil)); end

  # source://json//lib/json/ext/generator/state.rb#77
  def [](name); end

  # source://json//lib/json/ext/generator/state.rb#91
  def []=(name, value); end

  # source://json//lib/json/ext/generator/state.rb#23
  def configure(opts); end

  # source://json//lib/json/ext/generator/state.rb#23
  def merge(opts); end

  # source://json//lib/json/ext/generator/state.rb#42
  def to_h; end

  # source://json//lib/json/ext/generator/state.rb#42
  def to_hash; end
end

# source://json//lib/json/ext.rb#9
class JSON::Ext::Parser
  # source://json//lib/json/ext.rb#17
  def initialize(source, opts = T.unsafe(nil)); end

  # source://json//lib/json/ext.rb#26
  def parse; end

  # source://json//lib/json/ext.rb#22
  def source; end
end

# source://json//lib/json/ext.rb#32
JSON::Ext::Parser::Config = JSON::Ext::ParserConfig

# source://json//lib/json/common.rb#289
class JSON::Fragment < ::Struct
  # source://json//lib/json/common.rb#290
  def initialize(json); end

  def json; end
  def json=(_); end

  # source://json//lib/json/common.rb#298
  def to_json(state = T.unsafe(nil), *_arg1); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://json//lib/json/common.rb#259
class JSON::GeneratorError < ::JSON::JSONError
  # source://json//lib/json/common.rb#262
  def initialize(message, invalid_object = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#267
  def detailed_message(*_arg0, **_arg1, &_arg2); end

  # source://json//lib/json/common.rb#260
  def invalid_object; end
end

# source://json//lib/json/common.rb#1102
module JSON::GeneratorMethods
  # source://json//lib/json/common.rb#1110
  def to_json(state = T.unsafe(nil), *_arg1); end
end

# source://json//lib/json/generic_object.rb#9
class JSON::GenericObject < ::OpenStruct
  # source://json//lib/json/generic_object.rb#59
  def as_json(*_arg0); end

  # source://json//lib/json/generic_object.rb#51
  def to_hash; end

  # source://json//lib/json/generic_object.rb#63
  def to_json(*a); end

  # source://json//lib/json/generic_object.rb#55
  def |(other); end

  class << self
    # source://json//lib/json/generic_object.rb#45
    def dump(obj, *args); end

    # source://json//lib/json/generic_object.rb#25
    def from_hash(object); end

    # source://json//lib/json/generic_object.rb#17
    def json_creatable=(_arg0); end

    # source://json//lib/json/generic_object.rb#13
    def json_creatable?; end

    # source://json//lib/json/generic_object.rb#19
    def json_create(data); end

    # source://json//lib/json/generic_object.rb#40
    def load(source, proc = T.unsafe(nil), opts = T.unsafe(nil)); end
  end
end

# source://json//lib/json/common.rb#358
JSON::PARSE_L_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://json//lib/json/common.rb#471
JSON::PRETTY_GENERATE_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://json//lib/json/common.rb#152
JSON::Parser = JSON::Ext::Parser

# source://json//lib/json/common.rb#250
class JSON::ParserError < ::JSON::JSONError
  # source://json//lib/json/common.rb#251
  def column; end

  # source://json//lib/json/common.rb#251
  def line; end
end

# source://json//lib/json/common.rb#8
module JSON::ParserOptions
  class << self
    # source://json//lib/json/common.rb#10
    def prepare(opts); end

    private

    # source://json//lib/json/common.rb#40
    def array_class_proc(array_class, on_load); end

    # source://json//lib/json/common.rb#52
    def create_additions_proc(opts); end

    # source://json//lib/json/common.rb#95
    def create_additions_warning; end

    # source://json//lib/json/common.rb#29
    def object_class_proc(object_class, on_load); end
  end
end

# source://json//lib/json/common.rb#173
JSON::State = JSON::Ext::Generator::State

# source://json//lib/json/common.rb#1127
module Kernel
  private

  # source://json//lib/json/common.rb#1166
  def JSON(object, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#1132
  def j(*objs); end

  # source://json//lib/json/common.rb#1147
  def jj(*objs); end
end

# source://json//lib/json/common.rb#1171
class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
  include ::JSON::GeneratorMethods
end
