# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `memoizable` gem.
# Please instead update this file by running `bin/tapioca gem memoizable`.


# source://memoizable//lib/memoizable/instance_methods.rb#3
module Memoizable
  include ::Memoizable::InstanceMethods

  mixes_in_class_methods ::Memoizable::ModuleMethods

  class << self
    private

    # source://memoizable//lib/memoizable.rb#27
    def included(descendant); end
  end
end

# source://memoizable//lib/memoizable.rb#17
Memoizable::Freezer = T.let(T.unsafe(nil), Proc)

# source://memoizable//lib/memoizable/instance_methods.rb#6
module Memoizable::InstanceMethods
  # source://memoizable//lib/memoizable/instance_methods.rb#16
  def freeze; end

  # source://memoizable//lib/memoizable/instance_methods.rb#32
  def memoize(data); end

  private

  # source://memoizable//lib/memoizable/instance_methods.rb#44
  def memoized_method_cache; end
end

# source://memoizable//lib/memoizable/memory.rb#6
class Memoizable::Memory
  # source://memoizable//lib/memoizable/memory.rb#15
  def initialize; end

  # source://memoizable//lib/memoizable/memory.rb#28
  def [](name); end

  # source://memoizable//lib/memoizable/memory.rb#42
  def []=(name, value); end

  # source://memoizable//lib/memoizable/memory.rb#59
  def fetch(name); end

  # source://memoizable//lib/memoizable/memory.rb#76
  def key?(name); end

  # source://memoizable//lib/memoizable/memory.rb#86
  def marshal_dump; end

  # source://memoizable//lib/memoizable/memory.rb#98
  def marshal_load(hash); end
end

# source://memoizable//lib/memoizable/method_builder.rb#6
class Memoizable::MethodBuilder
  # source://memoizable//lib/memoizable/method_builder.rb#55
  def initialize(descendant, method_name, freezer); end

  # source://memoizable//lib/memoizable/method_builder.rb#72
  def call; end

  # source://memoizable//lib/memoizable/method_builder.rb#44
  def original_method; end

  private

  # source://memoizable//lib/memoizable/method_builder.rb#90
  def assert_arity(arity); end

  # source://memoizable//lib/memoizable/method_builder.rb#111
  def create_memoized_method; end

  # source://memoizable//lib/memoizable/method_builder.rb#101
  def remove_original_method; end

  # source://memoizable//lib/memoizable/method_builder.rb#128
  def set_method_visibility; end

  # source://memoizable//lib/memoizable/method_builder.rb#137
  def visibility; end
end

# source://memoizable//lib/memoizable/method_builder.rb#25
class Memoizable::MethodBuilder::BlockNotAllowedError < ::ArgumentError
  # source://memoizable//lib/memoizable/method_builder.rb#33
  def initialize(descendant, method); end
end

# source://memoizable//lib/memoizable/method_builder.rb#9
class Memoizable::MethodBuilder::InvalidArityError < ::ArgumentError
  # source://memoizable//lib/memoizable/method_builder.rb#18
  def initialize(descendant, method, arity); end
end

# source://memoizable//lib/memoizable/module_methods.rb#6
module Memoizable::ModuleMethods
  # source://memoizable//lib/memoizable/module_methods.rb#13
  def freezer; end

  # source://memoizable//lib/memoizable/module_methods.rb#28
  def memoize(*methods); end

  # source://memoizable//lib/memoizable/module_methods.rb#53
  def memoized?(name); end

  # source://memoizable//lib/memoizable/module_methods.rb#80
  def unmemoized_instance_method(name); end

  private

  # source://memoizable//lib/memoizable/module_methods.rb#94
  def included(descendant); end

  # source://memoizable//lib/memoizable/module_methods.rb#107
  def memoize_method(method_name); end

  # source://memoizable//lib/memoizable/module_methods.rb#120
  def memoized_methods; end
end

# source://memoizable//lib/memoizable/version.rb#6
Memoizable::VERSION = T.let(T.unsafe(nil), String)
