# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `memosa` gem.
# Please instead update this file by running `bin/tapioca gem memosa`.


# source://memosa//lib/memosa/cache.rb#3
# typed: strong
# Memosa provides a simple way to memoize methods in Ruby.
module Memosa
  # source://memosa//lib/memosa.rb#35
  # Convert a method to a memoized method
  #
  # Memosa does not support memoizing methods that accept arguments.
  # _@param_ `method_name` — the name of the method to memoize
  # _@return_ — the name of the memoized method
  # ```ruby
  # class State
  #   extend Memosa
  #   memoize def id
  #     SecureRandom.uuid
  #   end
  # end
  # ```
  sig { params(method_name: Symbol).returns(Symbol) }
  def memoize(method_name); end

  # source://memosa//lib/memosa.rb#72
  # Define and prepend MemosaMethods
  #
  # When {memoize} is called, Memosa will define a module named MemosaMethods. Memoized
  # methods will be defined on this module and then prepended to the class.
  # This method allows you to force that module to be defined and prepended, which is
  # useful when order matters.
  # ```ruby
  # class Foo
  #   extend Memosa
  #   prepend_memosa
  # end
  # ```
  sig { returns(Module) }
  def prepend_memosa; end

  class << self
    # source://memosa//lib/memosa.rb#13
    # Called when Memosa is extended
    #
    # _@param_ `base`
    sig { params(base: Module).void }
    def extended(base); end

    # source://memosa//lib/memosa.rb#87
    # Reset an object's memoization cache
    #
    # _@param_ `object`
    # ```ruby
    # Memosa.reset(user)
    # ```
    sig { params(object: Object).void }
    def reset(object); end
  end
end

# source://memosa//lib/memosa.rb#110
# This module provides a {#memosa} helper that can be used to manipulate the
# memoization cache directly.
module Memosa::API
  # source://memosa//lib/memosa.rb#128
  # Used to manipulate the memoized cache directly
  #
  # ```ruby
  # class State
  #   extend Memosa
  #   include Memosa::API
  #   memoize def id
  #     SecureRandom.uuid
  #   end
  #   def reset!
  #     memosa.clear
  # end
  # ```
  sig { returns(Memosa::Cache) }
  def memosa; end
end

# source://memosa//lib/memosa/cache.rb#6
# This class is used to interact with the memoization cache.
# @api public
class Memosa::Cache
  # source://memosa//lib/memosa/cache.rb#11
  # Create a new instance of {Cache}
  #
  # _@param_ `cache` — the memoization cache
  sig { params(cache: T::Hash[Symbol, BasicObject]).void }
  def initialize(cache); end

  # source://memosa//lib/memosa/cache.rb#33
  # Reset the cache
  #
  # ```ruby
  # memosa.clear
  # ```
  sig { returns(T.self_type) }
  def clear; end

  # source://memosa//lib/memosa/cache.rb#45
  # Delete a key from the cache
  #
  # _@param_ `key`
  # ```ruby
  # memosa.delete(:foo)
  # ```
  sig { params(key: Symbol).returns(T.self_type) }
  def delete(key); end

  # source://memosa//lib/memosa/cache.rb#22
  # Add values to the cache
  #
  # _@param_ `values` — the values to add to the cache.
  # ```ruby
  # memosa.merge!(foo: "bar")
  # ```
  sig { params(values: T::Hash[Symbol, BasicObject]).returns(T.self_type) }
  def merge!(values); end
end

# source://memosa//lib/memosa.rb#96
module Memosa::Initializer
  # source://memosa//lib/memosa.rb#102
  def freeze; end
end

# source://memosa//lib/memosa/internal.rb#6
module Memosa::Internal
  class << self
    # source://memosa//lib/memosa/internal.rb#29
    def method_defined?(owner, method_name); end

    # source://memosa//lib/memosa/internal.rb#12
    def visibility(owner, method_name); end
  end
end

# source://memosa//lib/memosa/version.rb#6
Memosa::VERSION = T.let(T.unsafe(nil), String)

module RuboCop
  module Cop
    # Memosa includes a set of RuboCop rules that encourage best practices when using
    # memosa.
    #
    # Add the following configuration to your `.rubocop.yml`:
    #
    # @example
    #   inherit_gem:
    #     memosa: config/rubocop.yml
    module Memosa
      # This cop checks for memoized methods that accept arguments or yield.
      #
      # @example
      #   # bad
      #   def foo; end
      #   memoize :foo
      #
      #   # good
      #   memoize def foo; end
      class MethodDefinition < RuboCop::Cop::Base
        MSG = T.let("`memoize` should precede a method definition (e.g. `memoize def`)", T.untyped)
      end

      # This cop checks for memoized methods that accept arguments or yield.
      #
      # @example
      #   # bad
      #   memoize def foo(a); end
      #
      #   # good
      #   memoize def foo; end
      class MethodSignature < RuboCop::Cop::Base
        MSG = T.let("Memoized methods should not accept arguments or yield", T.untyped)
      end
    end
  end
end
