# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `morpher` gem.
# Please instead update this file by running `bin/tapioca gem morpher`.


# source://morpher//lib/morpher.rb#9
module Morpher; end

# source://morpher//lib/morpher.rb#12
Morpher::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# source://morpher//lib/morpher.rb#10
Morpher::Either = MPrelude::Either

# source://morpher//lib/morpher/newtype.rb#5
class Morpher::Newtype < ::Module
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/newtype.rb#9
  def included(host); end
end

# source://morpher//lib/morpher/record.rb#5
class Morpher::Record < ::Module
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/record.rb#19
  def included(host); end

  # source://anima/0.3.2/lib/anima.rb#142
  def optional; end

  # source://anima/0.3.2/lib/anima.rb#142
  def required; end

  private

  # source://morpher//lib/morpher/record.rb#49
  def transform(attributes); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end

    # source://morpher//lib/morpher/record.rb#13
    def new(**attributes); end
  end
end

# source://morpher//lib/morpher/record.rb#6
Morpher::Record::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://morpher//lib/morpher/transform.rb#5
class Morpher::Transform
  include ::AbstractType
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::AbstractType::AbstractMethodDeclarations
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods

  # source://morpher//lib/morpher/transform.rb#35
  def array; end

  # source://abstract_type/0.0.7/lib/abstract_type.rb#111
  def call(*_arg0); end

  # source://morpher//lib/morpher/transform.rb#42
  def maybe; end

  # source://morpher//lib/morpher/transform.rb#28
  def seq(transform); end

  # source://morpher//lib/morpher/transform.rb#12
  def slug; end

  # source://morpher//lib/morpher/transform.rb#49
  def to_proc; end

  private

  # source://morpher//lib/morpher/transform.rb#137
  def error(input:, cause: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://morpher//lib/morpher/transform.rb#154
  def failure(value); end

  # source://morpher//lib/morpher/transform.rb#146
  def lift_error(error); end

  # source://morpher//lib/morpher/transform.rb#158
  def success(value); end

  # source://morpher//lib/morpher/transform.rb#150
  def wrap_error(error); end

  class << self
    # source://abstract_type/0.0.7/lib/abstract_type.rb#33
    def new(*args, &block); end
  end
end

# source://morpher//lib/morpher/transform.rb#264
class Morpher::Transform::Array < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#277
  def call(input); end

  private

  # source://morpher//lib/morpher/transform.rb#287
  def run(input); end
end

# source://morpher//lib/morpher/transform.rb#267
Morpher::Transform::Array::MESSAGE = T.let(T.unsafe(nil), String)

# source://morpher//lib/morpher/transform.rb#268
Morpher::Transform::Array::PRIMITIVE = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://morpher//lib/morpher/transform.rb#521
Morpher::Transform::BOOLEAN = T.let(T.unsafe(nil), Morpher::Transform::Boolean)

# source://morpher//lib/morpher/transform.rb#110
class Morpher::Transform::Block < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://anima/0.3.2/lib/anima.rb#142
  def block; end

  # source://morpher//lib/morpher/transform.rb#117
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def name; end

  # source://morpher//lib/morpher/transform.rb#130
  def slug; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end

    # source://morpher//lib/morpher/transform.rb#113
    def capture(name, &block); end
  end
end

# source://morpher//lib/morpher/transform.rb#237
class Morpher::Transform::Boolean < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#249
  def call(input); end
end

# source://morpher//lib/morpher/transform.rb#240
Morpher::Transform::Boolean::MESSAGE = T.let(T.unsafe(nil), String)

# source://morpher//lib/morpher/transform.rb#54
class Morpher::Transform::Error
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods

  # source://anima/0.3.2/lib/anima.rb#142
  def cause; end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def compact_message(&block); end

  # source://anima/0.3.2/lib/anima.rb#142
  def input; end

  # source://anima/0.3.2/lib/anima.rb#142
  def message; end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def trace(&block); end

  # source://anima/0.3.2/lib/anima.rb#142
  def transform; end

  private

  # source://morpher//lib/morpher/transform.rb#85
  def path; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://morpher//lib/morpher/transform.rb#63
Morpher::Transform::Error::COMPACT = T.let(T.unsafe(nil), String)

# source://morpher//lib/morpher/transform.rb#479
class Morpher::Transform::Exception < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#487
  def call(input); end
end

# source://morpher//lib/morpher/transform.rb#522
Morpher::Transform::FLOAT = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://morpher//lib/morpher/transform.rb#308
class Morpher::Transform::Hash < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#363
  def call(input); end

  # source://anima/0.3.2/lib/anima.rb#142
  def optional; end

  # source://anima/0.3.2/lib/anima.rb#142
  def required; end

  private

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def allowed_keys(&block); end

  # source://morpher//lib/morpher/transform.rb#411
  def coerce_key(key, input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def defaults(&block); end

  # source://morpher//lib/morpher/transform.rb#418
  def reject_keys(input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def required_keys(&block); end

  # source://morpher//lib/morpher/transform.rb#373
  def transform(input); end

  # source://morpher//lib/morpher/transform.rb#396
  def transform_keys(keys, input); end

  # source://morpher//lib/morpher/transform.rb#388
  def transform_optional(input); end

  # source://morpher//lib/morpher/transform.rb#379
  def transform_required(input); end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end
  end
end

# source://morpher//lib/morpher/transform.rb#311
Morpher::Transform::Hash::KEY_MESSAGE = T.let(T.unsafe(nil), String)

# source://morpher//lib/morpher/transform.rb#335
class Morpher::Transform::Hash::Key < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#351
  def call(input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def slug(&block); end

  # source://concord/0.1.6/lib/concord.rb#67
  def transform; end

  # source://concord/0.1.6/lib/concord.rb#67
  def value; end
end

# source://morpher//lib/morpher/transform.rb#312
Morpher::Transform::Hash::PRIMITIVE = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://morpher//lib/morpher/transform.rb#317
class Morpher::Transform::Hash::Symbolize < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#325
  def call(input); end
end

# source://morpher//lib/morpher/transform.rb#523
Morpher::Transform::INTEGER = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://morpher//lib/morpher/transform.rb#163
class Morpher::Transform::Index < ::Morpher::Transform
  include ::Anima::InstanceMethods
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#188
  def call(input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def slug(&block); end

  private

  # source://anima/0.3.2/lib/anima.rb#142
  def index; end

  # source://anima/0.3.2/lib/anima.rb#142
  def transform; end

  class << self
    # source://anima/0.3.2/lib/anima.rb#136
    def anima; end

    # source://morpher//lib/morpher/transform.rb#174
    def wrap(cause, index); end
  end
end

# source://morpher//lib/morpher/transform.rb#509
class Morpher::Transform::Maybe < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#512
  def call(input); end
end

# source://morpher//lib/morpher/transform.rb#91
class Morpher::Transform::Named < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#97
  def call(input); end

  # source://morpher//lib/morpher/transform.rb#104
  def slug; end
end

# source://morpher//lib/morpher/transform.rb#202
class Morpher::Transform::Primitive < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#214
  def call(input); end

  # source://memoizable/0.4.2/lib/memoizable/method_builder.rb#114
  def slug(&block); end
end

# source://morpher//lib/morpher/transform.rb#205
Morpher::Transform::Primitive::MESSAGE = T.let(T.unsafe(nil), String)

# source://morpher//lib/morpher/transform.rb#524
Morpher::Transform::STRING = T.let(T.unsafe(nil), Morpher::Transform::Primitive)

# source://morpher//lib/morpher/transform.rb#525
Morpher::Transform::STRING_ARRAY = T.let(T.unsafe(nil), Morpher::Transform::Array)

# source://morpher//lib/morpher/transform.rb#448
class Morpher::Transform::Sequence < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#465
  def call(input); end

  # source://morpher//lib/morpher/transform.rb#456
  def seq(transform); end
end

# source://morpher//lib/morpher/transform.rb#495
class Morpher::Transform::Success < ::Morpher::Transform
  include ::Equalizer::Methods

  # source://morpher//lib/morpher/transform.rb#503
  def call(input); end
end
