# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mprelude` gem.
# Please instead update this file by running `bin/tapioca gem mprelude`.


# source://mprelude//lib/mprelude.rb#7
module MPrelude; end

# source://mprelude//lib/mprelude.rb#71
class MPrelude::Either
  include ::AbstractType
  include ::MPrelude::RequireBlock
  include ::Equalizer::Methods
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat
  extend ::AbstractType::AbstractMethodDeclarations

  # source://mprelude//lib/mprelude.rb#93
  def left?; end

  # source://mprelude//lib/mprelude.rb#100
  def right?; end

  class << self
    # source://abstract_type/0.0.7/lib/abstract_type.rb#33
    def new(*args, &block); end

    # source://mprelude//lib/mprelude.rb#84
    def wrap_error(*exceptions); end
  end
end

# source://mprelude//lib/mprelude.rb#104
class MPrelude::Either::Left < ::MPrelude::Either
  # source://mprelude//lib/mprelude.rb#115
  def bind(&block); end

  # source://mprelude//lib/mprelude.rb#151
  def either(left, _right); end

  # source://mprelude//lib/mprelude.rb#108
  def fmap(&block); end

  # source://mprelude//lib/mprelude.rb#122
  def from_left; end

  # source://mprelude//lib/mprelude.rb#131
  def from_right; end

  # source://mprelude//lib/mprelude.rb#143
  def lmap; end
end

# source://mprelude//lib/mprelude.rb#156
class MPrelude::Either::Right < ::MPrelude::Either
  # source://mprelude//lib/mprelude.rb#167
  def bind; end

  # source://mprelude//lib/mprelude.rb#203
  def either(_left, right); end

  # source://mprelude//lib/mprelude.rb#160
  def fmap; end

  # source://mprelude//lib/mprelude.rb#176
  def from_left; end

  # source://mprelude//lib/mprelude.rb#188
  def from_right; end

  # source://mprelude//lib/mprelude.rb#195
  def lmap(&block); end
end

# source://mprelude//lib/mprelude.rb#25
class MPrelude::Maybe
  include ::AbstractType
  include ::MPrelude::RequireBlock
  include ::Adamantium::Flat
  include ::Adamantium
  include ::Memoizable::InstanceMethods
  include ::Memoizable
  extend ::Memoizable::ModuleMethods
  extend ::Adamantium::ModuleMethods
  extend ::Adamantium::ClassMethods
  extend ::Adamantium::Flat
  extend ::AbstractType::AbstractMethodDeclarations

  class << self
    # source://abstract_type/0.0.7/lib/abstract_type.rb#33
    def new(*args, &block); end
  end
end

# source://mprelude//lib/mprelude.rb#52
class MPrelude::Maybe::Just < ::MPrelude::Maybe
  include ::Equalizer::Methods

  # source://mprelude//lib/mprelude.rb#65
  def bind; end

  # source://mprelude//lib/mprelude.rb#58
  def fmap; end
end

# source://mprelude//lib/mprelude.rb#32
class MPrelude::Maybe::Nothing < ::MPrelude::Maybe
  # source://mprelude//lib/mprelude.rb#47
  def bind(&block); end

  # source://mprelude//lib/mprelude.rb#40
  def fmap(&block); end

  # source://mprelude//lib/mprelude.rb#35
  def new; end
end

# source://mprelude//lib/mprelude.rb#8
module MPrelude::RequireBlock
  include ::AbstractType
  extend ::AbstractType::AbstractMethodDeclarations

  private

  # source://mprelude//lib/mprelude.rb#19
  def require_block; end

  class << self
    # source://abstract_type/0.0.7/lib/abstract_type.rb#33
    def new(*args, &block); end
  end
end
